import test from 'node:test';import assert from 'node:assert/strict';
import {boardActor,boardModerator,boardVisible,boardThreadVisible,boardProjection,boardAudience,boardContent,boardUuid} from '../src/board-policy.js';
const player=id=>boardActor({role:'player',playerId:id}),host=id=>boardActor({role:'streamer_admin',streamer_id:id}),supervisor=boardActor({role:'super_admin'});
const post={id:'bd310611-7792-45f6-810f-1ea9bd75a014',seq:1,root_id:null,scope:'streamer',streamer_id:'papa',author_key:'player:A',visibility:'public',targets:[],body:'Hello',anonymous:true,version:1,deleted:false};
test('board requires server-authenticated identities',()=>{for(const a of [null,{}, {role:'player'},{role:'guest'}])assert.throws(()=>boardActor(a));assert.equal(player('A').key,'player:A');assert.equal(host('papa').key,'streamer:papa');assert.equal(boardActor({role:'admin'}).role,'super');});
test('visibility matrix: public, include, exclude, streamers and management',()=>{
 const actors=[player('A'),player('B'),player('C'),host('papa'),host('michelle'),supervisor];
 for(const [visibility,expected] of [['public',[true,true,true,true,true,true]],['include',[true,true,false,true,false,true]],['exclude',[true,false,true,true,true,true]],['streamers',[true,false,false,true,true,true]]]){
  const p={...post,visibility,targets:['player:B']};assert.deepEqual(actors.map(a=>boardVisible(a,p)),expected,visibility);
 }
});
test('global board does not grant a streamer global moderation or anonymous access',()=>{const p={...post,scope:'global',streamer_id:'__global__',visibility:'include',targets:[]};assert.equal(boardModerator(host('papa'),p),false);assert.equal(boardVisible(host('papa'),p),false);assert.equal(boardVisible(supervisor,p),true);});
test('excluded moderators keep scoped management; other hosts cannot reveal identities',()=>{const p={...post,visibility:'exclude',targets:['streamer:papa','super']};assert.equal(boardVisible(host('papa'),p),true);assert.equal(boardVisible(supervisor,p),true);assert.equal(boardModerator(host('michelle'),p),false);});
test('blocks hide authors and cannot strip management or self visibility',()=>{const blocks=['player:A'];assert.equal(boardVisible(player('B'),post,blocks),false);assert.equal(boardVisible(player('A'),post,blocks),true);assert.equal(boardVisible(host('papa'),post,blocks),true);assert.equal(boardVisible(host('michelle'),post,blocks),false);});
test('reply cannot widen root audience even when reader authored the reply',()=>{const root={...post,visibility:'include',targets:['player:B']},reply={...post,root_id:post.id,author_key:'player:C'};assert.equal(boardThreadVisible(player('C'),reply,root),false);assert.equal(boardThreadVisible(player('B'),reply,root),true);assert.equal(boardThreadVisible(player('B'),reply,root,['player:A']),false);});
test('player who writes a streamer-only post can read its management replies',()=>{const root={...post,visibility:'streamers'},reply={...root,root_id:post.id,author_key:'streamer:papa'};assert.equal(boardThreadVisible(player('A'),reply,root),true);assert.equal(boardThreadVisible(player('B'),reply,root),false);assert.equal(boardThreadVisible(player('A'),reply,root,['streamer:papa']),false);});
test('anonymous API projection has no author keys, targets or private fields',()=>{for(const a of [player('A'),player('B'),host('michelle')]){const v=boardProjection(a,{...post,targets:['player:SECRET'],client_id:'secret',origin_room:'secret'},'Alice');assert.equal(v.author,'匿名使用者');assert.equal(v.managedAuthor,undefined);assert.ok(!JSON.stringify(v).includes('Alice'));for(const k of ['author_key','targets','client_id','origin_room'])assert.ok(!(k in v));}assert.equal(boardProjection(host('papa'),post,'Alice').managedAuthor,'Alice');assert.equal(boardProjection(supervisor,post,'Alice').managedAuthor,'Alice');});
test('removed content redacted for every role, original history not projected',()=>{for(const a of [player('A'),player('B'),host('papa'),supervisor])assert.equal(boardProjection(a,{...post,deleted:true},'Alice').body,'');});
test('audience validation rejects malformed entries and empties unused lists',()=>{assert.throws(()=>boardAudience('include',[]));assert.throws(()=>boardAudience('public',['admin:any']));assert.throws(()=>boardAudience('typo',[]));assert.throws(()=>boardAudience('include',Array(51).fill('player:A')));assert.deepEqual(boardAudience('include',['player:A','player:A','streamer:papa']).targets,['player:A','streamer:papa']);assert.deepEqual(boardAudience('public',['player:A']).targets,[]);});
test('post input limits and stable request IDs',()=>{assert.equal(boardContent(' hi '),'hi');for(const body of ['',null,' '.repeat(20),'a'.repeat(2001)])assert.throws(()=>boardContent(body));assert.equal(boardUuid(post.id),post.id);assert.throws(()=>boardUuid('1&select=*'));});
