import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';

test('selected review keeps Honey 2+1 / 2+2 isolated, private data intact and lyrics inherited',async t=>{
 const db=new PGlite({extensions:{pg_trgm}});t.after(()=>db.close());
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 const rpc=async(name,args=[])=>(await q('select '+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') value',args))[0].value;
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table papa_v2_entities(kind text,id text,data jsonb,primary key(kind,id));
 create table papa_v2_revision(id int primary key,revision bigint);insert into papa_v2_revision values(1,1);
 create table papa_notice_config(id text primary key,value jsonb);
 create function papa_v2_snapshot() returns jsonb language sql as $$select jsonb_build_object('rows',(select jsonb_agg(to_jsonb(e)) from papa_v2_entities e))$$;`);
 await db.exec(fs.readFileSync('supabase/migrations/202609240001_release_a.sql','utf8'));
 await db.exec(`create table papa_notifications(id uuid default gen_random_uuid(),streamer_id text,streamer_name text,recipient text,type text,level int,entity_id text,body text);`);
 for(const file of fs.readdirSync('supabase/migrations').filter(f=>/^2026100100\d\d_/.test(f)||/^20261005000[123]_/.test(f)).sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080001_catalog_integrated.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080002_catalog_hidden_search.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080003_catalog_filtered_search.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080004_catalog_room_status.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080005_catalog_import_matching.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080006_catalog_fuzzy_suggestions.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080007_catalog_variant_details.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610080008_catalog_review_versions.sql','utf8'));
 await q('insert into papa_v2_entities values($1,$2,$3)',['meta','1',{streamers:[{id:'papa',active:true},{id:'b',active:true},{id:'c',active:true},{id:'d',active:true}]}]);
 const originals=[];
 for(const [i,title] of ['Honey','Honey','Honey','Honey2','Honey2','Honey2','Honey2','Solo','Var','Var'].entries()){
  const song={songId:'s'+i,streamer_id:['papa','b','c','d'][i%4],title,artist:i===2?'Other':'Artist',cat:'華語',artistType:'女歌手',version:i===9?'Live':'',tags:['private'],key:'D',creditCost:2,privateNote:'note',lyrics:i%2===0?'lyrics '+i:''};originals.push(song);
  await q('insert into papa_v2_entities values($1,$2,$3)',['songs',song.songId,song]);
 }
 const selection=async ids=>{const rows=await q('select id,source_hash from papa_catalog_candidates where song_id=any($1) order by song_id',[ids]);return {ids:rows.map(r=>r.id),hashes:Object.fromEntries(rows.map(r=>[r.id,r.source_hash]))};};
 const review=async(ids,decision,extra={})=>{const a=await selection(ids);return rpc('papa_catalog_review_selected',[decision,a.ids,a.hashes,'president',extra.family||null,null,extra.metadata||{},extra.lyrics?a.ids[0]:null,null]);};
 const single=await rpc('papa_catalog_review_page',['singles']);assert.equal(single.total,1);assert.equal(single.rows[0].title,'Solo');
 const dup=await rpc('papa_catalog_review_page',['duplicates','', '',1,0]);assert.equal(dup.total,3);assert.equal(dup.rows.length,1);assert.equal(dup.rows[0].rows.length,3);assert.ok(dup.hasMore);assert.ok(!JSON.stringify(dup).includes('lyrics 0'));
 const a=await review(['s0','s1'],'confirm_same',{lyrics:true});
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'b','s1'])).body,'lyrics 0');
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'papa','s0'])).mode,'own');
 const residual=await rpc('papa_catalog_review_page',['duplicates','Honey']);assert.ok(residual.rows.some(g=>g.rows.length===1&&g.rows[0].songId==='s2'));
 const b=await review(['s2'],'independent');assert.notEqual(a.familyId,b.familyId);
 const c=await review(['s3','s4'],'confirm_same');const d=await review(['s5','s6'],'confirm_same');assert.notEqual(c.familyId,d.familyId);
 const versions=await review(['s8','s9'],'different_versions');const vrows=await q('select id from papa_catalog_variants where family_id=$1',[versions.familyId]);assert.equal(vrows.length,2);
 const families=await rpc('papa_catalog_families_page',['Honey',1,0]);assert.equal(families.rows.length,1);assert.equal(families.total,4);assert.equal(families.rows[0].variants.length,1);assert.ok(families.rows[0].variants[0].streamerCount>=1);assert.equal((await q('select count(*)::int n from papa_catalog_song_links where variant_id=$1',[a.variantId]))[0].n,2);assert.ok(!JSON.stringify(families).includes('streamerId'));
 const metadata=await rpc('papa_catalog_song_metadata',['b']);assert.equal(metadata.find(r=>r.songId==='s1').hasLyrics,true);assert.ok(!JSON.stringify(metadata).includes('lyrics 0'));
 await rpc('papa_catalog_save_lyric',[a.variantId,'new shared','president',true]);assert.equal((await rpc('papa_catalog_get_lyrics',[null,'b','s1'])).body,'new shared');assert.equal((await rpc('papa_catalog_get_lyrics',[null,'papa','s0'])).body,'lyrics 0');
 const lyricSearch=await rpc('papa_catalog_search_filtered',['new shared',20,0,'papa',null,null,'lyrics']);
 assert.ok(lyricSearch.rows.some(r=>r.id===a.variantId));assert.ok(!JSON.stringify(lyricSearch).includes('new shared'));
 await rpc('papa_catalog_lyric_choice',['papa','s0','shared',null,'retained note','streamer:papa']);assert.equal((await rpc('papa_catalog_get_lyrics',[null,'papa','s0'])).body,'new shared');assert.equal((await q("select body from papa_catalog_custom_archives where song_id='s0'"))[0].body,'lyrics 0');assert.equal((await rpc('papa_catalog_get_lyrics',[null,'papa','s0'])).privateNote,'retained note');
 const proposals=await rpc('papa_catalog_lyric_sources',[c.variantId,3,0]);assert.equal(proposals.total,1);
 const adoptable=await rpc('papa_catalog_families_page_v2',['Honey2','proposals',20,0]);
 assert.ok(adoptable.rows.flatMap(f=>f.variants).some(v=>v.variantId===c.variantId));
 assert.ok(!JSON.stringify(adoptable).includes('lyrics 4'));
 const source=proposals.rows[0];await rpc('papa_catalog_adopt_lyric',[c.variantId,source.streamerId,source.songId,'president',false,source.updatedAt]);assert.equal((await rpc('papa_catalog_get_lyrics',[c.variantId])).body,'lyrics 4');assert.equal((await rpc('papa_catalog_get_lyrics',[d.variantId])).body,'');
 await assert.rejects(review(['s7'],'confirm_same'),/INVALID/);
 const e=await selection(['s7']);e.hashes[e.ids[0]]='0'.repeat(32);await assert.rejects(rpc('papa_catalog_review_selected',['independent',e.ids,e.hashes,'president']),/STALE/);
 await rpc('papa_catalog_candidate_edit',[e.ids[0],(await selection(['s7'])).hashes[e.ids[0]],{title:'Edited',artist:'New',language:'華語',performerType:'男歌手',versionLabel:'Live'},'president']);
 assert.equal((await rpc('papa_catalog_review_page',['singles'])).rows[0].title,'Edited');
 assert.deepEqual((await q("select data from papa_v2_entities where kind='songs' order by id")).map(r=>r.data),originals.sort((a,b)=>a.songId.localeCompare(b.songId)));
 assert.ok((await q('select count(*)::int n from papa_catalog_negative_decisions'))[0].n>0);
 // A later re-scan must not re-group a pair explicitly judged independent.
 await q("update papa_catalog_candidates set status='pending' where song_id in ('s0','s2')");
 const negatives=await rpc('papa_catalog_review_page',['singles','Honey']);assert.ok(negatives.rows.some(r=>r.songId==='s2'));
 // A new version is a candidate under the stated family, never an automatic formal link.
 await q('insert into papa_v2_entities values($1,$2,$3)',['songs','s-new',{songId:'s-new',streamer_id:'papa',title:'A new label',artist:'Artist',cat:'華語',version:'Live',catalogCandidateFamily:a.familyId}]);
 const proposed=await q("select preferred_family,status from papa_catalog_candidates where song_id='s-new'");assert.equal(proposed[0].preferred_family,a.familyId);assert.equal(proposed[0].status,'pending');assert.equal((await q("select count(*)::int n from papa_catalog_song_links where song_id='s-new'"))[0].n,0);
 const newSource=(await q("select source_hash from papa_catalog_candidates where song_id='s-new'"))[0].source_hash;
 const priorSong=(await q("select data from papa_v2_entities where id='s-new'"))[0].data;
 await rpc('papa_catalog_link_room_song',['papa','s-new',a.variantId,newSource,null,'streamer:papa',false]);
 assert.equal((await q("select data from papa_v2_entities where id='s-new'"))[0].data.title,priorSong.title);
 assert.equal((await q("select variant_id from papa_catalog_song_links where song_id='s-new'"))[0].variant_id,a.variantId);
 assert.equal((await rpc('papa_catalog_link_info',['papa','s-new'])).status,'linked');
 assert.equal((await rpc('papa_catalog_song_metadata',['papa'])).find(r=>r.songId==='s-new').catalogStatus,'linked');
 const singers=await rpc('papa_catalog_family_singers',[a.familyId]);
 assert.equal(singers.find(v=>v.variantId===a.variantId).rooms.length,2);
 await assert.rejects(rpc('papa_catalog_link_room_song',['papa','s-new',b.variantId,newSource,null,'streamer:papa',false]),/STALE/);
 const exact=(await rpc('papa_catalog_families_page_v2',['Honey','all',20,0])).rows
  .flatMap(f=>f.variants).find(v=>v.variantId===a.variantId);
 assert.equal(exact.streamerCount,2,'two room songs from papa count as one streamer');
 const versionStamp=(await q('select updated_at from papa_catalog_variants where id=$1',[a.variantId]))[0].updated_at;
 await rpc('papa_catalog_update_variant_full',[a.variantId,{title:'Honey'},{versionKind:'cover',performerDetail:'雙人',versionNote:'現場版'},versionStamp,'president']);
 const detail=(await q('select version_kind,performer_detail,version_note from papa_catalog_variants where id=$1',[a.variantId]))[0];
 assert.deepEqual(detail,{version_kind:'cover',performer_detail:'雙人',version_note:'現場版'});
 const variantInfo=await rpc('papa_catalog_variant_info',[a.variantId]);
 assert.equal(variantInfo.performerDetail,'雙人');assert.equal(variantInfo.versionNote,'現場版');
 assert.ok(!Object.hasOwn(variantInfo,'body'));
 await assert.rejects(rpc('papa_catalog_update_variant_full',[a.variantId,{}, {versionKind:'old'},versionStamp,'president']),/STALE/);
 assert.ok((await rpc('papa_catalog_suggest_variants',[(await selection(['s0'])).ids[0],8])).some(r=>r.variantId),'review receives bounded fuzzy suggestions');
 const rooms=await rpc('papa_catalog_variant_rooms_v2',[a.variantId,20,0]);
 assert.equal(rooms.total,2);assert.equal(rooms.items.find(r=>r.streamerId==='papa').songs.length,2);
 await q("update papa_v2_entities set data=data||'{\"hidden\":true}'::jsonb where id='s-new'");
 const playerSearch=await rpc('papa_song_search_room_v2',['papa','Honey',[],20,0,null,false]);
 assert.equal(playerSearch.songIds.includes('s-new'),false);
 const managerSearch=await rpc('papa_song_search_room_v2',['papa','Honey',[],20,0,null,true]);
 assert.equal(managerSearch.songIds.includes('s-new'),true);
 const publicPage=await rpc('papa_catalog_public_page',['Honey',12,0]);
 const speakers=publicPage.rows.flatMap(f=>f.variants).find(v=>v.variantId===a.variantId).streamers;
 assert.equal(speakers.find(r=>r.streamerId==='papa').songId,'s0');
 const importMatches=await rpc('papa_catalog_import_matches',[[{line:1,title:'Honey',artist:'Artist',cat:'華語'}]]);
 assert.ok(importMatches[0].total>=1);assert.ok(importMatches[0].matches.every(r=>!Object.hasOwn(r,'lyrics')));
 await q('insert into papa_v2_entities values($1,$2,$3)',['songs','s-import',{songId:'s-import',streamer_id:'papa',title:'Honey',artist:'Artist',cat:'華語',tags:['own']}]);
 assert.equal((await rpc('papa_catalog_import_link_batch',['papa',[{songId:'s-import',variantId:a.variantId,title:'Honey',artist:'Artist'}],'streamer:papa'])).linked,1);
 assert.equal((await q("select variant_id from papa_catalog_song_links where song_id='s-import'"))[0].variant_id,a.variantId);
 const report=await rpc('papa_catalog_report_issue',['papa',a.familyId,a.variantId,'artist_name','歌手需核對','建議名稱']);
 assert.equal(report.status,'pending');assert.equal((await rpc('papa_catalog_issue_page',['papa','pending',10,0])).total,1);
 assert.equal((await rpc('papa_catalog_issue_set_status',[report.id,'fixed','president'])).status,'fixed');
 // Already linked variants are skipped atomically; one master update changes the projected view only.
 const beforeCount=(await q("select count(*)::int n from papa_v2_entities where kind='songs'"))[0].n;
 assert.equal((await rpc('papa_catalog_batch_add',['b',[a.variantId],'shared','streamer:b'])).added,0);assert.equal((await q("select count(*)::int n from papa_v2_entities where kind='songs'"))[0].n,beforeCount);
 await q('update papa_catalog_variants set title=$1 where id=$2',['Changed master',a.variantId]);assert.equal((await rpc('papa_catalog_song_metadata',['b'])).find(r=>r.songId==='s1').title,'Changed master');assert.equal((await q("select data->>'title' title from papa_v2_entities where id='s1'"))[0].title,'Honey');
 for(const [id,artist] of [['sx','Artist X'],['sy','Artist Y']])await q('insert into papa_v2_entities values($1,$2,$3)',['songs',id,{songId:id,streamer_id:'papa',title:'Version Test',artist,cat:'華語',privateNote:'keep'}]);
 const custom=await selection(['sx','sy']);
 const mapped=Object.fromEntries(custom.ids.map((id,i)=>[id,{artist:i?'Singer Y':'Singer X',language:'華語',performerType:'女歌手',versionLabel:i?'Live':'Original',versionKind:i?'live':'original',performerDetail:i?'duo':'solo',versionNote:i?'stage':'studio'}]));
 const reviewed=await rpc('papa_catalog_review_versions',[custom.ids,custom.hashes,'president',{title:'Version Test'},mapped,null]);
 const reviewedVariants=await q('select artist,version_kind,performer_detail,version_note from papa_catalog_variants where family_id=$1 order by artist',[reviewed.familyId]);
 assert.equal(reviewedVariants.length,2);assert.deepEqual(reviewedVariants.map(v=>v.version_kind),['original','live']);
 assert.equal((await q("select data->>'privateNote' note from papa_v2_entities where id='sx'"))[0].note,'keep');
 for(const id of ['sf1','sf2'])await q('insert into papa_v2_entities values($1,$2,$3)',['songs',id,{songId:id,streamer_id:'papa',title:'Full merge',artist:'Source',privateNote:'untouched',lyrics:'custom '+id}]);
 const fullSelection=await selection(['sf1','sf2']);
 const fullResult=await rpc('papa_catalog_review_same_full',[fullSelection.ids,fullSelection.hashes,'president',{title:'Full merge',artist:'Chosen'},{versionKind:'cover',performerDetail:'合唱',versionNote:'live'},fullSelection.ids[0],null]);
 assert.equal((await rpc('papa_catalog_variant_info',[fullResult.variantId])).performerDetail,'合唱');
 assert.equal((await rpc('papa_catalog_get_lyrics',[fullResult.variantId])).body,'custom sf1');
 assert.equal((await q("select data->>'lyrics' lyrics from papa_v2_entities where id='sf2'"))[0].lyrics,'custom sf2');
 await q('insert into papa_v2_entities values($1,$2,$3)',['songs','link-custom',{songId:'link-custom',streamer_id:'b',title:'Unlinked lyric',artist:'Artist',lyrics:'source custom',privateNote:'own note'}]);
 const unlinkedSource=(await q("select source_hash from papa_catalog_candidates where song_id='link-custom'"))[0].source_hash;
 await rpc('papa_catalog_link_room_song',['b','link-custom',a.variantId,unlinkedSource,null,'streamer:b',false]);
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'b','link-custom'])).body,'source custom');
 await rpc('papa_catalog_link_room_song',['b','link-custom',b.variantId,unlinkedSource,a.variantId,'streamer:b',false]);
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'b','link-custom'])).body,'source custom');
 {const businessBefore=await q('select kind,id,data from papa_v2_entities order by kind,id'),linksBefore=await q('select streamer_id,song_id,variant_id,source_hash from papa_catalog_song_links order by song_id');
 await db.exec(fs.readFileSync('supabase/migrations/202610080010_admin_catalog_controls.sql','utf8'));
 assert.deepEqual(await q('select kind,id,data from papa_v2_entities order by kind,id'),businessBefore);
 assert.deepEqual(await q('select streamer_id,song_id,variant_id,source_hash from papa_catalog_song_links order by song_id'),linksBefore);
 const cover=await rpc('papa_catalog_families_page_v3',['Full merge','all',1,0,'','cover','papa']);
 assert.equal(cover.total,1);assert.equal(cover.rows.length,1);assert.equal(cover.rows[0].variants[0].alreadyAdded,true);assert.equal(cover.rows[0].variants[0].versionKind,'cover');
 assert.ok(!JSON.stringify(cover).includes('custom sf1'));assert.ok(!JSON.stringify(cover).includes('privateNote'));assert.ok(cover.filters.versionKinds.includes('cover'));
 assert.equal((await rpc('papa_catalog_families_page_v3',['Full merge','all',1,0,'英語','cover','papa'])).total,0);
 assert.equal((await rpc('papa_catalog_families_page_v3',['Full merge','all',1,0,'','live','papa'])).total,0);
 const familyPage=await rpc('papa_catalog_families_page_v3',['','all',1,0,'','','b']);assert.equal(familyPage.rows.length,1);assert.ok(familyPage.hasMore);
 const second=await rpc('papa_catalog_families_page_v3',['','all',1,1,'','','b']);assert.notEqual(familyPage.rows[0].id,second.rows[0].id);
 await q("update papa_v2_entities set data=jsonb_set(data,'{streamers}',$1) where kind='meta' and id='1'",[[{id:'papa',display_name:'怕怕',active:true},{id:'b',display_name:'米雪',active:true},{id:'c',display_name:'咪醬',active:true},{id:'d',display_name:'停用',active:false}]]);
 const rooms=await rpc('papa_catalog_variant_rooms_v3',[a.variantId,1,0]);assert.equal(rooms.items.length,1);assert.ok(['怕怕','米雪','咪醬'].includes(rooms.items[0].streamerName));assert.ok(!JSON.stringify(rooms).includes('source custom'));
 const meta=await rpc('papa_catalog_song_metadata',['papa']);assert.ok(meta.some(row=>row.otherStreamerCount>0));assert.ok(meta.every(row=>Number.isInteger(row.otherStreamerCount)));assert.ok(!JSON.stringify(meta).includes('custom sf1'));
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(rpc('papa_catalog_families_page_v3'),/permission denied/);await assert.rejects(rpc('papa_catalog_variant_rooms_v3',[a.variantId]),/permission denied/);await assert.rejects(rpc('papa_catalog_review_page',['singles']),/permission denied/);await assert.rejects(q('select body from papa_catalog_custom_archives'),/permission denied/);await db.exec('reset role');}
 }
});
