import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {empty,mutate,scopeState,balance,usedHour,reservedHour,songPlays,matchesSong} from '../src/core.js';
import {deriveNotices} from '../src/notification-rules.js';
import {eventDescription,canonicalLanguage,catalogGroupKey} from '../src/catalog-tools.js';
test('V2 normalization preserves approved links, exact common uniqueness, local settings and one audit stream',async t=>{
 const db=new PGlite({extensions:{pg_trgm}});t.after(()=>db.close());
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table papa_v2_entities(kind text,id text,data jsonb,primary key(kind,id));
 create table papa_v2_revision(id int primary key,revision bigint);insert into papa_v2_revision values(1,10);
 create table papa_notice_config(id text primary key,value jsonb);
 create table papa_events(id bigint generated always as identity primary key,streamer_id text,entity_kind text,entity_id text,action text,actor_role text,actor_player_id text,created_at timestamptz default now(),effective_at text,before_data jsonb,after_data jsonb);
 create table papa_release_backups(release text primary key,snapshot jsonb);
 create function papa_v2_snapshot() returns jsonb language sql as $$ select jsonb_build_object('rows',(select jsonb_agg(to_jsonb(e)) from papa_v2_entities e)) $$;`);
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 const rpc=async(name,args=[])=>(await q('select '+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') value',args))[0].value;
 const original=['s1','s2','s3','s4'].map((id,i)=>({songId:id,streamer_id:i%2?'michelle':'papa',title:i===3?'另一首':'野心家',artist:'歌手',cat:'國語',artistType:'女歌手',tags:['私有'+i],key:'Key'+i,creditCost:i+1,lyrics:'私有歌詞'+i,privateNote:'私人'+i}));
 await q('insert into papa_v2_entities values($1,$2,$3)',['meta','1',{streamers:[{id:'papa',active:true},{id:'michelle',active:true}]}]);
 for(const s of original)await q('insert into papa_v2_entities values($1,$2,$3)',['songs',s.songId,s]);
 await q('insert into papa_v2_entities values($1,$2,$3)',['ledger','l1',{amount:25,playerId:'P1'}]);
 for(const file of fs.readdirSync('supabase/migrations').filter(f=>/^2026100100\d\d_/.test(f)).sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await rpc('papa_catalog_reconcile_songs',['',100]);
 const selection=async ids=>{const rows=await q('select id,source_hash from papa_catalog_candidates where song_id=any($1) order by song_id',[ids]);return {ids:rows.map(r=>r.id),hashes:Object.fromEntries(rows.map(r=>[r.id,r.source_hash]))};};
 let a=await selection(['s1']);const first=await rpc('papa_catalog_review',['approve_new',a.ids,null,null,'','president',a.hashes]);
 await q("insert into papa_catalog_languages(id,name) values('custom_mandarin','華語')");
 await q("insert into papa_catalog_language_filters(streamer_id,mode) values('papa','custom')");
 await q("insert into papa_catalog_language_filter_items values('papa','mandarin'),('papa','custom_mandarin')");
 await db.exec(fs.readFileSync('supabase/migrations/202610050001_catalog_usability.sql','utf8'));
 const normalized=await q("select data from papa_v2_entities where kind='songs' order by id");
 assert.deepEqual(normalized.map(r=>r.data),original.map(r=>({...r,cat:'華語'})));
 assert.deepEqual((await q("select data from papa_v2_entities where kind='ledger'"))[0].data,{amount:25,playerId:'P1'});
 assert.equal((await q("select status from papa_catalog_candidates where song_id='s1'"))[0].status,'approved');
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'papa','s1'])).body,'私有歌詞0');
 assert.equal((await q("select count(*)::int n from papa_catalog_language_filter_items where streamer_id='papa'"))[0].n,1);
 assert.equal((await q("select count(*)::int n from papa_catalog_languages where name='國語'"))[0].n,0);
 a=await selection(['s2','s3']);await rpc('papa_catalog_review_v2',['confirm_same',a.ids,null,null,'','president',a.hashes,{}]);
 assert.equal((await q('select count(*)::int n from papa_catalog_variants where active'))[0].n,1);
 assert.equal((await q('select count(*)::int n from papa_catalog_song_links where variant_id=$1',[first.variantId]))[0].n,3);
 assert.deepEqual((await q("select data from papa_v2_entities where kind='songs' order by id")).map(r=>r.data),original.map(r=>({...r,cat:'華語'})));
 const history=await rpc('papa_event_page_v2',['papa',0,true,'shared_catalog',2,0]);assert.equal(history.rows.length,2);assert.ok(history.hasMore);assert.ok(history.total>=4);
 const page2=await rpc('papa_event_page_v2',['papa',0,true,'shared_catalog',2,2]);assert.ok(!history.rows.some(r=>page2.rows.some(x=>x.id===r.id)));
 assert.ok(!JSON.stringify(history).includes('私有歌詞'));
 assert.equal((await rpc('papa_event_page_v2',['papa',0,false,null])).rows.some(r=>r.entity_kind==='shared_catalog'),false);
 const before=await q('select * from papa_catalog_song_links order by song_id');a=await selection(['s4']);a.hashes[a.ids[0]]='0'.repeat(32);
 await assert.rejects(rpc('papa_catalog_review_v2',['approve_new',a.ids,null,null,'','president',a.hashes,{}]),/STALE/);
 assert.deepEqual(await q('select * from papa_catalog_song_links order by song_id'),before);
 // Explicit different versions remain different. Existing duplicate versions only merge by manual decision.
 a=await selection(['s4']);const v=await rpc('papa_catalog_review',['create_variant',a.ids,null,first.familyId,'Live','president',a.hashes]);
 const versions=Object.fromEntries((await q('select id,updated_at from papa_catalog_variants')).map(r=>[r.id,r.updated_at]));
 const merged=await rpc('papa_catalog_merge_same_versions',[[first.variantId,v.variantId],first.variantId,versions,'president']);assert.equal(merged.links,1);
 assert.equal((await q('select count(*)::int n from papa_catalog_variants where active'))[0].n,1);
 assert.deepEqual((await q("select data from papa_v2_entities where kind='songs' order by id")).map(r=>r.data),original.map(r=>({...r,cat:'華語'})));
 assert.equal((await rpc('papa_catalog_get_lyrics',[null,'michelle','s4'])).body,'私有歌詞3');
 const inactive=await rpc('papa_catalog_inactive_search',['',20,0,'papa']);assert.equal(inactive.rows.length,1);assert.ok(!JSON.stringify(inactive).includes('lyrics'));
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);await assert.rejects(rpc('papa_catalog_review_v2',['approve_new',a.ids]),/permission denied/);await assert.rejects(rpc('papa_event_page_v2',['papa']),/permission denied/);await assert.rejects(rpc('papa_catalog_merge_same_versions',[[],null,{},'president']),/permission denied/);await db.exec('reset role');}
});
test('streamer random self queue never consumes player credit/quota/popularity or sends player notices',()=>{
 const now='2026-10-05T00:00:00Z',admin={role:'admin'};
 let s=mutate(empty(),{type:'song',data:{title:'自帶歌',artist:'歌手',creditCost:2}},admin,now);const id=s.songs[0].songId;
 const before=structuredClone(s);s=mutate(s,{type:'streamerDraw',data:{songId:id},streamer:'papa'},admin,now);
 const room=scopeState(s,'papa'),r=room.queue[0];assert.equal(r.kind,'self');assert.equal(r.playerId,null);assert.equal(r.selfProvided,true);assert.equal(reservedHour(room,now),0);assert.equal(usedHour(room,now),0);assert.deepEqual(s.ledger,[]);assert.deepEqual(deriveNotices(before,s,{streamer_id:'papa',role:'streamer_admin'}),[]);
 const added=structuredClone(s);s=mutate(s,{type:'queue',data:{id:r.id,operation:'complete'},streamer:'papa'},admin,now);
 assert.equal(songPlays(scopeState(s,'papa'),id),0);assert.deepEqual(s.ledger,[]);assert.deepEqual(deriveNotices(added,s,{streamer_id:'papa',role:'streamer_admin'}),[]);
 assert.throws(()=>mutate(before,{type:'streamerDraw',data:{songId:id},streamer:'papa'},{role:'player',playerId:'P1'},now),/登入管理/);
 assert.throws(()=>mutate(before,{type:'streamerDraw',data:{songId:id},streamer:'missing'},admin,now),/主播/);
 const hidden=structuredClone(before);hidden.songs[0].hidden=true;assert.throws(()=>mutate(hidden,{type:'streamerDraw',data:{songId:id}},admin,now),/可用/);
});
test('language aliases and history summaries are human readable without technical IDs',()=>{
 assert.equal(canonicalLanguage('國語'),'華語');assert.equal(catalogGroupKey({title:'Ａ Song！'}),catalogGroupKey({title:'a song'}));
 assert.ok(matchesSong({title:'作品',cat:'國語'},'華語'));assert.ok(matchesSong({title:'作品',cat:'華語'},'國語'));
 assert.equal(eventDescription({action:'request_failed',entity_kind:'request',actor_player_id:'P1',after_data:{songId:'S1'}},{playerName:()=> '森',songName:()=> '愛你'}),'森提歌《愛你》失敗：本小時提歌額度已滿');
 assert.match(eventDescription({entity_kind:'shared_catalog',actor_role:'president',action:'confirm_same',after_data:{titles:['野心家'],rooms:['papa','michelle']}},{roomName:id=>id==='papa'?'怕怕':'米雪'}),/PA Party總裁.*野心家.*怕怕、米雪/);
});
