import test from 'node:test';
import assert from 'node:assert/strict';
import {matchesSong} from '../src/core.js';
import {empty,mutate,balance,usedHour,stats,liveDay,addMonths,songPlays,publicView,previewImport,applyImport,migrateLegacy,crownFor} from '../src/core.js';
const admin={role:'admin'},t='2026-09-17T11:00:00Z';
test('single search covers language and artist with any selected tag',()=>{const song={title:'舞孃',artist:'蔡依林',cat:'華語',tags:['嗨歌'],lyrics:'月光'};assert.ok(matchesSong(song,'蔡依林 華語',['甜歌','嗨歌']));assert.ok(matchesSong(song,'月光'));assert.ok(!matchesSong(song,'台語'));assert.ok(!matchesSong(song,'蔡依林',['甜歌']));});
test('each queued song retains its own preparation time',()=>{let s=request(fixture());s=request(s);s=mutate(s,{type:'queue',data:{id:s.queue[0].id,operation:'stage',stage:'🎤 暖嗓中',preparationMinutes:8}},admin,t);s=mutate(s,{type:'queue',data:{id:s.queue[1].id,operation:'stage',stage:'⏳ 等待中',preparationMinutes:3}},admin,t);assert.equal(publicView(s,null,t).nowPlaying.preparationMinutes,8);s=queue(s,'complete');assert.equal(publicView(s,null,t).nowPlaying.preparationMinutes,3);assert.throws(()=>mutate(s,{type:'queue',data:{id:s.queue[1].id,operation:'stage',stage:'⏳ 等待中',preparationMinutes:-1}},admin,t));});
test('public now-playing follows first confirmed queue item without exposing player history',()=>{let s=fixture();s=request(s,'live');assert.equal(publicView(s,null,t).nowPlaying,null);s=queue(s,'approve');const v=publicView(s,null,t);assert.equal(v.nowPlaying.title,'舞孃');assert.equal(v.queue.length,0);assert.equal(v.nowPlaying.playerId,undefined);s=queue(s,'complete');assert.equal(publicView(s,null,t).nowPlaying,null);});
function fixture(){let s=empty();s=mutate(s,{type:'player',data:{name:'樂樂',ids:'123,456',balance:5,password:'abcd'}},admin,t);s=mutate(s,{type:'song',data:{title:'舞孃',artist:'蔡依林',tags:['嗨歌']}},admin,t);return s;}
const player=s=>({role:'player',playerId:s.players[0].playerId,loginId:'456'});
function request(s,kind='saved',at=t,p=player(s)){return mutate(s,{type:'request',data:{songId:s.songs[0].songId,kind,giftConfirmed:true}},p,at);}
function queue(s,operation,at=t){return mutate(s,{type:'queue',data:{id:s.queue[0].id,operation}},admin,at);}
test('all aliases spend the same ledger; completed only increments once',()=>{let s=fixture();s=request(s);assert.equal(balance(s,s.players[0].playerId),5);assert.equal(songPlays(s,s.songs[0].songId),0);s=queue(s,'complete');assert.equal(songPlays(s,s.songs[0].songId),1);assert.throws(()=>queue(s,'complete'));assert.equal(balance(s,s.players[0].playerId),4);});
test('cancel refunds once, does not inflate received deposits; permanent delete updates ledger',()=>{let s=request(fixture());s=queue(s,'cancel');assert.equal(balance(s,s.players[0].playerId),5);assert.equal(stats(s,t).saved,5);assert.throws(()=>queue(s,'cancel'));s=queue(s,'delete');assert.equal(s.queue.length,0);assert.equal(balance(s,s.players[0].playerId),5);});
test('live pending is not received or playable, approval then conversion',()=>{let s=request(fixture(),'live');assert.equal(stats(s,t).received,5);assert.throws(()=>queue(s,'complete'));s=queue(s,'approve');assert.equal(stats(s,t).received,6);assert.equal(songPlays(s,s.songs[0].songId),0);s=queue(s,'store');assert.equal(balance(s,s.players[0].playerId),6);assert.throws(()=>queue(s,'store'));});
test('Taipei hour boundary and 19:00 show boundary are independent',()=>{let s=request(fixture(),'saved','2026-09-17T10:59:59Z');assert.equal(usedHour(s,'2026-09-17T11:00:00Z'),0);assert.equal(liveDay('2026-09-17T10:59:59Z'),'2026-09-16');assert.equal(liveDay('2026-09-17T11:00:00Z'),'2026-09-17');assert.equal(liveDay('2026-09-17T19:00:00Z'),'2026-09-17');});
test('hourly limit, empty credit and pause block all request variants',()=>{let s=fixture();s=request(s);s=request(s);assert.throws(()=>request(s),/滿/);assert.doesNotThrow(()=>request(s,'live'));s=mutate(s,{type:'settings',data:{status:'暫停點歌'}},admin,t);assert.throws(()=>request(s,'saved'),/休息/);assert.throws(()=>request(s,'live'),/休息/);});
test('crown payment confirmation, owner rules, expiry and month clamping',()=>{let s=fixture(),p=player(s);s=mutate(s,{type:'crown',data:{playerId:p.playerId,songId:s.songs[0].songId,tier:'金卡'}},admin,t);assert.equal(crownFor(s,s.songs[0].songId,t),undefined);assert.throws(()=>mutate(s,{type:'crown',data:{...s.crowns[0],activate:true,singerPaid:true}},admin,t));s=mutate(s,{type:'crown',data:{...s.crowns[0],activate:true,singerPaid:true,bandPaid:true,hostPaid:true}},admin,t);assert.doesNotThrow(()=>request(s));s=mutate(s,{type:'player',data:{name:'其他人',balance:5}},admin,t);const other={role:'player',playerId:s.players[1].playerId};assert.throws(()=>request(s,'saved',t,other),/冠歌/);s=request(s,'live',t,other);assert.equal(s.queue[0].price,4200);assert.equal(crownFor(s,s.songs[0].songId,'2026-10-17T11:00:00Z'),undefined);assert.equal(addMonths('2026-01-31T14:00:00Z',1),'2026-02-28T14:00:00.000Z');});
test('public projection never exposes passwords, other histories or admin settings',()=>{const s=fixture(),v=publicView(s,null,t),own=publicView(s,player(s),t);assert.equal(v.players.length,0);assert.equal(v.ledger.length,0);assert.equal(own.players[0].password,undefined);assert.equal(JSON.stringify(v).includes('abcd'),false);assert.equal(own.players[0].hasPassword,true);});
test('import preview duplicate handling is atomic and handles intra-batch duplicates',()=>{let s=fixture();const rows=previewImport(s,'players','樂樂新名字｜123||||||');assert.equal(rows[0].match.playerId,s.players[0].playerId);const next=applyImport(s,'players',rows,['update'],admin,t);assert.equal(next.players.length,1);assert.equal(balance(next,next.players[0].playerId),5);const songs=previewImport(s,'songs','新歌｜歌手\n新歌｜歌手');assert.throws(()=>applyImport(s,'songs',songs,['add','add'],admin,t),/重複/);assert.equal(s.songs.length,1);});
test('tag deletion survives further edits; wishes link without merging requests',()=>{let s=fixture();s=mutate(s,{type:'tag',data:{tag:'嗨歌',remove:true}},admin,t);assert.ok(!s.songs[0].tags.includes('嗨歌'));assert.ok(!s.settings.tags.includes('嗨歌'));for(let i=0;i<2;i++)s=mutate(s,{type:'wish',data:{title:'新歌',artist:'歌手'}},player(s),t);assert.equal(s.wishes.length,2);s=mutate(s,{type:'wishAdmin',data:{id:s.wishes[0].id,status:'已學會',addSong:true}},admin,t);assert.ok(s.wishes[0].songId);});
test('legacy balance reconciliation preserves credits and unparseable time is not fabricated',()=>{const s=migrateLegacy({users:[{id:1,name:'樂樂',ids:['123','456'],credits:7,logs:[{amount:2,time:'未知'}]}],songs:[{id:1,title:'歌',artist:'人',plays:20}],queue:[],crowns:[]});assert.equal(balance(s,'P1'),7);assert.equal(s.ledger[0].at,null);assert.equal(stats(s,t).saved,0);assert.ok(s.migrationIssues.length);});
test('players cannot run admin commands',()=>{const s=fixture();for(const type of ['player','ledger','song','crown','card','settings','cleanup','queue'])assert.throws(()=>mutate(s,{type,data:{}},player(s),t),/管理/);});
test('self-provided songs retain history and credit debit but never count as player choices',()=>{let s=fixture();s=mutate(s,{type:'onBehalf',data:{playerId:s.players[0].playerId,songId:s.songs[0].songId,kind:'saved',selfProvided:true}},admin,t);assert.equal(balance(s,s.players[0].playerId),5);assert.equal(s.queue.length,1);assert.equal(usedHour(s,t),0);assert.equal(stats(s,t).received,5);s=queue(s,'complete');assert.equal(usedHour(s,t),1);assert.equal(balance(s,s.players[0].playerId),4);assert.equal(songPlays(s,s.songs[0].songId),0);assert.equal(stats(s,t).sung,1);assert.equal(s.queue[0].status,'completed');});

test('bulk editing adds tags to only selected songs, preserves identities/history and supports removal',()=>{
 let s=fixture();s=mutate(s,{type:'song',data:{title:'新歌',artist:'歌手',tags:['甜歌'],murmur:'原本的碎碎念'}},admin,t);s=mutate(s,{type:'song',data:{title:'未選取',artist:'歌手',tags:[]}},admin,t);s=request(s);s=queue(s,'complete');
 const ids=s.songs.slice(0,2).map(x=>x.songId),original=structuredClone(s);
 s=mutate(s,{type:'songsBulk',data:{songIds:ids,tagMode:'add',tags:['動感','動感'],cat:'韓語',new:true}},admin,t);
 assert.deepEqual(s.songs[0].tags,['嗨歌','動感']);assert.deepEqual(s.songs[1].tags,['甜歌','動感']);assert.equal(s.songs[1].murmur,'原本的碎碎念');assert.deepEqual(s.songs[2],original.songs[2]);assert.equal(songPlays(s,ids[0]),1);assert.deepEqual(s.queue,original.queue);assert.deepEqual(s.ledger,original.ledger);assert.deepEqual(s.songs.map(x=>x.songId),original.songs.map(x=>x.songId));
 s=mutate(s,{type:'songsBulk',data:{songIds:ids,tagMode:'remove',tags:['動感']}},admin,t);assert.deepEqual(s.songs[0].tags,['嗨歌']);assert.deepEqual(s.songs[1].tags,['甜歌']);
 s=mutate(s,{type:'songsBulk',data:{songIds:ids,tagMode:'replace',tags:['抒情'],new:false,murmur:'統一文字'}},admin,t);assert.deepEqual(s.songs[1].tags,['抒情']);assert.equal(s.songs[1].new,false);
 s=mutate(s,{type:'songsBulk',data:{songIds:ids,tagMode:'clear',murmur:''}},admin,t);assert.deepEqual(s.songs[0].tags,[]);assert.equal(s.songs[1].murmur,'');
});
test('invalid bulk batches are atomic and admin-only',()=>{
 const s=fixture(),before=structuredClone(s),id=s.songs[0].songId;
 for(const data of [{songIds:[id,'missing'],cat:'韓語'},{songIds:[id],cat:'錯誤'},{songIds:[id],tagMode:'replace',tags:[]},{songIds:[id],new:'false'},{songIds:[]},{songIds:[id]}])assert.throws(()=>mutate(s,{type:'songsBulk',data},admin,t));
 assert.throws(()=>mutate(s,{type:'songsBulk',data:{songIds:[id],cat:'台語'}},player(s),t),/管理/);assert.deepEqual(s,before);
});
test('bulk undo restores metadata without erasing newer edits or play records',()=>{
 const fields=x=>({songId:x.songId,cat:x.cat,artistType:x.artistType,tags:x.tags,new:x.new,murmur:x.murmur,creditCost:x.creditCost});
 let s=fixture(),before=s.songs.map(fields),id=s.songs[0].songId;
 s=mutate(s,{type:'songsBulk',data:{songIds:[id],tagMode:'add',tags:['甜歌'],cat:'台語'}},admin,t);const after=s.songs.map(fields);s=request(s);s=queue(s,'complete');const reverted=mutate(s,{type:'restoreSongEdits',data:{before,after}},admin,t);assert.deepEqual(reverted.songs.map(fields),before);assert.equal(songPlays(reverted,id),1);
 s=mutate(s,{type:'songsBulk',data:{songIds:[id],murmur:'更新的內容'}},admin,t);assert.throws(()=>mutate(s,{type:'restoreSongEdits',data:{before,after}},admin,t),/其他修改/);
});

test('legacy crowns stay visible with original titles without fabricating bindings or activation dates',()=>{
 const s=migrateLegacy({songs:[],users:[],queue:[],crowns:[{id:1,title:'三心愛意',artist:'不不玩家',crownedBy:'不不玩家',type:'至尊冠歌',expires:'永久',crownedAt:'未知'}]});
 const view=publicView(s,null,t);assert.equal(view.crowns.length,1);assert.equal(view.crowns[0].title,'三心愛意');assert.equal(view.crowns[0].ownerName,'不不玩家');assert.equal(view.crowns[0].activatedAt,null);assert.equal(view.crowns[0].songId,null);assert.equal(crownFor(s,null,t),undefined);
});
