import test from 'node:test';
import assert from 'node:assert/strict';
import {empty,mutate,scopeState,publicView,balance,stats,usedHour,reservedCredits,upgradePlatform,songPlays,searchAcrossStreamers,previewImport,applyImport} from '../src/core.js';
const admin={role:'admin'},t='2026-09-18T12:00:00Z';
function setup(){let s=mutate(empty(),{type:'player',data:{name:'玩家',ids:['a','b'],balance:5}},admin,t);s=mutate(s,{type:'song',data:{title:'短歌',artist:'甲',creditCost:0.5}},admin,t);return s;}
const player=s=>({role:'player',playerId:s.players[0].playerId});
const run=(s,type,data,streamer='papa',who=admin)=>mutate(s,{type,data,streamer},who,t);
test('half song twice reserves one credit and charges only once at completion',()=>{let s=setup(),id=s.songs[0].songId,p=player(s);s=run(s,'request',{songId:id,kind:'saved'},'papa',p);assert.equal(balance(s,p.playerId),5);assert.equal(reservedCredits(s,p.playerId),1);assert.equal(s.queue[0].items[0].performances,2);const q=s.queue[0].id;s=run(s,'queue',{id:q,operation:'complete'});assert.equal(balance(s,p.playerId),4);assert.equal(songPlays(s,id),2);assert.equal(stats(s,t).sung,2);assert.equal(usedHour(s,t),1);assert.throws(()=>run(s,'queue',{id:q,operation:'complete'}));});
test('allowed half-song pairing snapshots both songs and charges one credit',()=>{let s=setup();s=run(s,'song',{title:'短歌二',artist:'乙',creditCost:0.5});const [a,b]=s.songs;s=run(s,'song',{...a,shortMode:'pair',pairSongIds:[b.songId]});assert.throws(()=>run(s,'request',{songId:a.songId,kind:'saved'},'papa',player(s)));s=run(s,'request',{songId:a.songId,pairSongId:b.songId,kind:'saved'},'papa',player(s));assert.equal(s.queue[0].items.length,2);s=run(s,'song',{...b,creditCost:2});s=run(s,'queue',{id:s.queue[0].id,operation:'complete'});assert.equal(balance(s,s.players[0].playerId),4);assert.equal(songPlays(s,a.songId),1);assert.equal(songPlays(s,b.songId),1);});
test('long-song reservations prevent overspending and cancel releases without refund ledger',()=>{let s=setup();s=run(s,'song',{...s.songs[0],creditCost:3});s=run(s,'request',{songId:s.songs[0].songId,kind:'saved'},'papa',player(s));assert.throws(()=>run(s,'request',{songId:s.songs[0].songId,kind:'saved'},'papa',player(s)));const before=s.ledger.length;s=run(s,'queue',{id:s.queue[0].id,operation:'cancel'});assert.equal(s.ledger.length,before);assert.equal(reservedCredits(s,s.players[0].playerId),0);});
test('rooms share players but isolate songs, balance, queue, imports and forged IDs',()=>{let s=setup();s=run(s,'streamer',{slug:'second',display_name:'第二位'});const original=s.songs[0],p=player(s);let r=scopeState(s,'second');assert.equal(r.players.length,1);assert.equal(r.songs.length,0);assert.equal(balance(r,p.playerId),0);s=run(s,'song',{title:original.title,artist:original.artist},'second');s=run(s,'ledger',{playerId:p.playerId,amount:2},'second');assert.equal(balance(scopeState(s,'papa'),p.playerId),5);assert.equal(balance(scopeState(s,'second'),p.playerId),2);assert.throws(()=>run(s,'song',{...original,title:'越界'},'second'));assert.throws(()=>run(s,'request',{songId:original.songId,kind:'saved'},'second',p));const second=scopeState(s,'second').songs[0];s=run(s,'request',{songId:second.songId,kind:'saved'},'second',p);assert.equal(scopeState(s,'papa').queue.length,0);assert.equal(publicView(s,p,t,'papa').queue.length,0);assert.throws(()=>run(s,'queueBulkDelete',{ids:[s.queue[0].id]},'papa'));const rows=previewImport(scopeState(s,'second'),'songs','新增｜歌手');s=applyImport(s,'songs',rows,['add'],admin,t,'second');assert.equal(scopeState(s,'second').songs.length,2);assert.equal(scopeState(s,'papa').songs.length,1);assert.equal(searchAcrossStreamers(s,'短歌').length,2);});
test('V2 upgrade preserves metadata and records with one-time prepayment reconciliation',()=>{const s=empty();s.players=[{playerId:'p',ids:[],names:[],name:'原玩家'}];s.songs=[{songId:'s',title:'已改歌名',artist:'已改歌手',tags:['自訂'],cat:'台語'}];s.queue=[{id:'q',playerId:'p',songId:'s',kind:'saved',status:'waiting'}];s.ledger=[{id:'l',playerId:'p',amount:5},{id:'d',playerId:'p',queueId:'q',amount:-1}];const upgraded=upgradePlatform(s);assert.equal(balance(upgraded,'p'),5);assert.deepEqual(upgraded.songs[0].tags,['自訂']);assert.equal(upgraded.songs[0].title,'已改歌名');assert.equal(upgradePlatform(upgraded).ledger.length,3);assert.equal(s.ledger.length,2);});
test('test accounts exercise completion and quotas without formal statistics',()=>{let s=setup();s=run(s,'player',{...s.players[0],test:true});s=run(s,'request',{songId:s.songs[0].songId,kind:'saved',selfProvided:true},'papa',player(s));s=run(s,'queue',{id:s.queue[0].id,operation:'complete'});assert.equal(usedHour(s,t),1);assert.equal(stats(s,t).sung,0);assert.equal(balance(s,s.players[0].playerId),4);assert.equal(songPlays(s,s.songs[0].songId),0);});
