import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('policy and feature skeleton remains service-only and Space scoped',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table papa_v2_entities(kind text,id text,data jsonb,primary key(kind,id));
 insert into papa_v2_entities values('meta','1','{"streamers":[{"id":"papa"}]}');`);
 await db.exec(fs.readFileSync('supabase/migrations/202610070001_space_foundation.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610070008_policy_feature_entitlement.sql','utf8'));
 await q("insert into papa_spaces(id,slug,display_name) values('space-002','other','Other')");
 const member=(await q('insert into papa_accounts default values returning id'))[0].id;
 const stranger=(await q('insert into papa_accounts default values returning id'))[0].id;
 const president=(await q('insert into papa_accounts default values returning id'))[0].id;
 await q("insert into papa_space_memberships(account_id,space_id,role) values($1,'space-001','player')",[member]);
 await q("insert into papa_platform_roles(account_id,role) values($1,'president')",[president]);
 await q("insert into papa_feature_registry(feature_key,target_kind) values('room_theme','space'),('player_plus','account')");
 await assert.rejects(q("insert into papa_space_entitlements(space_id,feature_key,enabled) values('space-001','player_plus',true)"),/FEATURE_TARGET_MISMATCH/);
 await assert.rejects(q("insert into papa_account_entitlements(account_id,feature_key,enabled) values($1,'room_theme',true)",[member]),/FEATURE_TARGET_MISMATCH/);
 await assert.rejects(q("update papa_feature_registry set target_kind='account' where feature_key='room_theme'"),/FEATURE_TARGET_IMMUTABLE/);
 await q("insert into papa_space_entitlements(space_id,feature_key,enabled) values('space-001','room_theme',true),('space-002','room_theme',false)");
 await q("insert into papa_account_entitlements(account_id,feature_key,enabled) values($1,'player_plus',true)",[member]);
 await q("insert into papa_space_policies(space_id,policy_key,value) values('space-001','request_limit','{\"perHour\":2}'),('space-002','request_limit','{\"perHour\":3}')");
 const snapshot=async(account,space)=>(await q('select papa_policy_feature_snapshot($1,$2) result',[account,space]))[0].result;
 const own=await snapshot(member,'space-001');
 assert.equal(own.spaceId,'space-001');
 assert.equal(own.features.room_theme.enabled,true);
 assert.equal(own.accountFeatures.player_plus.enabled,true);
 assert.equal(own.policies.request_limit.value.perHour,2);
 assert.equal(await snapshot(member,'space-002'),null);
 assert.equal(await snapshot(stranger,'space-001'),null);
 assert.equal((await snapshot(president,'space-002')).policies.request_limit.value.perHour,3);
 await q("update papa_space_memberships set status='suspended' where account_id=$1",[member]);
 assert.equal(await snapshot(member,'space-001'),null);
 await db.exec('set role anon');
 await assert.rejects(snapshot(president,'space-001'),/permission denied/);
 await assert.rejects(q('select * from papa_space_policies'),/permission denied/);
 await db.exec('reset role');
});
