import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';

test('public classification filters paginate families in SQL and expose no private or hidden data',async t=>{
 const db=new PGlite({extensions:{pg_trgm}});t.after(()=>db.close());
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 const one=async(sql,args=[])=>(await q(sql,args))[0];
 const call=async(query='',language='',performer='',version='',limit=12,offset=0)=>(await one('select papa_catalog_public_page_filtered($1,$2,$3,$4,$5,$6) result',[query,language,performer,version,limit,offset])).result;
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table papa_v2_entities(kind text,id text,data jsonb,primary key(kind,id));
 create table papa_v2_revision(id int primary key,revision bigint);insert into papa_v2_revision values(1,10);
 create table papa_notice_config(id text primary key,value jsonb);
 create table papa_events(id bigint primary key,streamer_id text,entity_kind text,entity_id text,action text,actor_role text,actor_player_id text,created_at timestamptz,effective_at text,before_data jsonb,after_data jsonb);`);
 for(const file of fs.readdirSync('supabase/migrations').filter(f=>/^2026100100\d\d_/.test(f)).sort())await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 const integrated=fs.readFileSync('supabase/migrations/202610080001_catalog_integrated.sql','utf8');
 await db.exec("alter table papa_catalog_variants add column version_kind text not null default 'original'");
 const start=integrated.indexOf('create function papa_catalog_public_page(');
 await db.exec(integrated.slice(start,integrated.indexOf('\nrevoke all',start)));
 const rooms=[{id:'papa',slug:'papa',display_name:'怕怕',active:true},{id:'michelle',slug:'michelle',display_name:'米雪',active:true},{id:'disabled',slug:'disabled',display_name:'停用',active:false}];
 await q("insert into papa_v2_entities values('meta','1',$1)",[{streamers:rooms,privateSetting:'secret room'}]);
 const familyA=(await one("insert into papa_catalog_families(title) values('Honey A') returning id")).id;
 const familyB=(await one("insert into papa_catalog_families(title) values('Honey B') returning id")).id;
 const add=async(id,family,room,language,performer,kind,hidden=false,stale=false)=>{
  const v=(await one('insert into papa_catalog_variants(family_id,title,artist,language_text,performer_type_text,version_kind) values($1,$2,$3,$4,$5,$6) returning id',[family,'Honey','Artist '+id,language,performer,kind])).id;
  const data={songId:id,streamer_id:room,title:'Honey',artist:'Artist '+id,lyrics:'secret lyric '+id,privateNote:'secret note',tags:['private tag'],hidden};
  await q("insert into papa_v2_entities values('songs',$1,$2)",[id,data]);
  await q('insert into papa_catalog_song_links(streamer_id,song_id,variant_id,source_hash) values($1,$2,$3,papa_catalog_source_hash($4))',[room,id,v,{...data,...(stale?{title:'Old title'}:{})}]);return v;
 };
 const original=await add('s1',familyA,'papa','國語','女歌手','original');
 const cover=await add('s2',familyA,'michelle','英語','團體','cover');
 await add('s3',familyB,'papa','英語','男女合唱','original');
 await add('s4',familyA,'disabled','private language','secret performer','live');
 await add('s5',familyA,'papa','private language','secret performer','live',true);
 await add('s6',familyA,'papa','private language','secret performer','live',false,true);
 const before=await q('select kind,id,data from papa_v2_entities order by kind,id');
 await db.exec(fs.readFileSync('supabase/migrations/202610080009_public_catalog_filters.sql','utf8'));
 assert.deepEqual(await q('select kind,id,data from papa_v2_entities order by kind,id'),before);
 const all=await call();assert.equal(all.total,2);assert.equal(all.rows[0].variants.length,2);
 assert.deepEqual(all.filters.languages,['國語','英語']);assert.deepEqual(all.filters.versionKinds,['cover','original']);
 assert.equal((await call('','英語')).total,2);
 const translated=await call('Honey','英語','團體','cover');assert.equal(translated.total,1);assert.equal(translated.rows[0].variants.length,1);assert.equal(translated.rows[0].variants[0].variantId,cover);assert.equal(translated.rows[0].variants[0].streamers[0].slug,'michelle');
 assert.equal((await call('','國語')).rows[0].variants[0].variantId,original);
 assert.equal((await call('','','團體','original')).total,0);
 const first=await call('','','','',1,0),second=await call('','','','',1,1);assert.equal(first.hasMore,true);assert.equal(second.hasMore,false);assert.notEqual(first.rows[0].familyId,second.rows[0].familyId);
 assert.equal(/secret|lyrics|private/.test(JSON.stringify(all)),false);
 const old=(await one("select papa_catalog_public_page('',12,0) result")).result;assert.equal(old.total,all.total,'old clients keep their original RPC');
 await assert.rejects(call('','','','',21),/CATALOG_PAGE_LIMIT/);
 await db.exec('set role anon');await assert.rejects(call(),/permission denied/);await db.exec('reset role');
});
