import test from 'node:test';
import assert from 'node:assert/strict';
import {empty,mutate,balance,stats,usedHour,reservedCredits,scopeState,publicView} from '../src/core.js';
const admin={role:'admin'},now='2026-09-24T15:05:00Z',past='2026-09-24T14:58:00Z';
const run=(s,type,data,actor=admin,t=now,streamer='papa')=>mutate(s,{type,data,streamer},actor,t);
function setup(){let s=run(empty(),'player',{name:'測試',ids:['test'],balance:5});s=run(s,'song',{title:'歌曲',artist:'歌手'});return s;}
const player=s=>({role:'player',playerId:s.players[0].playerId});
const req=s=>({songId:s.songs[0].songId,kind:'saved'});
test('opening balance remains usable but is excluded from daily received',()=>{let s=setup();assert.equal(balance(s,s.players[0].playerId),5);assert.equal(stats(s,now).received,0);s=run(s,'ledger',{playerId:s.players[0].playerId,amount:3,at:now});assert.equal(stats(s,now).received,3);assert.equal(balance(s,s.players[0].playerId),8);});
test('player cancellation retains row and releases credits; rejects other player, completed and other room',()=>{let s=setup();s=run(s,'request',req(s),player(s));const id=s.queue[0].id;s=run(s,'player',{name:'其他',ids:['other']});assert.throws(()=>run(s,'cancelOwn',{id}, {role:'player',playerId:s.players[1].playerId}));s=run(s,'streamer',{slug:'second',display_name:'第二位'});assert.throws(()=>run(s,'cancelOwn',{id},player(s),now,'second'));s=run(s,'cancelOwn',{id},player(s));assert.equal(s.queue.length,1);assert.equal(s.queue[0].status,'cancelled');assert.equal(reservedCredits(s,s.players[0].playerId),0);assert.equal(balance(s,s.players[0].playerId),5);assert.throws(()=>run(s,'cancelOwn',{id},player(s)));});
test('backfilled completion and later time edits update hours and debit date, not registration date',()=>{let s=setup();s=run(s,'onBehalf',{...req(s),playerId:s.players[0].playerId,at:past,completed:true,note:'補登'});let q=s.queue[0];assert.equal(q.created_at,now);assert.equal(q.effective_at,new Date(past).toISOString());assert.equal(usedHour(s,now),0);assert.equal(usedHour(s,past),1);assert.equal(balance(s,q.playerId),4);s=run(s,'recordTime',{table:'queue',id:q.id,times:{completedAt:now},note:'時間修正'});q=s.queue[0];assert.equal(q.created_at,now);assert.equal(usedHour(s,now),1);assert.equal(s.ledger.find(l=>l.queueId===q.id).at,new Date(now).toISOString());assert.equal(q.note,'時間修正');assert.throws(()=>run(s,'recordTime',{table:'queue',id:q.id,times:{created_at:past}}));assert.throws(()=>run(s,'recordTime',{table:'queue',id:q.id,times:{at:past}},player(s)));});
test('pending backfill later completed still belongs to its recorded hour',()=>{let s=setup();s=run(s,'onBehalf',{...req(s),playerId:s.players[0].playerId,at:past});s=run(s,'queue',{id:s.queue[0].id,operation:'complete'});assert.equal(usedHour(s,now),0);assert.equal(usedHour(s,past),1);assert.throws(()=>run(s,'queue',{id:s.queue[0].id,operation:'complete'}));});
test('allocation of three into one live and two saved counts exactly three, completion only once',()=>{let s=setup();s=run(s,'allocate',{playerId:s.players[0].playerId,total:3,stored:2,effective_at:past,items:[{songId:s.songs[0].songId,completed:true}]});assert.equal(stats(s,now).received,3);assert.equal(stats(s,now).sung,1);assert.equal(balance(s,s.players[0].playerId),7);assert.equal(s.queue[0].status,'completed');assert.equal(s.queue[0].created_at,now);assert.equal(usedHour(s,now),0);assert.throws(()=>run(s,'allocate',{playerId:s.players[0].playerId,total:3,stored:3,items:[{songId:s.songs[0].songId}]}));});
test('existing deposit can split without double counting, cannot use another room deposit',()=>{let s=setup();s=run(s,'ledger',{playerId:s.players[0].playerId,amount:3,at:past});const l=s.ledger.at(-1),data={ledgerId:l.id,playerId:l.playerId,total:3,stored:2,effective_at:past,items:[{songId:s.songs[0].songId}]};s=run(s,'allocate',data);assert.equal(stats(s,now).received,3);assert.equal(balance(s,l.playerId),7);assert.equal(s.ledger.find(x=>x.id===l.id).amount,2);assert.throws(()=>run(s,'allocate',data));s=run(s,'streamer',{slug:'second',display_name:'第二位'});assert.throws(()=>run(s,'allocate',data,admin,now,'second'));assert.equal(balance(scopeState(s,'second'),l.playerId),0);});
test('invalid future times and malformed input are rejected atomically',()=>{const s=setup(),before=JSON.stringify(s);for(const at of ['garbage','2099-01-01T00:00:00Z'])assert.throws(()=>run(s,'onBehalf',{...req(s),playerId:s.players[0].playerId,at}));assert.equal(JSON.stringify(s),before);});
test('historical registration time is left unknown; unrelated records remain identical',()=>{let s=setup();delete s.ledger[0].created_at;const before=structuredClone(s);s=run(s,'ledger',{...s.ledger[0],at:past,note:'歷史核對'});assert.equal(s.ledger[0].created_at,null);assert.deepEqual(s.songs,before.songs);assert.deepEqual(s.players,before.players);assert.equal(publicView(s,null,now).ledger.length,0);});
