import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pg_trgm} from '@electric-sql/pglite/contrib/pg_trgm';
import {empty,mutate,TABLES} from '../src/core.js';
import {stateEntries,stateChanges} from '../src/state-patch.js';

test('room admin patches retain private source fields, other rooms and the real audit/notice transaction',async t=>{
 const db=new PGlite({extensions:{pg_trgm}});t.after(()=>db.close());
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 await db.exec('create role anon;create role authenticated;create role service_role;');
 const base=fs.readFileSync('supabase/migrations/202609170001_party_v2.sql','utf8');
 await db.exec(base.slice(0,base.indexOf('insert into storage.buckets')));
 await db.exec(fs.readFileSync('supabase/migrations/202609240001_release_a.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202609240003_notifications.sql','utf8'));
 const at='2026-10-08T04:00:00Z';let full=mutate(empty(),{type:'song',data:{title:'A',artist:'Artist',lyrics:'private-body-A',tags:['甜歌']}},{role:'admin'},at);
 full.songs[0].privateNotes='private-notes-A';const first=full.songs[0].songId;
 full=mutate(full,{type:'streamer',data:{slug:'michelle',display_name:'米雪'}},{role:'admin'},at);
 const other=full.streamers.find(r=>r.slug==='michelle').id;
 full=mutate(full,{streamer:other,type:'song',data:{title:'B',artist:'Artist',lyrics:'private-body-B'}},{role:'admin'},at);
 full.players=[{playerId:'P1',name:'Player',password:'preserved',ids:[],names:[],note:'private-profile'}];
 full.wishes=[{id:'W1',streamer_id:'papa',title:'Learned song',artist:'Wish artist',status:'收到',playerId:'P1'}];
 for(const row of stateEntries(full))await q('insert into papa_v2_entities values($1,$2,$3)',[row.kind,row.id,row.data]);
 for(const file of fs.readdirSync('supabase/migrations').filter(f=>/^2026100100\d\d_/.test(f)||/^20261005000[123]_/.test(f)||/^20261008000[1-8]_/.test(f)).sort())
  await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
 await q("select papa_catalog_reconcile_songs('',100)");
 const candidate=(await q('select id,source_hash from papa_catalog_candidates where song_id=$1',[first]))[0];
 await q("select papa_catalog_review_selected('independent',$1,$2,'president')",[[candidate.id],{[candidate.id]:candidate.source_hash}]);
 const linkedBefore=(await q('select variant_id from papa_catalog_song_links where song_id=$1',[first]))[0].variant_id;
 await db.exec(fs.readFileSync('supabase/migrations/202610070001_space_foundation.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610070009_scoped_read_snapshot.sql','utf8'));
 const directory=fs.readFileSync('supabase/migrations/202610070012_catalog_space_relations.sql','utf8');
 await db.exec(directory.slice(directory.indexOf('create or replace function public.papa_streamer_directory'),directory.indexOf('$$;')+3));
 await db.exec(fs.readFileSync('supabase/migrations/202610070013_space_player_profiles.sql','utf8'));
 await db.exec(fs.readFileSync('supabase/migrations/202610070015_room_admin_commit.sql','utf8'));
 const read=async(room,ids=[])=>{
  const result=(await q('select papa_v2_room_write_snapshot($1,$2) result',[room,ids]))[0].result;
  const state=empty();state.revision=result.revision;
  for(const r of result.rows)if(r.kind==='meta')Object.assign(state,r.data);else if(r.kind==='settings')state.settings=r.data;else if(TABLES.includes(r.kind))state[r.kind].push(r.data);
  return state;
 };
 const context=room=>({role:'streamer_admin',actor_streamer_id:room,streamer_id:room,space_id:'space-001',action:'songsBulk'});
 const commit=async(before,after,room='papa',ctx=context(room),notices=[])=>{
  const patch=stateChanges(before,after,{preserveOrder:true});
  return q('select papa_room_admin_commit($1,$2,$3,$4,$5,$6) result',[before.revision,patch.changes,patch.removed,ctx,notices,room]);
 };
 const otherBefore=(await q("select data from papa_v2_entities where kind='songs' and data->>'streamer_id'=$1",[other]))[0].data;
 let before=await read('papa');
 assert.equal(JSON.stringify(before).includes('private-body'),false);
 let after=mutate(before,{type:'songsBulk',data:{songIds:[first],tags:['New tag'],tagMode:'add'}},{role:'admin'},at);
 await commit(before,after);
 let song=(await q("select data from papa_v2_entities where kind='songs' and id=$1",[first]))[0].data;
 assert.equal(song.lyrics,'private-body-A');assert.equal(song.privateNotes,'private-notes-A');assert.ok(song.tags.includes('New tag'));
 assert.equal((await q('select variant_id from papa_catalog_song_links where song_id=$1',[first]))[0].variant_id,linkedBefore,'local tags do not disturb the approved shared relation');
 assert.deepEqual((await q("select data from papa_v2_entities where kind='songs' and data->>'streamer_id'=$1",[other]))[0].data,otherBefore);
 before=await read('papa',[first]);assert.equal(before.songs[0].lyrics,'private-body-A');assert.equal(JSON.stringify(before).includes('private-body-B'),false);
 after=mutate(before,{type:'song',data:{...before.songs[0],title:'A edited'}},{role:'admin'},at);
 await commit(before,after);
 assert.equal((await q("select data->>'lyrics' body from papa_v2_entities where id=$1",[first]))[0].body,'private-body-A');
 before=await read('papa');after=mutate(before,{type:'wishAdmin',data:{id:'W1',status:'已學會',addSong:true}},{role:'admin'},at);
 await commit(before,after);
 assert.equal((await q("select count(*)::int n from papa_v2_entities where kind='songs' and data->>'title'='Learned song'"))[0].n,1);
 const originalSettings=(await q("select data from papa_v2_entities where kind='settings'"))[0].data;
 before=await read(other);after=mutate(before,{streamer:other,type:'settings',data:{status:'忙碌中'}},{role:'admin'},at);await commit(before,after,other);
 const meta=(await q("select data from papa_v2_entities where kind='meta'"))[0].data;
 assert.equal(meta.streamerSettings[other].status,'忙碌中');assert.equal(meta.streamerSettings.papa.status,'空閒中');
 assert.deepEqual((await q("select data from papa_v2_entities where kind='settings'"))[0].data,originalSettings);
 before=await read('papa');after=mutate(before,{type:'self',data:{name:'Updated player'}},{role:'player',playerId:'P1'},at);
 await commit(before,after,'papa',{role:'player',player_id:'P1',streamer_id:'papa',space_id:'space-001',action:'self'});
 assert.equal((await q("select data->>'password' pwd from papa_v2_entities where kind='players'"))[0].pwd,'preserved');
 before=await read('papa');after=mutate(before,{type:'songsBulk',data:{songIds:[first],new:true}},{role:'admin'},at);
 const stable=await q('select kind,id,data from papa_v2_entities order by kind,id');
 await assert.rejects(commit(before,after,'papa',context('papa'),[{id:'invalid-uuid',streamer_id:'papa'}]),/uuid/);
 assert.deepEqual(await q('select kind,id,data from papa_v2_entities order by kind,id'),stable);
 await assert.rejects(q('select papa_v2_room_write_snapshot($1,$2)',['papa',[otherBefore.songId]]),/SCOPE_INVALID/);
 const patch=stateChanges(before,after,{preserveOrder:true});patch.changes[0].data.streamer_id=other;
 await assert.rejects(q('select papa_room_admin_commit($1,$2,$3,$4,$5,$6)',[before.revision,patch.changes,[],context('papa'),[],'papa']),/SCOPE_INVALID/);
 assert.ok((await q("select count(*)::int n from papa_events where action='songsBulk'"))[0].n>0);
 await db.exec('set role anon');await assert.rejects(read('papa'),/permission denied/);await db.exec('reset role');
});
