import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';

test('durable Web Push survives short access expiry, respects room/membership, and revokes only matching device routes',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table papa_v2_entities(kind text,id text,data jsonb,primary key(kind,id));
 create table papa_v2_sessions(token_hash text primary key,player_id text,login_id text,role text,streamer_id text,expires_at timestamptz);
 create table papa_streamer_accounts(streamer_id text primary key,password_hash text,enabled boolean);
 create table papa_president_accounts(account_key text primary key,password_hash text);
 create table papa_push_subscriptions(id uuid primary key default gen_random_uuid(),streamer_id text,recipient text,endpoint text,session_hash text);
 create table papa_push_jobs(id int primary key,subscription_id uuid references papa_push_subscriptions(id) on delete cascade);
 create table papa_notifications(id int primary key,body text);
 insert into papa_v2_entities values('meta','1','{"streamers":[{"id":"papa"},{"id":"michelle"}]}'),('players','P1','{"playerId":"P1"}');
 insert into papa_streamer_accounts values('papa','old',true);
 insert into papa_push_subscriptions(streamer_id,recipient,endpoint,session_hash) values('papa','P1','legacy-endpoint','legacy-hash');
 insert into papa_notifications values(1,'keep notification history');`);
 for(const name of ['202610070001_space_foundation','202610070002_device_sessions','202610070003_verified_identity_binding','202610070006_device_access_lifecycle'])
  await db.exec(fs.readFileSync('supabase/migrations/'+name+'.sql','utf8'));
 const legacy=(await q('select id,streamer_id,recipient,endpoint,session_hash from papa_push_subscriptions'))[0];
 await db.exec(fs.readFileSync('supabase/migrations/202610070010_web_device_push_bridge.sql','utf8'));
 assert.deepEqual((await q('select id,streamer_id,recipient,endpoint,session_hash from papa_push_subscriptions'))[0],legacy);
 const account=(await q('insert into papa_accounts default values returning id'))[0].id;
 await q('insert into papa_account_legacy_players values($1,$2,now())',[account,'P1']);
 await q("insert into papa_space_memberships(account_id,space_id,role) values($1,'space-001','player')",[account]);
 const device=(await q("insert into papa_device_sessions(installation_id,account_id,session_kind,role,space_id,refresh_hash,expires_at) values($1,$2,'player','player','space-001',$3,now()+interval '90 days') returning id",[(await q("insert into papa_installations(id,platform) values(gen_random_uuid(),'web') returning id"))[0].id,account,'a'.repeat(64)]))[0].id;
 const allowed=async(room='papa',recipient='P1')=>(await q('select papa_device_push_recipient($1,$2,$3) value',[device,room,recipient]))[0].value;
 assert.equal(await allowed(),true);assert.equal(await allowed('michelle'),true);
 assert.equal(await allowed('papa','P2'),false);assert.equal(await allowed('papa','__admin__'),false);
 await q("insert into papa_v2_sessions(token_hash,player_id,role,account_id,device_session_id,expires_at) values($1,'P1','player',$2,$3,now()-interval '1 hour')",['b'.repeat(64),account,device]);
 assert.equal((await q('select papa_verified_session_actor($1) value',['b'.repeat(64)]))[0].value,null);
 assert.equal(await allowed(),true,'background push does not depend on expired short access');
 await q("insert into papa_spaces(id,slug,display_name) values('space-002','other','Other')");
 await q("insert into papa_space_streamers values('other','space-002',now())");
 assert.equal(await allowed('other'),false);
 await assert.rejects(q("insert into papa_push_subscriptions(streamer_id,recipient,device_session_id) values('other','P1',$1)",[device]),/MISMATCH/);
 const route=(await q("insert into papa_push_subscriptions(streamer_id,recipient,device_session_id) values('papa','P1',$1) returning id",[device]))[0].id;
 await q('insert into papa_push_jobs values(1,$1)',[route]);
 await q("update papa_space_memberships set status='suspended' where account_id=$1",[account]);assert.equal(await allowed(),false);
 await q("update papa_space_memberships set status='active' where account_id=$1",[account]);
 await q("update papa_accounts set disabled_at=now() where id=$1",[account]);assert.equal(await allowed(),false);
 await q('update papa_accounts set disabled_at=null where id=$1',[account]);
 await q('update papa_device_sessions set revoked_at=now() where id=$1',[device]);
 assert.equal(await allowed(),false);assert.equal((await q('select count(*)::int n from papa_push_jobs'))[0].n,0);
 assert.equal((await q('select count(*)::int n from papa_push_subscriptions'))[0].n,1,'legacy route remains');
 assert.equal((await q('select body from papa_notifications'))[0].body,'keep notification history');
 await db.exec('set role anon');await assert.rejects(allowed(),/permission denied/);await db.exec('reset role');
});
