// Authentication is checked here for every operation; no browser service key.
import {empty,TABLES,mutate,publicView,migrateLegacy,previewImport,applyImport,playerSearch,upgradePlatform,scopeState,searchAcrossStreamers} from '../../../src/core.js';
const URL=Deno.env.get('SUPABASE_URL')!,KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,ADMIN=Deno.env.get('PAPA_ADMIN_USER_ID');
const headers={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,authorization,apikey','Access-Control-Allow-Methods':'POST, OPTIONS'};
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
async function api(path:string,body?:unknown,method?:string){const r=await fetch(URL+path,{method:method||(body?'POST':'GET'),headers,body:body?JSON.stringify(body):undefined});const text=await r.text();if(!r.ok)throw new Error(text.includes('VERSION_CONFLICT')?'資料剛更新了，請重新整理後再試一次':'資料庫操作失敗');return text?JSON.parse(text):null;}
async function load(){const snap=await api('/rest/v1/rpc/papa_v2_snapshot',{}),s=empty();s.revision=snap.revision;for(const r of snap.rows){if(r.kind==='settings')s.settings=r.data;else if(r.kind==='meta')Object.assign(s,r.data);else if(TABLES.includes(r.kind))s[r.kind].push(r.data);}for(const k of TABLES)s[k].sort((a:any,b:any)=>(a._order||0)-(b._order||0));return upgradePlatform(s);}
function entries(s:any){return [...TABLES.flatMap(k=>s[k].map((data:any,index:number)=>({kind:k,id:String(data.playerId&&k==='players'?data.playerId:data.songId&&k==='songs'?data.songId:data.id),data:{...data,_order:index}}))),{kind:'settings',id:'1',data:s.settings},{kind:'meta',id:'1',data:{schemaVersion:3,streamers:s.streamers,streamerSettings:s.streamerSettings,migrationIssues:s.migrationIssues||[]}}];}
async function commit(before:any,after:any,context:any={}){const old=new Map(entries(before).map(r=>[r.kind+':'+r.id,r])),next=entries(after),keys=new Set(next.map(r=>r.kind+':'+r.id));const changes=next.filter(r=>JSON.stringify(old.get(r.kind+':'+r.id)?.data)!==JSON.stringify(r.data)),removed=[...old.values()].filter(r=>!keys.has(r.kind+':'+r.id)).map(r=>({kind:r.kind,id:r.id}));after.revision=await api('/rest/v1/rpc/papa_release_a_commit',{expected:before.revision,changes,removed,actor_context:context});return after;}
async function actor(token:string){if(!token)return null;if(token.startsWith('player:')||token.startsWith('admin:')){const token_hash=await hash(token),rows=await api('/rest/v1/papa_v2_sessions?token_hash=eq.'+token_hash+'&expires_at=gt.'+encodeURIComponent(new Date().toISOString()));return rows[0]?(token.startsWith('admin:')&&rows[0].player_id==='__admin__'?{role:'admin'}:token.startsWith('player:')?{role:'player',playerId:rows[0].player_id,loginId:rows[0].login_id}:null):null;}const r=await fetch(URL+'/auth/v1/user',{headers:{apikey:KEY,Authorization:'Bearer '+token}});if(!r.ok)return null;const u=await r.json();return ADMIN&&u.id===ADMIN?{role:'admin'}:null;}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});const respond=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}});try{if(req.method!=='POST')return respond({error:'Method not allowed'},405);const b=await req.json(),who=await actor(b.token||''),t=new Date().toISOString();
 if(b.op==='adminLogin'){if(!ADMIN){const old=await api('/rest/v1/party_state?id=eq.1&select=data'),password=old[0]?.data?.settings?.adminPassword;if(!password||!b.password||await hash(String(password))!==await hash(String(b.password)))throw new Error('管理密碼不正確');const token='admin:'+crypto.randomUUID()+crypto.randomUUID();await api('/rest/v1/papa_v2_sessions',{token_hash:await hash(token),player_id:'__admin__',login_id:'',expires_at:new Date(Date.now()+43200000).toISOString()});return respond({token,expiresIn:43200,legacy:true});}const r=await fetch(URL+'/auth/v1/token?grant_type=password',{method:'POST',headers,body:JSON.stringify({email:b.email,password:b.password})}),v=await r.json();if(!r.ok||v.user?.id!==ADMIN)throw new Error('管理登入資料不正確');return respond({token:v.access_token,refreshToken:v.refresh_token,expiresIn:v.expires_in});}
 if(b.op==='refreshAdmin'){const r=await fetch(URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers,body:JSON.stringify({refresh_token:b.refreshToken})}),v=await r.json();if(!r.ok||v.user?.id!==ADMIN)throw new Error('請重新登入管理');return respond({token:v.access_token,refreshToken:v.refresh_token,expiresIn:v.expires_in});}
 if(b.op==='upload'){if(who?.role!=='admin')throw new Error('只有管理員能上傳');const binary=Uint8Array.from(atob(b.image),c=>c.charCodeAt(0));if(binary.length>3145728||b.mime!=='image/webp')throw new Error('請使用壓縮後圖片');const path=crypto.randomUUID()+'.webp',r=await fetch(URL+'/storage/v1/object/papa-photos/'+path,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'image/webp'},body:binary});if(!r.ok)throw new Error('圖片上傳失敗');return respond({url:URL+'/storage/v1/object/public/papa-photos/'+path});}
 if(b.op==='events'){if(who?.role!=='admin')throw new Error('請先登入管理');const snapshot=await load(),room=scopeState(snapshot,b.streamer||'papa').currentStreamer.id,page=Math.max(0,Math.min(100000,Math.floor(Number(b.page)||0)));const rows=await api('/rest/v1/papa_events?streamer_id=eq.'+encodeURIComponent(room)+'&order=created_at.desc,id.desc&limit=51&offset='+page*50);return respond({rows:rows.slice(0,50),hasMore:rows.length>50});}
 const s=await load();if(b.op==='login'){if(who?.playerId)throw new Error('請先登出再登入');const p=s.players.find((p:any)=>p.playerId===b.playerId);if(!p||String(p.password||'')!==String(b.password||''))throw new Error('玩家密碼不正確');const token='player:'+crypto.randomUUID()+crypto.randomUUID();await api('/rest/v1/papa_v2_sessions',{token_hash:await hash(token),player_id:p.playerId,login_id:p.ids.includes(b.loginId)?b.loginId:'',expires_at:new Date(Date.now()+30*86400000).toISOString()});return respond({token});}
 if(b.op==='logout'){if(b.token?.startsWith('player:'))await api('/rest/v1/papa_v2_sessions?token_hash=eq.'+await hash(b.token),undefined,'DELETE');return respond({ok:true});}
 if(b.op==='songSearch'){return respond({songs:searchAcrossStreamers(s,b.query||'').slice(0,100)});}if(b.op==='search'){return respond({players:b.query?.trim()?playerSearch(s,b.query).slice(0,20).map((p:any)=>({playerId:p.playerId,name:p.name,ids:p.ids,hasPassword:!!p.password})):[]});}
 if(b.op==='backup'){if(who?.role!=='admin')throw new Error('請先登入管理');return respond({backup:s,now:t});}const project=async(value:any)=>{const view=publicView(value,who,t,b.streamer||'papa'),signatures:any={},delta:any={};for(const [key,v] of Object.entries(view)){signatures[key]=await hash(JSON.stringify(v));if(b.signatures?.[key]!==signatures[key])delta[key]=v;}return {state:delta,signatures,now:t,ready:scopeState(value,b.streamer||'papa').songs.length>0};};
 if(b.op==='read'){if(b.token&&!who)throw new Error('登入已到期，請重新登入');return respond(await project(s));}
 if(who?.role!=='admin'&&(b.op!=='mutate'||!['request','wish','self','cancelOwn'].includes(b.action?.type)))throw new Error('請先登入管理');
 if(b.op==='migrate'){if(s.songs.length)throw new Error('已有 V2 資料，不能重複移轉');const rows=await api('/rest/v1/party_state?id=eq.1&select=data'),old=rows[0]?.data;if(!old)throw new Error('找不到 V1 資料');const migrated=migrateLegacy(old);if(!b.confirm)return respond({issues:migrated.migrationIssues,counts:Object.fromEntries(TABLES.map(k=>[k,migrated[k].length])),backup:old});return respond({state:publicView(await commit(s,upgradePlatform(migrated)),who,t,b.streamer||'papa'),now:t});}
 if(b.revision!==s.revision)throw new Error('資料剛更新了，請重新整理後再試一次');
 let next;if(b.op==='import'){const rows=previewImport(scopeState(s,b.streamer||'papa'),b.kind,b.text);next=applyImport(s,b.kind,rows,b.choices,who,t,b.streamer||'papa');}else if(b.op==='publish'){if(b.baseRevision!==s.revision)throw new Error('正式資料已有更新，請重新建立草稿');if(b.state?.schemaVersion!==3)throw new Error('草稿格式錯誤');if(!b.state.streamerSettings)throw new Error('請先取得完整平台草稿');next=b.state;}else next=mutate(s,{...b.action,streamer:b.streamer||'papa'},who,t);
 return respond(await project(await commit(s,next,{role:who?.role||'unknown',player_id:who?.playerId||null,streamer_id:scopeState(s,b.streamer||'papa').currentStreamer.id,action:b.op==='mutate'?b.action?.type+(b.action?.data?.operation?':'+b.action.data.operation:''):b.op})));
 }catch(e){return respond({error:e.message||'操作失敗'},400);}});
