import {createBoard} from './board.js?v=9.24-C.2.1';
import {createChat} from './chat.js?v=9.24-C.1';
import {normalizeHome,themePalette} from './home-settings.js?v=9.24-H';
import {openHomeEditor} from './home-editor.js?v=9.24-H';
import {streamerName,streamerText,streamerDestination} from './streamer-navigation.js?v=9.24-B.2';
import {createNotifications} from './notifications.js?v=9.24-B.1';
import {API,PUBLISHABLE_KEY} from './config.js';
import {empty,TIERS,TABLES,mutate,publicView,migrateLegacy,balance,stats,liveDay,timeValue,stamp,usedHour,hourKey,matchesSong,crownFor,isActive,songPlays,playerSearch,achievements,previewImport,applyImport,list,upgradePlatform,scopeState,quoteSong,reservedCredits} from './core.js?v=9.24-H';
const $=s=>document.querySelector(s),h=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demo=new URLSearchParams(location.search).has('demo')||location.pathname.endsWith('/preview.html'),roomCacheKey=k=>['draft','adminTab'].includes(k)?k+'-'+(new URLSearchParams(location.search).get('streamer')||'papa'):k,get=k=>{try{return JSON.parse(localStorage.getItem('papa-v2-'+(demo?'preview-':'')+roomCacheKey(k)));}catch{return null;}},put=(k,v)=>localStorage.setItem('papa-v2-'+(demo?'preview-':'')+roomCacheKey(k),JSON.stringify(v));
let state=empty(),full=null,session=get('player'),admin=get('admin'),draft=get('draft'),offset=0,busy=false,route=location.hash.slice(1)||'home',tab=new URLSearchParams(location.search).get('adminTab')||get('adminTab')||'dashboard',subtab=new URLSearchParams(location.search).get('tab')||'overview',selectedPlayer=new URLSearchParams(location.search).get('player')||null,photoIndex=0,fateId=null,fateSeen=[],importRows=[],importKind='players',importText='',migrationPreview=null;
const streamerSlug=new URLSearchParams(location.search).get('streamer')||'papa';
let eventPage=0;let signatures={};let queueHistory=false;const selectedQueue=new Set();
const selectedSongs=new Set();
let songUndo=null,songUndoTimer;
let filters={q:'',tags:[]},pages={},adminQuery='',ledgerQuery='',galleryFilter='current';
if(admin?.until<Date.now()){admin=null;put('admin',null);}if(!admin)draft=null;
const isSuperAdmin=()=>!!admin&&admin.role!=='streamer_admin';
const clock=()=>stamp(Date.now()+offset),me=()=>state.players.find(p=>p.playerId===session?.playerId),isAdmin=()=>!!admin&&route==='admin',actor=()=>isAdmin()?{role:'admin'}:session?{role:'player',playerId:session.playerId,loginId:session.loginId}:null;
const button=(label,act,id='',cls='tiny',extra='')=>`<button type="button" class="${cls}" data-act="${act}" data-id="${h(id)}" ${extra}>${label}</button>`;
const blank=(text='還沒有紀錄，先留個位置 ♡')=>`<div class="empty">${h(text)}</div>`;
const money=n=>Number(n||0).toLocaleString('zh-TW');
const time=x=>x&&Number.isFinite(timeValue(x))?new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(timeValue(x))):'舊時間待核對';
const dateInput=x=>x?new Date(timeValue(x)+8*3600000).toISOString().slice(0,16):'';
const isoInput=x=>x?stamp(timeValue(x)):null;
const dayLabel=x=>{const d=liveDay(x).split('-');return `${+d[1]}/${+d[2]} 場`;};
const playerName=id=>state.players.find(p=>p.playerId===id)?.name||state.crowns.find(c=>c.playerId===id)?.ownerName||'玩家';
const song=id=>state.songs.find(s=>s.songId===id);
const plays=s=>isAdmin()?songPlays(state,s.songId):s.plays||0;
const statusName={pending:'🎁 待確認禮物',waiting:'⏳ 待唱',completed:'🎤 已完成',cancelled:'取消',stored:'💾 已轉存歌'};
const chatter={success:['收到啦～等等唱 🎤','聲帶收到通知啦 ♡','歌已排好，耳朵準備～'],empty:['歌本翻爛了，真的沒有 🥹','這首還沒住進歌本～','找不到耶，去許願池試試 ♡'],cancel:['先讓這首休息一下～','好，這次先跳過 ♡','已取消，下首見～'],center:['你的點歌小天地 ♡','耳朵的快樂都在這裡～','看看今天累積了什麼 ✨'],full:['本小時滿啦，整點再來 ♡','先住手，歌單真的滿了～','額度休息中，現點還可以～'],paused:['{streamer}休息一下，等等再來 ♡','聲帶放風中，稍等一下～','先陪我休息一小下 ♡'],noCredit:['存歌袋空空，風吹進去都有回音。','存歌用完啦，補一點再來 ♡','口袋沒有歌了耶～'],busy:['歌單熱鬧中，慢慢唱給你聽～','待播有點多，先坐好 ♡','聲帶努力趕路中 🎤']};
const hostName=()=>streamerName(state.currentStreamer),hostText=text=>streamerText(text,state.currentStreamer);
const say=k=>hostText(chatter[k][Math.floor(Math.random()*chatter[k].length)]);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function modal(title,body,submit){$('#dialog').innerHTML=`<div class="dialog-head"><h2>${h(title)}</h2>${button('✕','close','','','aria-label="關閉"')}</div>${submit?'<form id="modal-form">':''}${body}<p class="error" id="dialog-error"></p>${submit?'<div class="actions dialog-actions"><button type="button" data-act="close">取消</button><button class="primary" type="submit">儲存</button></div></form>':''}`;if(!$('#dialog').open)$('#dialog').showModal();if(submit)$('#modal-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,submitButton=form.querySelector('[type=submit]');submitButton.disabled=true;try{await submit(new FormData(form),form);$('#dialog').close();}catch(e){$('#dialog-error').textContent=e.message;if(e.liveSongId)$('#dialog-error').insertAdjacentHTML('beforeend','<div class="actions">'+button('前往現點','request',e.liveSongId,'primary','data-kind="live"')+'</div>');}finally{submitButton.disabled=false;}};}
const field=(name,label,value='',type='text',extra='')=>`<label>${h(label)}<input name="${name}" type="${type}" value="${h(value)}" ${extra}></label>`;
const area=(name,label,value='')=>`<label class="full">${h(label)}<textarea name="${name}">${h(value)}</textarea></label>`;
const nativeSelect=(name,label,values,value)=>`<label>${h(label)}<select name="${name}">${values.map(v=>{const [id,text]=Array.isArray(v)?v:[v,v];return `<option value="${h(id)}" ${String(value)===String(id)?'selected':''}>${h(text)}</option>`;}).join('')}</select></label>`;
const check=(name,label,on=false)=>`<label class="check-row"><input type="checkbox" name="${name}" ${on?'checked':''}>${h(label)}</label>`;
const formData=f=>Object.fromEntries(f.entries());
function paginate(items,key,size=10){const max=Math.max(1,Math.ceil(items.length/size));pages[key]=Math.min(Math.max(1,pages[key]||1),max);return {rows:items.slice((pages[key]-1)*size,pages[key]*size),nav:`<div class="pagination">${button('上一頁','page',key,'tiny',`data-step="-1" ${pages[key]===1?'disabled':''}`)}<label class="page-jump">第 <input type="number" min="1" max="${max}" value="${pages[key]}" data-page-key="${h(key)}" aria-label="輸入頁碼"> / ${max} 頁</label>${button('跳頁','jumpPage',key)}${button('下一頁','page',key,'tiny',`data-step="1" ${pages[key]===max?'disabled':''}`)}</div>`};}
async function api(body){if(admin&&(isAdmin()||body.management)&&!admin.legacy&&admin.accessUntil<Date.now()&&body.op!=='refreshAdmin'){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLISHABLE_KEY},body:JSON.stringify({op:'refreshAdmin',refreshToken:admin.refreshToken})}),v=await r.json();if(!r.ok)throw new Error(v.error||'請重新登入管理');admin={...admin,...v,accessUntil:Date.now()+(v.expiresIn-60)*1000};put('admin',admin);}const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLISHABLE_KEY},body:JSON.stringify({streamer:streamerSlug,token:(isAdmin()||body.management)?admin?.token:session?.token,signatures,...body})});const data=await r.json();if(!r.ok||data.error)throw new Error(data.error||'連線失敗');if(data.signatures)signatures=data.signatures;if(data.now)offset=timeValue(data.now)-Date.now();return data;}
async function refresh(force=false){if(busy)return;if(demo||draft&&isAdmin()){full=(draft&&isAdmin()?draft.state:null)||get('demo')||full;state=publicView(full,actor(),clock(),streamerSlug);render();return;}const r=await api({op:'read',revision:force?-1:state.revision});if(r.state){state={...state,...r.state};render();}if(!r.ready&&!isAdmin())$('#app').innerHTML=`<section class="card"><h2>歌本整理中 ♡</h2><p>管理員完成資料移轉後就能開始點歌。</p>${button('管理入口','admin')}</section>`;}
async function dispatch(type,data){if(busy)throw new Error('上一筆還在處理');busy=true;try{if(demo||draft&&isAdmin()){const before=structuredClone(full);full=mutate(full,{type,data,streamer:streamerSlug},actor(),clock());notifications.localChange(before,full,{type,data,streamer:streamerSlug},actor());if(draft&&isAdmin()){draft.state=full;put('draft',draft);}else put('demo',full);state=publicView(full,actor(),clock(),streamerSlug);}else{const r=await api({op:'mutate',revision:state.revision,action:{type,data}});state={...state,...r.state};}render();notifications.refresh().catch(()=>{});}finally{busy=false;}}
function switchStreamer(slug){if(slug===streamerSlug)return;location.href=streamerDestination(location.href,slug,{role:admin?.role,managedSlug:admin?.streamerSlug,subtab,adminTab:tab});}
document.addEventListener('change',e=>{if(e.target.id==='header-streamer')switchStreamer(e.target.value);});
async function go(next){if(next==='admin'&&admin?.role==='streamer_admin'&&admin.streamerSlug!==streamerSlug){const u=new URL(location.href);u.hash='admin';location.href=streamerDestination(u.href,admin.streamerSlug,{role:admin.role,managedSlug:admin.streamerSlug});return;}signatures={};route=next;location.hash=next;filters={q:'',tags:[]};pages={};if(next==='admin'&&!admin){route='home';await adminLogin();return;}if(next==='center'&&!session){route='home';await loginDialog();return;}await refresh(true);}
const notifications=createNotifications({api:b=>api({...b,management:!!admin,streamer:admin?.role==='streamer_admin'?admin.streamerSlug:streamerSlug}),apiUrl:API,apiKey:PUBLISHABLE_KEY,context:()=>({demo:demo||!!(draft&&isAdmin()),role:admin?(admin.role||'super_admin'):'player',recipient:admin?(isSuperAdmin()?'__super__':'__admin__'):session?.playerId,streamer:admin?(isSuperAdmin()?'__global__':admin.streamerSlug):streamerSlug,streamerName:admin&&isSuperAdmin()?'全部主播':state.currentStreamer?.display_name}),toast,onUpdate:()=>{chat.refresh().catch(()=>{});if(!busy&&!$('#dialog').open&&!document.activeElement?.matches('input,textarea,select'))refresh().catch(()=>{});}});
const chat=createChat({api,context:()=>({manager:isAdmin(),playerId:session?.playerId,streamer:streamerSlug,streamerName:hostName(),demo:demo||!!draft}),toast,onRead:()=>notifications.refresh().catch(()=>{})});
document.addEventListener('click',e=>{if(e.target.closest('[data-open-chat]'))chat.open().catch(e=>toast(e.message));});
const board=createBoard({api,context:()=>({manager:isAdmin(),role:admin?.role,playerId:session?.playerId,streamer:streamerSlug,streamerName:hostName(),demo:demo||!!draft}),toast});
document.addEventListener('click',e=>{if(e.target.closest('[data-open-board]'))board.open().catch(e=>toast(e.message));});
function header(){const p=me();$('#header').innerHTML=`${demo?'<div class="offline">預覽測試模式 · 資料只在這台裝置，未連正式資料庫</div>':''}<div class="header-inner">${button('<span class="brand-logo" role="img" aria-label="PA • PARTY"></span>','home','','brand')}<div class="login-status">${p?`<b title="${h(p.name)}">👤 ${h(p.name)}${session.loginId?'｜ID '+h(session.loginId):''}</b><small>可以開始點歌嚕 ♡</small>`:''}</div><div class="header-actions"><label class="header-streamer"><span>主播</span><select id="header-streamer" aria-label="切換主播">${state.streamers?.filter(r=>r.active||isAdmin()&&isSuperAdmin()).map(r=>`<option value="${h(r.slug)}" ${r.slug===streamerSlug?'selected':''}>${h(r.display_name)}</option>`).join('')||''}</select></label>${button(h('回'+hostName()+'首頁'),'home')}${button('歌本','book')}${p?button('玩家中心','center')+button('登出','logout'):button('玩家登入','login')}${button('管理','admin')}${chat.button()}${board.button()}${notifications.button()}</div></div>`;}
function card(title,body,wide=false,action=''){return `<section class="card ${wide?'wide':''}">${title||action?`<div class="section-head"><h2>${title}</h2>${action}</div>`:''}${body}</section>`;}
function songRows(rows){return rows.map((s,i)=>{const c=crownFor(state,s.songId,clock());return `<div class="song"><span class="number">${i+1}</span><div class="info"><b>${h(s.title)}${c?' 👑':''}</b><small>${h(s.artist)} · ${plays(s)} 次</small>${s.murmur?`<div class="subtle">💬 ${h(hostName())}碎碎念：${h(s.murmur)}</div>`:''}<div>${(s.tags||[]).map(t=>`<span class="tag">${h(t)}</span>`).join('')}</div></div><div class="actions">${button('提歌','request',s.songId,'tiny','data-kind="saved"')}${button('現點','request',s.songId,'tiny','data-kind="live"')}</div></div>`;}).join('')||blank(say('empty'));}
function hour(){const used=isAdmin()?usedHour(state,clock()):(state.hourBucket===hourKey(clock())?state.hourlyUsed||0:0),remaining=Math.ceil((3600000-(Date.now()+offset)%3600000)/60000);return `<small>🕒 本小時提歌</small><strong>${used} / ${state.settings.hourlyLimit}</strong><small>還可以提 ${Math.max(0,state.settings.hourlyLimit-used-(state.hourlyReserved||0))} 首；待唱保留 ${state.hourlyReserved||0} 首</small><small>距離下一次提歌重置還有 ${remaining} 分鐘</small>`;}
function statsHtml(s){return `<div class="stats"><div class="stat">🎵 收到<b>${s.received}</b></div><div class="stat">🎤 唱了<b>${s.sung}</b></div><div class="stat">💾 存了<b>${s.saved}</b></div></div>`;}
function crownsHtml(rows,adminMode=false){return `<div class="crown-grid">${rows.map(c=>{const remaining=c.expiresAt?(timeValue(c.expiresAt)-Date.now()-offset)/86400000:Infinity,status=!c.activatedAt?'⏳ 待確認':!isActive(c,clock())?'🕒 已過期':remaining<=7?'⚠️ 即將到期':!c.expiresAt?'♾️ 永久':'👑 生效中';return `<div class="crown"><h3>${h(song(c.songId)?.title||c.title||'歌曲待核對')} 👑</h3><p>${h(c.tier)} · ${h(c.ownerName||playerName(c.playerId))}</p>${adminMode||c.activatedAt?`<p>${h(status)}${c.expiresAt?' · '+time(c.expiresAt):''}</p>`:''}<p>其他玩家現點 ${money(c.price)}／首＋雙費 ${money(state.settings.liveDouble??500)}</p>${adminMode?button('編輯／生效','editCrown',c.id)+button('時間','recordTime',c.id,'tiny','data-table="crowns"'):button('👑 點冠歌','requestCrown',c.id,'tiny primary')}</div>`;}).join('')||blank('還沒有冠歌，王冠等你戴 ♡')}</div>`;}
function currentCards(){return state.cards.filter(c=>timeValue(c.startsAt)<=Date.now()+offset&&(!c.expiresAt||timeValue(c.expiresAt)>Date.now()+offset));}
function photoHtml(c){return `<div class="photo"><img src="${h(c.thumbnail||c.url)}" alt="${h(c.description||'照片卡片')}" loading="lazy"><p>${h(c.description)}</p><small>${time(c.startsAt)} ～ ${c.expiresAt?time(c.expiresAt):'永久'}</small></div>`;}
function photoCarousel(){const rows=currentCards();if(!rows.length)return blank('照片還在路上，先想像一下 ♡');photoIndex=(photoIndex+rows.length)%rows.length;return photoHtml(rows[photoIndex])+`<div class="photo-controls">${button('←','photoPrev')}<small>${photoIndex+1} / ${rows.length}</small>${button('→','photoNext')}</div>`;}
function renderHome(){
 const st=state.settings.status,c=({'空閒中':['🟢','#79d5b0','歡迎點歌提歌 ♡'],'忙碌中':['🔴','#f299ab','{streamer}忙碌中～'],'準備中':['🟠','#e9b975','暖嗓準備中～'],'暫停點歌':['🟣','#c4a5ed','{streamer}休息一下～']})[st],p=me(),rank=state.rank||[],mine=rank.find(x=>x.mine),popular=[...state.songs].sort((a,b)=>plays(b)-plays(a)).slice(0,5),reco=recommendSongs(state,p?.playerId);
 const home=normalizeHome(state.settings.home),summary=state.summary||stats(state,clock());
 const defaultImage=state.currentStreamer?.banner_url||(streamerSlug==='papa'?'assets/papa-singer-hero.jpg':'');
 const heroImage=home.imageMode==='none'?'':home.imageMode==='custom'?home.imageUrl:defaultImage;
 const heroFields={title:'<h2>'+h(home.title||state.currentStreamer?.home_title||hostName()+' PARTY')+'</h2>',subtitle:'<small>'+h(home.subtitle||state.currentStreamer?.subtitle||'')+'</small>',status:'<div class="state-label" style="color:'+c[1]+'">'+c[0]+' '+h(home.statusText||st)+'</div>',message:'<p class="status-note">'+h(home.message||hostText(c[2]))+'</p>',nowPlaying:'<p class="now-playing">目前待播歌名：<strong>'+h(state.nowPlaying?.title||'目前沒有待播歌曲')+'</strong></p>',preparation:state.nowPlaying?'<p class="preparation-note">'+(state.nowPlaying.preparationMinutes>0?'準備中，請稍後 '+state.nowPlaying.preparationMinutes+' 分鐘':'準備好了，即將開唱 ♡')+'</p>':'',hour:'<div class="hour" id="hour">'+hour()+'</div>',sung:'<p>本場已唱：'+summary.sung+' 次</p>',queue:'<p>待播：'+(state.waitingCount??state.queue.filter(q=>q.status==='waiting').length)+' 首</p>'};
 const banner='<section class="hero integrated-hero">'+(heroImage?'<img src="'+h(heroImage)+'" alt="'+h(state.currentStreamer?.home_title||'音樂時光')+'">':'<div class="hero-placeholder" aria-hidden="true"></div>')+'<div class="hero-overlay">'+home.fieldOrder.filter(k=>home.fields[k]).map(k=>heroFields[k]).join('')+'</div></section>';
 const search=card('找找'+h(hostName())+'會唱的歌👀','<input id="home-search" aria-label="搜尋歌曲" placeholder="歌名、歌手、語言、標籤都可以…"><div id="home-results">'+blank('給我一點線索，幫你翻歌本 ♡')+'</div>',true,button('完整歌本 ↗','book'));
 const fresh=card('✨ 新練歌曲',songRows(state.songs.filter(s=>s.new).slice(0,5)),true);
 const fate=card('🎲 今天聽什麼？','<div class="fate-toolbar"><select id="fate-category" aria-label="命運分類">'+['全部','嗨歌','傷感','甜歌','怪歌','慢歌','完全交給命運'].map(x=>'<option>'+x+'</option>').join('')+'</select>'+button('🎲 抽一首','fate','','tiny')+'</div><div id="fate-result" class="fate"><small>讓命運幫你選一首 ♡</small></div>');
 const credits=card('💾 我的存歌',p?'<div class="stat">'+h(p.name)+' 在本主播的存歌<b>'+balance(state,p.playerId)+' 首</b></div><p class="muted">所有綁定 ID 共用；完成演唱才扣。</p>'+'<small>待唱保留 '+reservedCredits(state,p.playerId)+' 首</small>'+button('查看完整記錄','myLedger','','primary'):blank('登入後，幫你打開存歌袋 ♡')+button('玩家登入','login'));
 const ranking=card('🏆 存歌排行榜','<small>匿名 Top 5</small>'+ (rank.filter(x=>x.rank<=5).map(x=>'<div class="song"><div class="info">第 '+x.rank+' 名</div><b>'+x.amount+' 首</b></div>').join('')||blank())+'<div class="notice">'+(p?mine?'你的排名：第 '+mine.rank+' 名　存歌：'+mine.amount+' 首':'測試玩家不列入排行':'請登入查看自己的名次')+'</div>');
 const cards=card('🖼️ 卡片牆','<div id="photo-carousel">'+photoCarousel()+'</div>',false,button('全部卡片','gallery'));
 const recommendations=card('為你推薦','<p class="subtle">'+(p&&state.queue.some(q=>q.playerId===p.playerId&&q.status==='completed'&&!q.selfProvided)?'依你親自點過的歌手與標籤推薦':'還沒有聆聽偏好，先隨機選幾首 ♡')+'</p>'+songRows(reco));
 if(state.settings.home){const modules={hero:banner,search,fresh,fate,credits,popular:card('🔥 熱門點歌',songRows(popular)),recommendations,crowns:card('👑 冠歌',crownsHtml(state.crowns.filter(c=>isActive(c,clock())||c.legacyDisplay)),true,button('如何冠歌？','crownHelp')),ranking,cards,wishes:card('🌟 許願池','<p>希望'+h(hostName())+'可以學會這首</p>'+button('投一個願望','wish','','primary')),recap:card('🌙 本晚回顧','<small>'+dayLabel(clock())+' · 每天 19:00 換場</small>'+statsHtml(summary)),manual:card('📖 說明書','<div class="manual">'+h(hostText(state.settings.manual).replace('提歌扣存歌','完成演唱才扣存歌'))+'</div>',false,button('價格表','prices'))};$('#app').innerHTML='<div class="grid custom-home">'+home.order.filter(k=>home.visible[k]).map(k=>'<div class="home-module home-module-'+k+(['hero','search','fresh','crowns'].includes(k)?' wide':'')+'" data-home-module="'+k+'">'+modules[k]+'</div>').join('')+'</div>';return;}
 $('#app').innerHTML=banner+'<div class="grid">'+search+fresh+'<div class="compact-pair mini-pair">'+fate+credits+'</div>'+card('🔥 熱門點歌',songRows(popular))+recommendations+card('👑 冠歌',crownsHtml(state.crowns.filter(c=>isActive(c,clock())||c.legacyDisplay)),true,button('如何冠歌？','crownHelp'))+'<div class="home-stack">'+ranking+cards+'</div><div class="compact-pair">'+card('🌟 許願池','<p class="muted">希望'+h(hostName())+'可以學會這首<br>需要使用玩家身分投遞</p>'+button('投一個願望','wish','','primary'))+card('🌙 本晚回顧','<small>'+dayLabel(clock())+' · 每天 19:00 換場</small>'+statsHtml(state.summary||stats(state,clock())))+'</div>'+card('📖 說明書','<div class="manual">'+h(hostText(state.settings.manual).replace('提歌扣存歌','完成演唱才扣存歌'))+'</div>',false,button('價格表','prices'))+'</div>';
}
function recommendSongs(s,id){const history=s.queue.flatMap(q=>q.items?q.items.map(i=>({...q,songId:i.songId})):q).filter(q=>q.playerId===id&&q.status==='completed'&&!q.selfProvided&&!q.test),artists=new Set(),tags=new Set();for(const q of history){const item=s.songs.find(x=>x.songId===q.songId);if(item){item.artist.split(/[／/,，]/).forEach(x=>artists.add(x.trim()));item.tags.forEach(x=>tags.add(x));}}const seed=id||'guest',hash=str=>{let n=2166136261;for(const char of str)n=Math.imul(n^char.charCodeAt(0),16777619);return n>>>0;};return [...s.songs].sort((a,b)=>{const score=x=>x.artist.split(/[／/,，]/).filter(y=>artists.has(y.trim())).length*3+x.tags.filter(y=>tags.has(y)).length*2;return score(b)-score(a)||hash(seed+liveDay(clock())+a.songId)-hash(seed+liveDay(clock())+b.songId);}).slice(0,5);}

function filteredSongs(){return state.songs.filter(s=>matchesSong(s,filters.q,filters.tags));}
function songToolbar(adminMode=false){return `<div class="toolbar"><input id="song-q" aria-label="搜尋歌曲" placeholder="歌名、歌手、語言、歌詞、標籤都能搜…" value="${h(filters.q)}">${button('清除','clearFilters')}${adminMode?button('新增歌曲','editSong')+button('批量匯入','import','songs'):''}</div><div class="chips search-tags" role="group" aria-label="標籤多選">${state.settings.tags.map(t=>`<label><input type="checkbox" data-filter-tag="${h(t)}" ${filters.tags.includes(t)?'checked':''}>${h(t)}</label>`).join('')}<small>可多選，符合任一標籤即可</small></div>`;}
function renderBook(){const p=paginate(filteredSongs(),'book',20);$('#app').innerHTML=card('🎵 歌本',songToolbar()+`<div id="song-list">${songRows(p.rows)}${p.nav}</div>`,true);}
function renderGallery(){const rows=state.cards.filter(c=>galleryFilter==='history'||galleryFilter==='current'&&currentCards().includes(c)||galleryFilter==='expired'&&c.expiresAt&&timeValue(c.expiresAt)<=Date.now()+offset);$('#app').innerHTML=card('🖼️ 卡片牆',`<div class="tabs">${[['current','目前卡片'],['history','歷史卡片'],['expired','已過期']].map(([id,label])=>button(label,'galleryFilter',id,galleryFilter===id?'active':'')).join('')}</div><div class="gallery">${rows.map(photoHtml).join('')||blank()}</div>`,true);}
function playerTabs(id,manager=false){const p=state.players.find(x=>x.playerId===id);if(!p)return blank('找不到玩家');const qs=state.queue.filter(q=>q.playerId===id),done=qs.filter(q=>q.status==='completed'&&!q.test&&!q.selfProvided),cs=state.crowns.filter(c=>c.playerId===id),cards=state.cards.filter(c=>c.playerId===id),wishes=state.wishes.filter(w=>w.playerId===id),names=[['overview',manager?'基本資料':'總覽'],['ledger','存歌'],['queue','目前點歌／歷史'],['crowns','冠歌'],['cards','卡片'],['wishes','許願']];let body='';if(subtab==='overview'){const counts=done.flatMap(q=>q.items?q.items.flatMap(i=>Array(i.performances).fill({...q,songId:i.songId})):q).reduce((a,q)=>(a[q.songId]=(a[q.songId]||0)+1,a),{});body=`<div class="stats"><div class="stat">💾 存歌<b>${balance(state,id)}</b></div><div class="stat">🎤 已唱<b>${qs.filter(q=>q.status==='completed'&&!q.test).length}</b></div><div class="stat">👑 冠歌<b>${cs.length}</b></div><div class="stat">🖼️ 卡片<b>${cards.length}</b></div></div><div class="notice">${h(p.certification?'🐯 平台認證：'+p.certification:say('center'))}</div><div class="chips achievement-badges">${(manager?achievements(state,id,clock()):state.badges||[]).slice(0,3).map(x=>`<span class="tag">${h(x)}</span>`).join('')}</div><h3 style="margin-top:20px">我最常聽的歌</h3>${Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,n])=>`<div class="song"><div class="info">${h(song(id)?.title||'舊歌曲')}</div><b>×${n}</b></div>`).join('')||blank()}<div class="notice">ID：${h(p.ids.join('、')||'尚未填寫')}<br>曾用名：${h(p.names.join('、'))}</div>${manager?button('編輯玩家／密碼','editPlayer',id):button('我的名稱與密碼','self')}`;}if(subtab==='ledger')body=ledgerRows(id,manager);if(subtab==='queue')body='<h3>我的目前操作</h3>'+queueRows(qs.filter(q=>['pending','waiting'].includes(q.status)),manager)+'<h3>歷史紀錄</h3>'+queueRows(qs.filter(q=>!['pending','waiting'].includes(q.status)),manager);if(subtab==='crowns')body=crownsHtml(cs,manager);if(subtab==='cards')body=`<div class="gallery">${cards.map(photoHtml).join('')||blank()}</div>`;if(subtab==='wishes')body=wishRows(wishes,manager);return `<h2>${h(p.name)}</h2><div class="tabs">${names.map(([k,n])=>button(n,'subtab',k,subtab===k?'active':'')).join('')}</div>${body}`;}
function renderCenter(){const p=me();$('#app').innerHTML=card('👤 玩家中心',p?playerTabs(p.playerId):blank('請先登入'),true);}
function ledgerRows(id,manager){let rows=state.ledger.filter(l=>!id||l.playerId===id);if(!id&&ledgerQuery){const ids=playerSearch(state,ledgerQuery).map(x=>x.playerId);rows=rows.filter(l=>ids.includes(l.playerId));}rows.sort((a,b)=>(timeValue(b.at)||0)-(timeValue(a.at)||0));const p=paginate(rows,'ledger');return `${manager?`<div class="toolbar">${!id?`<input id="ledger-query" value="${h(ledgerQuery)}" placeholder="搜尋玩家名稱、ID、曾用名" aria-label="存歌玩家搜尋">`:''}${button('新增存歌','addLedger',id||'')}</div><small>最近 · 每頁 10 筆</small>`:''}<div id="ledger-results">${p.rows.map(l=>`<div class="song admin-row"><div class="info"><b>${manager?h(playerName(l.playerId))+' · ':''}<span class="${l.amount>=0?'positive':'negative'}">${l.amount>=0?'+':''}${l.amount} 首</span></b><small>${time(l.at)} · ${h(l.note)}</small></div>${manager?`<div class="actions">${button('編輯','editLedger',l.id)}${l.amount>0&&!l.queueId&&!l.conversion?button('分配','allocate',l.id):''}${button('刪除','deleteLedger',l.id,'tiny danger')}</div>`:''}</div>`).join('')||blank()}${p.nav}</div>`;}
function queueRows(rows,manager){const history=rows.every(q=>!['waiting','pending'].includes(q.status));if(history)rows=[...rows].sort((a,b)=>timeValue(b.effective_at||b.completedAt||b.at)-timeValue(a.effective_at||a.completedAt||a.at));const p=paginate(rows,history?'queue-history':'queue');return p.rows.map(q=>`<div class="song admin-row">${manager?`<input type="checkbox" aria-label="選取 ${h(q.title)}" data-queue-select="${h(q.id)}" ${selectedQueue.has(q.id)?'checked':''}>`:''}<div class="info"><b>${h(q.items?.map(i=>i.title+(i.performances>1?' ×'+i.performances:'')).join(' ＋ ')||q.title)}</b><small>${manager?h(playerName(q.playerId))+' · ':''}${q.kind==='saved'?'提歌':'現點'} · ${time(q.effective_at||q.at)}</small>${q.note?'<small>備註：'+h(q.note)+'</small>':''}<div><span class="tag">${statusName[q.status]}${manager&&q.selfProvided?' · 自帶（不計熱門／常聽）':''}</span>${q.test?'<span class="tag">測試</span>':''}${q.status==='waiting'?`<span class="tag">${h(q.stage)}</span>`:''}</div></div>${manager?`<div class="actions">${q.status==='pending'?button('✅ 已收到禮物','queueOp',q.id,'tiny','data-op="approve"'):''}${q.status==='waiting'?button('🎤 完成演唱','queueOp',q.id,'tiny','data-op="complete"')+button('準備時間／狀態','stage',q.id)+button('↑','move',q.id,'tiny','data-step="-1"')+button('↓','move',q.id,'tiny','data-step="1"')+(q.kind==='live'?button('未唱→存歌','queueOp',q.id,'tiny','data-op="store"'):''):''}${['waiting','pending'].includes(q.status)?button('取消','queueOp',q.id,'tiny','data-op="cancel"'):''}${button('時間／備註','recordTime',q.id,'tiny','data-table="queue"')}${button('移除紀錄','queueOp',q.id,'tiny danger','data-op="delete"')}</div>`:q.playerId===session?.playerId&&['pending','waiting'].includes(q.status)?button('取消','cancelOwn',q.id):''}</div>`).join('')+p.nav;}
function wishRows(rows,manager){const p=paginate(rows,'wishes');return p.rows.map(w=>`<div class="song"><div class="info"><b>${h(w.title)}－${h(w.artist)}</b><small>${manager?h(playerName(w.playerId))+' · ':''}${time(w.at)} · ${h(w.note)}</small><div class="tag">${h(w.status)}</div>${w.status==='已學會'?'<p class="positive">✨ 願望成真！這首'+h(hostName())+'學會啦～</p>':''}${w.url?`<a href="${h(w.url)}" target="_blank" rel="noopener">歌曲連結 ↗</a>`:''}</div>${manager?button('處理','editWish',w.id)+button('時間','recordTime',w.id,'tiny','data-table="wishes"'):''}</div>`).join('')+p.nav;}
const adminTabs=[['dashboard','📊 總覽'],['queue','🎤 待播'],['songs','🎵 歌曲'],['players','👤 玩家'],['ledger','💾 存歌'],['crowns','👑 冠歌'],['cards','🖼️ 卡片'],['wishes','🌟 許願池'],['stats','📈 統計'],['events','📜 操作歷史'],['settings','⚙️ 設定']];
function renderAdmin(){let body='';if(tab==='dashboard'){body=statsHtml(stats(state,clock()))+`<div class="stats" style="margin-top:12px">${[['歌曲',state.songs.length],['待播',state.queue.filter(q=>q.status==='waiting').length],['玩家',state.players.length],['冠歌',state.crowns.length],['待確認現點',state.queue.filter(q=>q.status==='pending').length]].map(([k,n])=>`<div class="stat">${k}<b>${n}</b></div>`).join('')}</div><h3 style="margin-top:20px">${dayLabel(clock())} · 快捷狀態</h3><div class="actions">${['🟢 空閒中','🔴 忙碌中','🟠 準備中','🟣 暫停點歌'].map(v=>button(v,'status',v.slice(3),'')).join('')}</div><h3 style="margin-top:20px">目前待播</h3>${queueRows(state.queue.filter(q=>q.status==='waiting'),true)}${isSuperAdmin()&&state.schemaVersion<3?button('讀取舊版資料並核對','migrate','','primary'):''}${state.migrationIssues?.length?`<details class="notice warning"><summary>資料移轉待核對 ${state.migrationIssues.length} 項</summary>${state.migrationIssues.map(h).join('<br>')}</details>`:''}`;}
 if(tab==='queue')body=button('後台代播／自帶','onBehalf')+`<div class="tabs">${button('待播','queueMode','active',!queueHistory?'active':'')}${button('歷史','queueMode','history',queueHistory?'active':'')}</div><p class="muted">完成演唱才扣存歌並移入歷史。自帶也照常扣除。</p><div class="actions">${button('全選目前列表','selectQueue')}${button('取消選取','clearQueueSelection')}${button('刪除已選','deleteSelectedQueue','','tiny danger')}</div>${queueRows(state.queue.filter(q=>queueHistory?!['pending','waiting'].includes(q.status):['pending','waiting'].includes(q.status)),true)}`;
 if(tab==='songs')body=songToolbar(true)+`<details class="tag-management"><summary>管理本主播標籤</summary><div class="chips">${state.settings.tags.map(t=>button(h(t)+' ×','deleteTag',t)).join('')}${button('＋標籤','addTag')}</div></details><div id="song-batch-bar">${songBatchBar()}</div><div id="song-list">${adminSongResults()}${paginate(filteredSongs(),'songs',20).nav}</div>`;
 if(tab==='players'){if(selectedPlayer)body=button('← 玩家列表','backPlayers')+playerTabs(selectedPlayer,true);else body=`<div class="toolbar"><input id="player-query" placeholder="名稱、ID、曾用名都可以" aria-label="搜尋玩家" value="${h(adminQuery)}">${button('新增玩家','editPlayer')}${button('批量匯入','import','players')}</div><div id="player-results">${playerResults()}</div>`;}
 if(tab==='ledger')body=button('收到歌單：分配現點／存歌','allocate','','primary')+ledgerRows(null,true);
 if(tab==='crowns')body=`<div class="toolbar">${button('新增冠歌','editCrown')}${button('批量匯入','import','crowns')}${button('如何冠歌？','crownHelp')}</div>${crownsHtml(state.crowns,true)}`;
 if(tab==='cards')body=`<div class="toolbar">${button('上傳照片卡','editCard')}</div><div class="gallery">${state.cards.map(c=>`<div>${photoHtml(c)}${button('編輯','editCard',c.id)}${button('刪除','deleteCard',c.id,'tiny danger')}</div>`).join('')||blank()}</div>`;
 if(tab==='wishes')body=wishRows(state.wishes,true);
 if(tab==='stats')body=`<label>選擇直播場次<input id="stats-day" type="date" value="${liveDay(clock())}"></label><div id="stats-result">${statsHtml(stats(state,clock()))}</div><p class="muted">19:00 切場。收到＝新增存歌（不含初始／歷史存歌）＋確認現點；唱了＝完成演唱次數（包含提歌）；存了＝本場收到扣除本場已唱用額，最低為 0。測試玩家不列入統計。</p>`;
 if(tab==='events'){body='<p class="muted">重要操作永久保留，依登記時間由新到舊。可展開核對修改前後資料。</p><div id="event-list">讀取中…</div>';setTimeout(loadEvents,0);}if(tab==='settings')body=settingsHtml();
 $('#app').innerHTML=`<div class="admin-banner"><b>🔐 ${isSuperAdmin()?'總管理 · ':''}${h(hostName())}的管理後台</b><div class="actions">${button(h('回'+hostName()+'首頁'),'home')}${button('登出管理','adminLogout')}</div></div><div class="streamer-toolbar"><details class="room-picker"><summary>目前管理主播：${h(state.currentStreamer.display_name)}</summary><input type="search" data-room-filter placeholder="搜尋主播"><div class="room-options">${state.streamers.map(r=>button(h(r.display_name)+(r.active?'':'（未開放）'),'switchStreamer',r.slug)).join('')}</div></details>${button('新增主播','editStreamer')}${button('編輯主播','editStreamer',state.currentStreamer.id)}${isSuperAdmin()?button('主播帳號與密碼','streamerAccounts'):''}</div><div class="tabs">${adminTabs.map(([id,label])=>button(label,'adminTab',id,tab===id?'active':'')).join('')}</div><section class="card">${body}</section>`;if(!isSuperAdmin()){for(const el of document.querySelectorAll('[data-act=editPlayer],[data-act=editStreamer],[data-act=draft],[data-act=publish],[data-act=backup],[data-act=migrate],[data-act=import][data-id=players]'))el.remove();document.querySelector('.room-picker')?.remove();}
}
function editHome(){openHomeEditor({home:state.settings.home,room:state.currentStreamer,modal,dispatch,demo,toast,upload:async file=>(await api({op:'upload',image:await compress(file,1800),mime:'image/webp'})).url});}
function applyHomeTheme(){const root=document.documentElement;if(!state.settings.home){delete root.dataset.homeTheme;return;}root.dataset.homeTheme='custom';for(const [k,v] of Object.entries(themePalette(state.settings.home.color)))root.style.setProperty('--home-'+k,v);}
function settingsHtml(){return `<div class="notice ${draft?'warning':''}">${demo?'預覽測試：資料只存在這台裝置':draft?'📝 草稿模式：只存在這台裝置':'☁️ 正式同步模式'}</div><div class="actions">${button('開始草稿測試','draft')}${button('匯出備份','backup')}${draft?button('正式同步','publish','','primary')+button('離開草稿','leaveDraft'):''}</div><hr><h3>首頁外觀與內容</h3><p class="muted">主題色、主圖、卡片顯示與排序、本日狀態欄位</p>${button('自訂首頁','editHome','','primary')}<hr><h3>直播與價格</h3><p class="muted">${h(state.settings.opening)} · 試音 ${money(state.settings.audition)} · 一般現點 ${money(state.settings.livePrice)}＋雙費 ${money(state.settings.liveDouble)}</p>${button('編輯設定與說明書','editSettings')}${button('存歌方案','editPlans')}${button('冠歌卡別價格','editTiers')}`;}
function render(){applyHomeTheme();header();if(route==='admin'&&admin)renderAdmin();else if(route==='book')renderBook();else if(route==='center'&&session)renderCenter();else if(route==='gallery')renderGallery();else renderHome();}

async function loginDialog(){modal('👤 玩家登入','<label>名稱、ID 或曾用名<input id="login-query" placeholder="找找自己"></label><div id="login-results"></div>');}
async function chooseLogin(id){const result=demo?full.players.find(p=>p.playerId===id):(await api({op:'search',query:id})).players.find(p=>p.playerId===id);if(!result)return;modal('登入 '+result.name,`${select('loginId','本次使用的 ID',result.ids.length?result.ids.map(x=>[x,x]):[['','沒有平台 ID']],result.ids[0])}${result.hasPassword||result.password?field('password','玩家密碼','','password','autocomplete="current-password"'):''}`,async f=>{let token='demo';if(!demo)token=(await api({op:'login',playerId:id,loginId:f.get('loginId'),password:f.get('password')||''})).token;else if(String(result.password||'')!==String(f.get('password')||''))throw new Error('玩家密碼不正確');session={playerId:id,loginId:f.get('loginId')||'',token};put('player',session);await go('home');});}
async function adminLogin(){modal('🔐 管理入口',nativeSelect('mode','登入身分',[['streamer','主播管理'],['super','總管理']],'streamer')+nativeSelect('streamer','選擇主播',state.streamers.map(r=>[r.slug,r.display_name]),streamerSlug)+(demo?'<p>本機測試模式</p>':field('email','總管理 Email（原密碼登入可留空）','','email','autocomplete="username"')+field('password','密碼','','password','required autocomplete="current-password"')),async f=>{const mode=f.get('mode'),slug=f.get('streamer');const auth=demo?{token:'demo',role:mode==='super'?'super_admin':'streamer_admin',streamerSlug:slug,expiresIn:43200,legacy:true}:await api({op:mode==='super'?'adminLogin':'streamerLogin',streamer:slug,email:f.get('email'),password:f.get('password')});admin={...auth,until:Date.now()+43200000,accessUntil:Date.now()+(auth.expiresIn-60)*1000};draft=null;put('admin',admin);if(admin.role==='streamer_admin'&&admin.streamerSlug!==streamerSlug){const u=new URL(location.href);u.searchParams.set('streamer',admin.streamerSlug);u.hash='admin';location.href=u.href;return;}await go('admin');toast('已登入，點「啟用通知音效」開始提醒');});}
function shortSongOptions(item){if(Number(item.creditCost)!==0.5)return '';const mode=item.shortMode||'repeat';return '<p class="notice">此歌較短；唱兩次或搭配兩首，合計扣 1 首。</p><input type="search" data-short-filter placeholder="搜尋可搭配的歌曲">'+nativeSelect('pairSongId','演唱方式',[...(mode!=='pair'?[['','這首唱兩次']]:[]),...(item.pairSongIds||[]).map(id=>song(id)).filter(Boolean).map(x=>[x.songId,'搭配：'+x.title+'－'+x.artist])],'');}
async function requestSong(id,kind,selfProvided=false){if(!session)return loginDialog();const item=song(id);if(!item)return toast('歌曲已更新');const c=crownFor(state,id,clock()),other=c&&c.playerId!==session.playerId;if(other)kind='live';const cost=Number(item.creditCost)===0.5?1:Number(item.creditCost||1);if(kind==='saved'&&balance(state,session.playerId)-reservedCredits(state,session.playerId)<cost){modal('沒有可提的存歌','<p>目前沒有足夠的存歌可提這首歌。</p><div class="actions">'+button('前往現點','request',id,'primary','data-kind="live"')+'</div>');return;}const liveHelp=button('點歌教學','prices','','tiny');modal(kind==='saved'?'🎤 確認提歌':'🎁 確認現點','<h3>'+h(item.title)+'－'+h(item.artist)+'</h3>'+shortSongOptions(item)+(kind==='saved'?'<p>此歌曲會扣 '+cost+' 首歌單。完成演唱才扣，等待時先保留額度。</p>':other?'<p>現點費用：'+money(c.price)+' 探鑽；另需雙費：'+money(state.settings.liveDouble??500)+' 探鑽</p>'+check('gift','我已確認禮物價格')+liveHelp:'<p>給歌手 '+money(state.settings.livePrice)+' 探鑽＋雙費 '+money(state.settings.liveDouble)+' 探鑽</p>'+check('gift','我已確認禮物價格')+liveHelp),async f=>{const data={songId:id,kind,selfProvided,pairSongId:f.get('pairSongId')||'',giftConfirmed:f.has('gift')};try{await dispatch('request',data);toast(say('success'));}catch(e){if(kind==='saved'){if(e.message.includes('本小時真的滿')&&!demo)try{await api({op:'failedRequest',songId:id,pairSongId:data.pairSongId});}catch{}if(e.message.includes('本小時真的滿')||e.message.includes('存歌袋空空'))e.liveSongId=id;}throw e;}});}

function crownHelp(){modal('👑 如何冠歌？',`<div class="table-wrap"><table><thead><tr><th>卡別</th><th>辦卡給歌手</th><th>辦卡雙費</th><th>其他玩家現點</th><th>期限</th></tr></thead><tbody>${state.settings.tiers.map(t=>`<tr><td>${h(t.name)}</td><td>${money(t.fee)}</td><td>${money(state.settings.crownDouble)} × 2</td><td>${money(t.price)}／首＋雙費 ${money(state.settings.liveDouble??500)}</td><td>${t.months?t.months+' 個月':'永久'}</td></tr>`).join('')}</tbody></table></div><div class="notice">🎤 給歌手對應數值禮物<br>💰 辦卡雙費：聲瑪樂團 ${money(state.settings.crownDouble)}＋2號位主持 ${money(state.settings.crownDouble)}，兩筆都需要。<br>選歌曲 → 選卡別 → 付辦卡費＋雙費 → 確認後生效 ✨</div><p class="muted">金額皆為探鑽。點歌雙費與一般現點相同，為 ${money(state.settings.liveDouble??500)}；辦卡雙費另計。冠歌主人照一般規則；其他玩家在有效期間內只能依卡別現點。</p>`);}
function prices(){modal('價格表',`<p>一首:給歌手${state.settings.livePrice}+雙費 ${state.settings.liveDouble}</p><div class="table-wrap"><table><tr><th>方案</th><th>給歌手</th><th>雙費</th></tr>${state.settings.plans.map(p=>`<tr><td>${h(p.name.includes('金牌歌單')?'🏅 金牌歌單('+p.amount+'首)':p.name.replace(/一般/g,'').trim())}</td><td>${money(p.fee)}</td><td>${money(p.double)}</td></tr>`).join('')}</table></div><p class="muted">雙費=給聲瑪樂團＋2號位主持。 以上禮物數值單位皆為探鑽</p>`);}
function wish(){if(!session)return loginDialog();modal('🌟 許個願',field('title','歌名','','text','required')+field('artist','歌手','','text','required')+area('note','備註')+field('url','歌曲連結（選填）','','url'),async f=>{await dispatch('wish',formData(f));toast('收到你的許願啦～ 願望想快點實現可考慮一首學歌費一個金牌😍');});}
function editPlayer(id){const p=state.players.find(p=>p.playerId===id)||{};modal(p.playerId?'編輯玩家':'新增玩家',`<div class="form-grid">${field('name','主要名稱',p.name||'','text','required')}${field('ids','平台 ID、其他 ID（逗號分開）',(p.ids||[]).join(','))}${field('names','曾用名／相關名',(p.names||[]).join(','))}${field('certification','🐯 平台認證',p.certification||'')}${field('password','玩家密碼（留空即清除）',p.password||'')}${!p.playerId?field('balance','初始存歌',0,'number','min="0"'):''}${area('note','備註',p.note||'')}${check('test','測試玩家（不列正式統計）',p.test)}</div>`,async f=>dispatch('player',{...formData(f),playerId:p.playerId,test:f.has('test')}));}
function playerOptions(){return [['','請選玩家'],...state.players.map(p=>[p.playerId,p.name+' · '+(p.ids.join('、')||'無平台 ID')])];}
function addLedger(id,old){const p=old||{};modal(old?'編輯存歌紀錄':'新增存歌',`${select('playerId','玩家',playerOptions(),old?.playerId||id)}${!old?`<div class="actions">${state.settings.plans.map((p,i)=>button('+'+p.amount+' '+h(p.name),'plan',String(i))).join('')}</div>`:''}${field('amount','增減首數',p.amount??1,'number','required step="0.5"')}${field('at','台北時間',dateInput(p.at||clock()),'datetime-local','required')}${field('note','來源／備註',p.note||'手動存歌')}${check('openingBalance','歷史／初始存歌（不計當日收到）',p.openingBalance||p.note==='初始存歌')}`,async f=>dispatch('ledger',{...formData(f),id:old?.id,at:isoInput(f.get('at')),openingBalance:f.has('openingBalance')}));}
function editSong(id){const s=song(id)||{};modal(s.songId?'編輯歌曲':'新增歌曲',`<div class="form-grid">${field('title','歌名',s.title||'','text','required')}${field('artist','歌手（多位以／分隔）',s.artist||'','text','required')}${nativeSelect('cat','語言',['華語','韓語','台語','其他'],!s.cat?'華語':['華語','韓語','台語'].includes(s.cat)?s.cat:'其他')}${select('artistType','歌手分類',['女歌手','男歌手','團體','合唱','其他'],s.artistType||'其他')}${field('creditCost','扣歌首數（半首填 0.5）',s.creditCost??1,'number','min="0.5" step="0.5" required')}${nativeSelect('shortMode','半首演唱方式',[['repeat','唱兩次，扣 1 首'],['pair','搭配另一半首，合扣 1 首'],['both','玩家可選唱兩次或搭配']],s.shortMode||'repeat')}<div class="full"><p>允許搭配的半首歌曲（可搜尋）</p><input type="search" data-pair-filter placeholder="搜尋搭配歌曲"><div class="pair-options">${state.songs.filter(x=>x.songId!==s.songId&&Number(x.creditCost)===0.5).map(x=>check('pairSongIds',x.title+'－'+x.artist,(s.pairSongIds||[]).includes(x.songId)).replace('name="pairSongIds"',`name="pairSongIds" value="${h(x.songId)}"`)).join('')}</div></div>${field('plays','完成次數（手動修正）',s.songId?plays(s):0,'number','min="0"')}${field('murmur','💬 '+hostName()+'碎碎念（約 20 字）',s.murmur||'','text','maxlength="40"')}${check('new','新練歌曲',s.new)}<div class="full chips">${state.settings.tags.map(t=>check('tags',t,(s.tags||[]).includes(t)).replace('name="tags"',`name="tags" value="${h(t)}"`)).join('')}</div>${field('customTags','自訂標籤（逗號分開）')}${area('lyrics','歌詞搜尋內容',s.lyrics||'')}</div>`,async f=>{await dispatch('song',{...formData(f),songId:s.songId,new:f.has('new'),pairSongIds:f.getAll('pairSongIds'),tags:[...f.getAll('tags'),...list(f.get('customTags'))]});toast('歌曲已儲存，標籤與碎碎念已更新');});}
function editCrown(id){const c=state.crowns.find(c=>c.id===id)||{},tier=state.settings.tiers.find(t=>t.name===c.tier)||state.settings.tiers[0];modal('👑 冠歌管理',`<div class="form-grid">${select('playerId','冠歌主人',playerOptions(),c.playerId)}${select('songId','歌曲',state.songs.map(s=>[s.songId,s.title+'－'+s.artist]),c.songId)}${select('tier','卡別',state.settings.tiers.map(t=>t.name),tier.name)}${field('fee','辦卡給歌手',c.fee??tier.fee,'number','min="0"')}${field('price','其他玩家現點',c.price??tier.price,'number','min="0"')}${field('double','辦卡雙費（每人）',c.double??state.settings.crownDouble,'number','min="0"')}${field('months','期限月數（0＝永久）',c.months??tier.months,'number','min="0"')}${area('note','備註',c.note||'')}</div>${c.activatedAt?`<div class="notice">生效：${time(c.activatedAt)}<br>到期：${c.expiresAt?time(c.expiresAt):'永久'}</div>`:`<div class="notice">先存為待確認；三筆款項齊了，再勾選生效。</div>${check('singerPaid','已收到辦卡給歌手費用')}${check('bandPaid','已收到聲瑪樂團費用')}${check('hostPaid','已收到2號位主持費用')}${check('activate','確認現在生效，從現在開始計算期限')}`}${c.id?button('刪除冠歌','deleteCrown',c.id,'tiny danger'):''}`,async f=>dispatch('crown',{...formData(f),id:c.id,activate:f.has('activate'),singerPaid:f.has('singerPaid'),bandPaid:f.has('bandPaid'),hostPaid:f.has('hostPaid')}));$('#dialog select[name=tier]').onchange=e=>{const t=state.settings.tiers.find(t=>t.name===e.target.value);for(const k of ['fee','price','months'])$('#dialog [name='+k+']').value=t[k];};}
async function compress(file,max=1400){if(!file||!file.type.startsWith('image/'))throw new Error('請選圖片');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),ratio=Math.min(1,max/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.82).split(',')[1];}
function editCard(id){const c=state.cards.find(c=>c.id===id)||{};modal('🖼️ 照片卡片',`${field('file','上傳照片（自動壓縮、縮圖）','','file','accept="image/*"')}${select('playerId','綁定玩家（選填）',[['','不綁定'],...playerOptions().slice(1)],c.playerId)}${area('description','簡述',c.description||'')}${field('startsAt','開始時間',dateInput(c.startsAt||clock()),'datetime-local','required')}${field('expiresAt','到期時間（留空永久）',dateInput(c.expiresAt),'datetime-local')}`,async f=>{let url=c.url,thumbnail=c.thumbnail;const file=f.get('file');if(file?.size){if(demo)throw new Error('圖片上傳需連接 Supabase，預覽不存 Base64 圖片');url=(await api({op:'upload',image:await compress(file),mime:'image/webp'})).url;thumbnail=(await api({op:'upload',image:await compress(file,480),mime:'image/webp'})).url;}await dispatch('card',{id:c.id,url,thumbnail,playerId:f.get('playerId'),description:f.get('description'),startsAt:isoInput(f.get('startsAt')),expiresAt:isoInput(f.get('expiresAt'))});});}
function editWish(id){const w=state.wishes.find(w=>w.id===id);modal('處理許願',`<h3>${h(w.title)}－${h(w.artist)}</h3>${select('status','狀態',['收到','考慮中','學習中','已學會','暫不學'],w.status)}${check('addSong','已學會，加入曲庫（已有同歌則連動）')}`,async f=>dispatch('wishAdmin',{id,status:f.get('status'),addSong:f.has('addSong')}));}
function editSettings(){const s=state.settings;modal('⚙️ 設定',`<div class="form-grid">${field('opening','開廳時間',s.opening)}${field('hourlyLimit','每小時提歌上限',s.hourlyLimit,'number','min="0"')}${field('audition','試音價格',s.audition,'number')}${field('livePrice','一般現點給歌手',s.livePrice,'number')}${field('liveDouble','點歌雙費（一般／冠歌共用）',s.liveDouble,'number')}${field('crownDouble','辦卡雙費（每人）',s.crownDouble,'number')}${area('manual','📖 說明書（支援換行、Emoji）',s.manual)}</div>`,async f=>dispatch('settings',formData(f)));}
function editPrices(kind){const rows=state.settings[kind];modal(kind==='tiers'?'冠歌卡別價格':'存歌方案',rows.map((p,i)=>`<h3>${h(p.name)}</h3><div class="form-grid">${field('name'+i,'名稱',p.name)}${Object.keys(p).filter(k=>k!=='name').map(k=>field(k+i,({fee:'給歌手',price:'其他玩家現點',months:'期限月數（0永久）',amount:'首數',double:'雙費'})[k],p[k],'number','min="0"')).join('')}</div>`).join(''),async f=>dispatch('settings',{[kind]:rows.map((p,i)=>Object.fromEntries(Object.keys(p).map(k=>[k,k==='name'?f.get(k+i):Number(f.get(k+i))])))}));}
function importDialog(kind){importKind=kind;modal('批量匯入',`<div class="notice">${kind==='players'?'主要名稱｜平台ID｜其他ID｜曾用名稱｜存歌｜密碼｜備註｜平台認證':kind==='songs'?'歌名｜歌手｜語言｜歌手類型｜標籤｜新練｜主播碎碎念':'歌曲｜歌手｜冠歌主人｜卡別｜生效時間｜備註'}<br>一行一筆。先檢查，再匯入。冠歌匯入一律待確認。</div><textarea id="import-text" aria-label="匯入資料" rows="8"></textarea><div class="actions">${button('檢查資料','previewImport','','primary')}</div><div id="import-preview"></div>`);}
function preview(){importText=$('#import-text').value;importRows=previewImport(state,importKind,importText);$('#import-preview').innerHTML=`<div class="notice">更新玩家時保留原存歌餘額；數量異動請用存歌紀錄。</div>${importRows.map((r,i)=>`<div class="song"><div class="info"><b>第 ${r.line} 筆 · ${h(r.data.name||r.data.title||song(r.data.songId)?.title||'冠歌')}</b><small class="${r.error?'error':''}">${h(r.error||(r.match?'疑似重複，請選更新或跳過':'可新增'))}</small></div><select data-import-row="${i}" aria-label="第 ${r.line} 筆處理">${r.error?'<option value="skip">跳過錯誤</option>':r.match?'<option value="skip">跳過</option><option value="update">更新</option>':'<option value="add">新增</option><option value="skip">跳過</option>'}</select></div>`).join('')}${button('確認匯入','applyImport','','primary')}`;}
async function executeImport(){const choices=importRows.map((_,i)=>$('#dialog [data-import-row="'+i+'"]').value);if(demo||draft){full=applyImport(full,importKind,importRows,choices,{role:'admin'},clock(),streamerSlug);if(draft){draft.state=full;put('draft',draft);}else put('demo',full);state=publicView(full,actor(),clock(),streamerSlug);}else{const r=await api({op:'import',revision:state.revision,kind:importKind,text:importText,choices});state={...state,...r.state};}$('#dialog').close();render();toast('資料住進來啦 ♡');}
function backup(data=state,name='backup'){if(demo&&location.origin==='http://127.0.0.1:4173')fetch('/__backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).catch(()=>{});const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download=`papa-party-${name}-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function migrate(){if(demo)return toast('預覽不讀正式資料');migrationPreview=await api({op:'migrate'});backup(migrationPreview.backup,'v1-before-migration');modal('舊資料移轉核對',`<p>舊資料備份已下載。請先保存。</p><div class="notice">${Object.entries(migrationPreview.counts).map(([k,v])=>`${h(k)}：${v}`).join('<br>')}</div><details><summary>待核對 ${migrationPreview.issues.length} 項</summary><div class="notice warning">${migrationPreview.issues.map(h).join('<br>')}</div></details>${button('保留舊資料，建立 V2','confirmMigration','','primary')}`);}

document.addEventListener('click',async e=>{const b=e.target.closest('[data-act]');if(!b)return;const a=b.dataset.act,id=b.dataset.id;try{switch(a){
case 'pickEntity':{const box=b.closest('.entity-picker'),kind=box.dataset.entityKind,record=kind==='playerId'?state.players.find(p=>p.playerId===id):song(id);box.querySelector('[type=hidden]').value=id;box.querySelector('[data-entity-query]').value=kind==='playerId'?record.name+' · '+(record.ids.join('、')||'無平台 ID'):record.title+'－'+record.artist;box.querySelector('.entity-results').innerHTML='';break;}
case 'editHome':editHome();break;
case 'close':$('#dialog').close();break;
case 'home':case 'book':case 'center':case 'gallery':await go(a);break;
case 'login':await loginDialog();break;case 'chooseLogin':await chooseLogin(id);break;
case 'logout':if(!demo)await api({op:'logout'});session=null;put('player',null);await go('home');break;
case 'admin':admin?await go('admin'):await adminLogin();break;
case 'adminLogout':if(!demo)await api({op:'logout'});admin=null;draft=null;put('admin',null);await go('home');break;
case 'adminTab':tab=id;put('adminTab',tab);selectedPlayer=null;pages={};adminQuery='';render();break;
case 'subtab':subtab=id;pages={};render();break;
case 'jumpPage':jumpPage(document.querySelector('[data-page-key="'+id+'"]'));break;
case 'page':pages[id]=(pages[id]||1)+Number(b.dataset.step);render();break;
case 'myLedger':subtab='ledger';await go('center');break;
case 'request':await requestSong(id,b.dataset.kind,b.dataset.self==='true');break;
case 'requestCrown':{const c=state.crowns.find(c=>c.id===id);if(!c)return;if(!c.songId||!isActive(c,clock())){modal('👑 '+(song(c.songId)?.title||c.title||'冠歌'),'<p>'+h(c.tier)+' · 其他玩家現點 '+money(c.price)+' 探鑽／首＋雙費 '+money(state.settings.liveDouble??500)+' 探鑽</p><div class="notice">這首冠歌的歌曲綁定與生效資料還在核對中，確認後就能從這裡點歌 ♡</div>');}else await requestSong(c.songId,'saved');break;}
case 'crownHelp':crownHelp();break;case 'prices':prices();break;case 'wish':wish();break;
case 'photoPrev':photoIndex--;$('#photo-carousel').innerHTML=photoCarousel();break;
case 'photoNext':photoIndex++;$('#photo-carousel').innerHTML=photoCarousel();break;
case 'galleryFilter':galleryFilter=id;render();break;
case 'fate':{const cat=$('#fate-category').value,candidates=state.songs.filter(s=>['全部','完全交給命運'].includes(cat)||s.tags.includes(cat));let rows=candidates.filter(s=>!fateSeen.includes(s.songId));if(!rows.length){fateSeen=fateId?[fateId]:[];rows=candidates.filter(s=>s.songId!==fateId);}if(!rows.length)return toast('這個分類暫時沒有其他歌了 ♡');const chosen=rows[Math.floor(Math.random()*rows.length)];fateId=chosen.songId;fateSeen.push(fateId);$('#fate-result').innerHTML=`<small>✨ 命運選中了</small><b>${h(chosen.title)}${crownFor(state,fateId,clock())?' 👑':''}</b><small>${h(chosen.artist)}</small>${chosen.murmur?`<p>💬 ${h(chosen.murmur)}</p>`:''}<div class="actions" style="justify-content:center">${button('🎤 接受命運','request',fateId,'tiny','data-kind="saved" data-self="true"')}${button('🎲 這命我不要','fate')}</div>`;break;}
case 'status':await dispatch('settings',{status:id});break;
case 'streamerAccounts':await streamerAccounts();break;case 'streamerCredentials':await streamerCredentials(id);break;case 'onBehalf':onBehalf();break;case 'editStreamer':editStreamer(id);break;case 'switchStreamer':switchStreamer(id);break;case 'queueMode':queueHistory=id==='history';selectedQueue.clear();pages.queue=1;render();break;case 'selectQueue':state.queue.filter(q=>queueHistory?!['pending','waiting'].includes(q.status):['pending','waiting'].includes(q.status)).forEach(q=>selectedQueue.add(q.id));render();break;case 'clearQueueSelection':selectedQueue.clear();render();break;case 'deleteSelectedQueue':if(selectedQueue.size&&confirm('刪除選取的 '+selectedQueue.size+' 筆紀錄及對應扣歌明細？')){await dispatch('queueBulkDelete',{ids:[...selectedQueue]});selectedQueue.clear();}break;
case 'queueOp':{const op=b.dataset.op,q=state.queue.find(q=>q.id===id);if(['approve','complete','store','cancel'].includes(op)){modal(({approve:'確認收到禮物',complete:'完成演唱',store:'未唱轉存歌',cancel:'取消點歌'})[op],'<h3>'+h(q.title)+'</h3>'+field('effective_at','實際發生時間',dateInput(q.recordedAt||clock()),'datetime-local','required')+'<p class="muted">取消只解除保留額度；完成演唱才扣存歌。</p>',async f=>dispatch('queue',{id,operation:op,effective_at:isoInput(f.get('effective_at'))}));}else if(confirm('移除這筆及相連存歌明細？操作歷史仍會保留修改前資料。'))await dispatch('queue',{id,operation:op});break;}
case 'cancelOwn':{const q=state.queue.find(q=>q.id===id);modal('取消自己的點歌','<p>取消《'+h(q.title)+'》？紀錄會保留，待唱額度會解除。</p>',async()=>{await dispatch('cancelOwn',{id});toast('已取消《'+q.title+'》');});break;}
case 'recordTime':recordTime(b.dataset.table,id);break;
case 'allocate':allocateDialog(id);break;
case 'allocationRow':addAllocationRow();break;
case 'removeAllocationRow':b.closest('.allocation-row').remove();break;
case 'eventPage':eventPage=Math.max(0,eventPage+Number(id));await loadEvents();break;
case 'move':await dispatch('queue',{id,operation:'move',direction:Number(b.dataset.step)});break;
case 'stage':modal('待播舞台狀態',select('stage','狀態',['⏳ 等待中','🎤 暖嗓中','🎹 找 Key 中','✨ 準備上台'],state.queue.find(q=>q.id===id).stage)+field('preparationMinutes','這首準備幾分鐘？',state.queue.find(q=>q.id===id).preparationMinutes??5,'number','min="0" max="120" step="1" required')+'<p class="muted">成為目前待播歌曲時，首頁會顯示這首的準備時間。0 分鐘表示準備好了。</p>',async f=>dispatch('queue',{id,operation:'stage',stage:f.get('stage'),preparationMinutes:f.get('preparationMinutes')}));break;
case 'editPlayer':editPlayer(id);break;case 'playerDetail':selectedPlayer=id;subtab='overview';render();break;case 'backPlayers':selectedPlayer=null;render();break;
case 'self':{const p=me();modal('我的名稱與密碼',field('name','顯示名稱',p.name)+field('currentPassword','目前密碼','','password')+field('password','新密碼（留空不修改）','','password'),async f=>{const data={name:f.get('name')};if(f.get('password'))Object.assign(data,{password:f.get('password'),currentPassword:f.get('currentPassword')});await dispatch('self',data);});break;}
case 'addLedger':addLedger(id);break;case 'editLedger':addLedger(null,state.ledger.find(l=>l.id===id));break;
case 'deleteLedger':{const l=state.ledger.find(l=>l.id===id);if(confirm('刪除這筆存歌紀錄？玩家餘額會一起重算。'))await dispatch('ledger',{id,playerId:l.playerId,remove:true});break;}
case 'plan':{const p=state.settings.plans[+id];$('#dialog [name=amount]').value=p.amount;$('#dialog [name=note]').value=p.name;break;}
case 'editMurmur':{const chosen=song(id);modal('💬 '+hostName()+'碎碎念 · '+chosen.title,field('murmur','這首歌的小吐槽（約20字）',chosen.murmur||'','text','maxlength="40"'),async f=>{await dispatch('song',{...chosen,murmur:f.get('murmur')});toast('碎碎念已更新');});break;}
case 'selectFilteredSongs':filteredSongs().forEach(s=>selectedSongs.add(s.songId));renderSongResults();break;
case 'clearSongSelection':selectedSongs.clear();renderSongResults();break;
case 'bulkEditSongs':bulkEditSongs();break;
case 'undoSongBatch':await undoSongBatch();break;
case 'editSong':editSong(id);break;case 'deleteSong':if(confirm('刪除這首歌曲？既有點歌歷史會保留。'))await dispatch('song',{songId:id,remove:true});break;
case 'clearFilters':filters={q:'',tags:[]};render();break;
case 'deleteTag':if(confirm('刪除標籤「'+id+'」並從歌曲移除？'))await dispatch('tag',{tag:id,remove:true});break;
case 'addTag':modal('新增標籤',field('tag','標籤名稱'),async f=>dispatch('tag',{tag:f.get('tag')}));break;
case 'editCrown':editCrown(id);break;case 'deleteCrown':if(confirm('刪除冠歌？')){await dispatch('crown',{id,remove:true});$('#dialog').close();}break;
case 'editCard':editCard(id);break;case 'deleteCard':if(confirm('刪除這張照片卡片？'))await dispatch('card',{id,remove:true});break;
case 'editWish':editWish(id);break;case 'editSettings':editSettings();break;case 'editPlans':editPrices('plans');break;case 'editTiers':editPrices('tiers');break;
case 'import':importDialog(id);break;case 'previewImport':preview();break;case 'applyImport':await executeImport();break;
case 'backup':backup(draft?.state||full||(await api({op:'backup'})).backup);break;
case 'draft':if(!draft){draft={state:structuredClone(full||(await api({op:'backup'})).backup),baseRevision:state.revision};full=draft.state;put('draft',draft);render();}break;
case 'leaveDraft':if(confirm('離開草稿？已存的草稿備份仍保留。')){backup(draft.state,'draft');draft=null;put('draft',null);await refresh(true);}break;
case 'publish':if(!draft)return;if(!confirm('將草稿同步到正式資料？若正式資料已有更新，會停止以免覆蓋。'))return;backup(draft.state,'before-publish');if(!demo){const r=await api({op:'publish',revision:draft.baseRevision,baseRevision:draft.baseRevision,state:draft.state});state={...state,...r.state};}else{full=draft.state;put('demo',full);}draft=null;put('draft',null);await refresh(true);toast('正式同步成功 ♡');break;
case 'migrate':await migrate();break;
case 'confirmMigration':if(confirm('已保存備份並接受待核對項目，建立 V2 資料？')){state=(await api({op:'migrate',confirm:true})).state;$('#dialog').close();render();}break;

}}catch(err){if($('#dialog').open&&$('#dialog-error'))$('#dialog-error').textContent=err.message;else toast(err.message);}});
let querySequence=0;
const composingInputs=new WeakSet();
document.addEventListener('compositionstart',e=>{composingInputs.add(e.target);if(e.target.id==='login-query')querySequence++;});
document.addEventListener('compositionend',e=>{composingInputs.delete(e.target);updateSearch(e.target);});
document.addEventListener('input',e=>{if(!e.isComposing&&!composingInputs.has(e.target))updateSearch(e.target);});
async function updateSearch(input){const id=input.id;try{
 if(input.matches('[data-entity-query]')){const box=input.closest('.entity-picker');box.querySelector('[type=hidden]').value='';showEntityResults(box);}
 if(id==='login-query'){const seq=++querySequence,q=input.value,rows=demo?playerSearch(full,q).slice(0,20):(await api({op:'search',query:q})).players;if(seq!==querySequence||!$('#login-results'))return;$('#login-results').innerHTML=q?rows.map(p=>`<div class="song"><div class="info"><b>${h(p.name)}</b><small>${h(p.ids.join('、'))}</small></div>${button('登入','chooseLogin',p.playerId)}</div>`).join('')||blank('找不到玩家'):'';}
 if(id==='home-search')$('#home-results').innerHTML=input.value?songRows(state.songs.filter(s=>matchesSong(s,input.value)).slice(0,5)):blank('給我一點線索，幫你翻歌本 ♡');
 if(id==='song-q'){filters.q=input.value;pages[isAdmin()?'songs':'book']=1;renderSongResults();}
 if(id==='player-query'){adminQuery=input.value;pages.players=1;$('#player-results').innerHTML=playerResults();}
 if(id==='ledger-query'){ledgerQuery=input.value;pages.ledger=1;const holder=document.createElement('div');holder.innerHTML=ledgerRows(null,true);$('#ledger-results').replaceWith(holder.querySelector('#ledger-results'));}
 if(id==='stats-day')$('#stats-result').innerHTML=statsHtml(stats(state,input.value+'T19:00:00+08:00'));
}catch(err){toast(err.message);}}
async function start(){if(demo){const catalog=await (await fetch('src/catalog.json')).json();full=get('demo')||migrateLegacy({songs:catalog,users:[],queue:[],crowns:[]});if(full.schemaVersion<3){put('before-v3',full);seedPreviewCrowns(full);full=upgradePlatform(full);}put('demo',full);}if(route==='admin'&&!admin)route='home';try{await refresh(true);}catch(e){header();$('#app').innerHTML=card('連線還沒準備好',`<p>${h(e.message)}</p><p class="muted">管理員完成 V2 部署設定後即可使用。現有正式資料沒有被改動。</p>${button('管理入口','admin')}`,true);}}
let lastHour=hourKey(clock());setInterval(()=>{const nextHour=hourKey(clock());if(nextHour!==lastHour&&!busy&&!$('#dialog').open&&!document.activeElement?.matches('input,textarea,select')){lastHour=nextHour;refresh(true).catch(()=>{});}if($('#hour'))$('#hour').innerHTML=hour();},1000);
setInterval(()=>{if(document.hidden||$('#dialog').open||document.activeElement?.matches('input,textarea,select')||demo||draft)return;refresh().catch(()=>{});},30000);
setInterval(()=>{if(route==='home'&&$('#photo-carousel')&&!document.hidden){photoIndex++;$('#photo-carousel').innerHTML=photoCarousel();}},8000);
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1)||'home';if(next!==route)go(next).catch(e=>toast(e.message));});
function onBehalf(){modal('後台代播／自帶',select('playerId','玩家',playerOptions(),'')+select('songId','歌曲',state.songs.map(s=>[s.songId,s.title+'－'+s.artist]),'')+select('kind','使用方式',[['saved','完成演唱才扣存歌'],['live','現點（待確認禮物）']],'saved')+check('selfProvided','自帶：不列熱門／常聽，照常扣額度')+field('at','實際時間（留空為當下）','','datetime-local')+area('note','備註')+check('completed','補登已完成演唱')+'<p class="muted">補登過去的演唱，歸入當時統計，不占本小時提歌。</p><div id="proxy-cost"></div>',async f=>dispatch('onBehalf',{...formData(f),selfProvided:f.has('selfProvided'),at:isoInput(f.get('at')),completed:f.has('completed'),giftConfirmed:true}));let lastSongId='';const update=()=>{const current=$('#dialog [name=songId]').value;if(current===lastSongId)return;lastSongId=current;const chosen=song($('#dialog [name=songId]').value);$('#proxy-cost').innerHTML=chosen?shortSongOptions(chosen)+'<p>完成演唱扣 '+(Number(chosen.creditCost)===0.5?1:chosen.creditCost||1)+' 首</p>':'';};$('#modal-form').addEventListener('click',()=>setTimeout(update,0));}

start();

function jumpPage(input){if(!input)return;const n=Number(input.value),max=Number(input.max);if(!Number.isInteger(n)||n<1||n>max){toast('請輸入 1～'+max+' 的頁碼');return;}pages[input.dataset.pageKey]=n;render();}
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-page-key]')){e.preventDefault();jumpPage(e.target);}});
document.addEventListener('change',e=>{if(e.target.matches('[data-filter-tag]')){filters.tags=Array.from(document.querySelectorAll('[data-filter-tag]:checked'),x=>x.dataset.filterTag);pages={};render();}});

function select(name,label,values,value){if(!['playerId','songId'].includes(name))return nativeSelect(name,label,values,value);const match=values.find(v=>String(v[0])===String(value)),optional=label.includes('選填');return `<div class="entity-picker" data-entity-kind="${name}"><label>${h(label)}<input type="search" data-entity-query autocomplete="off" placeholder="${name==='playerId'?'搜尋玩家名稱、ID、曾用名':'搜尋歌名、歌手、語言、標籤'}" value="${h(match?.[0]?match[1]:'')}" aria-label="${h(label)}搜尋" ${optional?'':'required'}></label><input type="hidden" name="${name}" value="${h(value||'')}"><div class="entity-results"></div></div>`;}
function showEntityResults(box){const input=box.querySelector('[data-entity-query]'),q=input.value.trim(),kind=box.dataset.entityKind,rows=q?(kind==='playerId'?playerSearch(state,q):state.songs.filter(s=>matchesSong(s,q))):[];box.querySelector('.entity-results').innerHTML=q?(rows.slice(0,12).map(r=>button(h(kind==='playerId'?r.name+' · '+(r.ids.join('、')||'無平台 ID'):r.title+'－'+r.artist),'pickEntity',kind==='playerId'?r.playerId:r.songId,'entity-option')).join('')||'<small>沒有符合的資料</small>')+(rows.length>12?'<small>再輸入幾個字，縮小搜尋範圍 ♡</small>':''):'';}

document.addEventListener('submit',e=>{for(const box of e.target.querySelectorAll('.entity-picker')){const input=box.querySelector('[data-entity-query]');if((input.required||input.value.trim())&&!box.querySelector('[type=hidden]').value){e.preventDefault();e.stopImmediatePropagation();$('#dialog-error').textContent='請從搜尋結果點選正確的玩家或歌曲';input.focus();return;}}},true);
function seedPreviewCrowns(s){if(s.previewCrownsRestored)return;s.previewCrownsRestored=true;for(const [id,title,artist] of [['legacy-crown-1','三心愛意','不不玩家'],['legacy-crown-2','crazy 1 night','葵葵']]){if(!s.crowns.some(c=>c.id===id||c.title===title))s.crowns.push({id,title,artist,ownerName:'不不玩家',playerId:null,songId:null,tier:'至尊卡',fee:925000,price:55599,double:18188,months:0,activatedAt:null,expiresAt:null,legacyDisplay:true,note:'原網站冠歌：永久；生效時間未知。請核對綁定與款項，不自動設定生效時間。'});}}

function playerResults(){const p=paginate(playerSearch(state,adminQuery),'players');return `${p.rows.map(p=>`<div class="song"><div class="info"><b>${h(p.name)}${p.test?' 🧪':''}</b><small>${h(p.ids.join('、'))} · 💾 ${balance(state,p.playerId)}｜👑 ${state.crowns.filter(c=>c.playerId===p.playerId).length}｜🖼️ ${state.cards.filter(c=>c.playerId===p.playerId).length}｜🎤 ${state.queue.filter(q=>q.playerId===p.playerId&&q.status==='completed'&&!q.test).length}</small></div>${button('查看','playerDetail',p.playerId)}</div>`).join('')}${p.nav}`;}

function adminSongResults(){const p=paginate(filteredSongs(),'songs',20);return p.rows.map(s=>`<div class="song selectable-song ${selectedSongs.has(s.songId)?'is-selected':''}"><label class="song-check"><input type="checkbox" data-song-select="${h(s.songId)}" aria-label="選取 ${h(s.title)}" ${selectedSongs.has(s.songId)?'checked':''}></label><div class="info"><b>${h(s.title)}${s.new?' <span class="tag">✨ 新練</span>':''}</b><small>${h(s.artist)} · ${h(s.cat)} · ${plays(s)} 次</small><div class="song-tags">${s.tags?.length?s.tags.map(t=>`<span class="tag">${h(t)}</span>`).join(''):'<small class="subtle">尚未貼標籤</small>'}</div>${s.murmur?`<div class="subtle">💬 ${h(s.murmur)}</div>`:''}</div><div class="actions">${button('💬 碎碎念','editMurmur',s.songId)}${button('編輯','editSong',s.songId)}${button('刪除','deleteSong',s.songId,'tiny danger')}</div></div>`).join('')||blank('沒有符合的歌曲');}
function songBatchBar(){for(const id of selectedSongs)if(!song(id))selectedSongs.delete(id);const matches=filteredSongs(),visible=paginate(matches,'songs',20).rows,all=visible.length&&visible.every(s=>selectedSongs.has(s.songId));return `<div class="batch-toolbar"><label class="check-row"><input type="checkbox" data-select-song-page ${all?'checked':''} ${visible.length?'':'disabled'}>本頁全選</label><strong role="status" aria-live="polite">已選 ${selectedSongs.size} 首</strong>${button('選取搜尋結果（'+matches.length+'）','selectFilteredSongs','', 'tiny', matches.length?'':'disabled')}${button('取消選取','clearSongSelection','','tiny',selectedSongs.size?'':'disabled')}${button('批次編輯／貼標籤','bulkEditSongs','','tiny primary',selectedSongs.size?'':'disabled')}${songUndo&&songUndo.until>Date.now()?button('復原剛才的批次修改','undoSongBatch'):''}</div><small>可跨頁選取；搜尋不會清除已選歌曲。</small>`;}
function renderSongResults(){if(!$('#song-list'))return;const p=paginate(filteredSongs(),isAdmin()?'songs':'book',20);$('#song-list').innerHTML=(isAdmin()?adminSongResults():songRows(p.rows))+p.nav;if($('#song-batch-bar')){$('#song-batch-bar').innerHTML=songBatchBar();const rows=p.rows,checked=rows.filter(s=>selectedSongs.has(s.songId)).length,all=$('[data-select-song-page]');if(all)all.indeterminate=checked>0&&checked<rows.length;}}
document.addEventListener('change',e=>{if(e.target.matches('[data-song-select]')){const id=e.target.dataset.songSelect;e.target.checked?selectedSongs.add(id):selectedSongs.delete(id);renderSongResults();}if(e.target.matches('[data-select-song-page]')){for(const s of paginate(filteredSongs(),'songs',20).rows)e.target.checked?selectedSongs.add(s.songId):selectedSongs.delete(s.songId);renderSongResults();}});
const songEditFields=s=>({cat:s.cat,artistType:s.artistType,tags:s.tags||[],new:!!s.new,murmur:s.murmur||'',creditCost:s.creditCost??1});
function bulkEditSongs(){const ids=[...selectedSongs].filter(id=>song(id));if(!ids.length)return toast('先勾選要修改的歌曲');modal('批次編輯 '+ids.length+' 首歌曲',`<details class="notice"><summary>查看這次選取的 ${ids.length} 首</summary><div class="batch-selection">${ids.map(id=>h(song(id).title)+'－'+h(song(id).artist)).join('<br>')}</div></details><p class="muted">只改你指定的欄位，其餘資料保留。</p><div class="form-grid">${nativeSelect('tagMode','標籤處理',[['keep','不變'],['add','加上勾選標籤'],['remove','移除勾選標籤'],['replace','改成以下標籤'],['clear','清空標籤']],'keep')}${nativeSelect('cat','語言',[['','不變'],'華語','韓語','台語','其他'],'')}<div class="full chips batch-tag-options">${state.settings.tags.map(t=>check('tags',t).replace('name="tags"',`name="tags" value="${h(t)}"`)).join('')}</div>${field('customTags','其他標籤（逗號分開）')}${nativeSelect('artistType','歌手分類',[['','不變'],'女歌手','男歌手','團體','合唱','其他'],'')}${nativeSelect('new','新練歌曲',[['','不變'],['true','設為新練'],['false','取消新練']],'')}${nativeSelect('murmurMode','碎碎念',[['keep','不變'],['set','統一填寫'],['clear','清空']],'keep')}${field('creditCost','統一扣歌首數（空白不變）','','number','min="0.5" step="0.5"')}${field('murmur','統一的碎碎念','','text','maxlength="40"')}</div><div id="batch-preview" class="notice" aria-live="polite">尚未指定修改項目</div>`,async f=>{const data=bulkSongData(f,ids),before=ids.map(id=>({songId:id,...songEditFields(song(id))}));await dispatch('songsBulk',data);songUndo={before,after:ids.map(id=>({songId:id,...songEditFields(song(id))})),until:Date.now()+10000};clearTimeout(songUndoTimer);songUndoTimer=setTimeout(()=>{songUndo=null;if($('#song-batch-bar'))$('#song-batch-bar').innerHTML=songBatchBar();},10000);renderSongResults();toast('已更新 '+ids.length+' 首歌曲，可在 10 秒內復原');});const form=$('#modal-form');form.addEventListener('change',()=>updateBulkPreview(form,ids));form.addEventListener('input',e=>{if(!e.isComposing)updateBulkPreview(form,ids);});}
function bulkSongData(f,ids){const data={songIds:ids,tagMode:f.get('tagMode'),tags:[...f.getAll('tags'),...list(f.get('customTags'))]};for(const k of ['cat','artistType'])if(f.get(k))data[k]=f.get(k);if(f.get('creditCost'))data.creditCost=Number(f.get('creditCost'));if(f.get('new'))data.new=f.get('new')==='true';if(f.get('murmurMode')!=='keep')data.murmur=f.get('murmurMode')==='clear'?'':f.get('murmur');return data;}
function updateBulkPreview(form,ids){const f=new FormData(form);if((f.getAll('tags').length||f.get('customTags').trim())&&f.get('tagMode')==='keep'){form.elements.tagMode.value='add';f.set('tagMode','add');}const d=bulkSongData(f,ids),parts=[];if(d.tagMode!=='keep')parts.push(({add:'加上標籤：',remove:'移除標籤：',replace:'改成標籤：',clear:'清空標籤'})[d.tagMode]+(d.tagMode==='clear'?'':d.tags.join('、')));if(d.creditCost)parts.push('扣歌首數：'+d.creditCost);if(d.cat)parts.push('語言：'+d.cat);if(d.artistType)parts.push('歌手分類：'+d.artistType);if('new'in d)parts.push(d.new?'設為新練歌曲':'取消新練');if('murmur'in d)parts.push(d.murmur?'碎碎念：'+d.murmur:'清空碎碎念');$('#batch-preview').textContent=parts.length?'將修改 '+ids.length+' 首：'+parts.join('；'):'尚未指定修改項目';}
async function undoSongBatch(){if(!songUndo||songUndo.until<Date.now())return toast('復原時間已過');const undo=songUndo;await dispatch('restoreSongEdits',{before:undo.before,after:undo.after});songUndo=null;clearTimeout(songUndoTimer);renderSongResults();toast('已復原剛才的批次修改');}

function editStreamer(id){const r=state.streamers.find(r=>r.id===id)||{};modal(id?'編輯主播':'新增主播',field('display_name','主播名稱',r.display_name||'','text','required')+field('slug','網址名稱（英文）',r.slug||'','text','required')+field('home_title','首頁名稱',r.home_title||'')+field('subtitle','副標題',r.subtitle||'')+field('avatar_url','頭像網址',r.avatar_url||'')+field('banner_url','橫幅網址',r.banner_url||'')+area('description','介紹',r.description||'')+check('active','開放主播頁',r.active!==false),async f=>dispatch('streamer',{...formData(f),id:r.id,active:f.has('active')}));}
document.addEventListener('change',e=>{if(e.target.name==='streamer-switch'){const u=new URL(location.href);u.searchParams.set('streamer',e.target.value);location.href=u.href;}if(e.target.matches('[data-queue-select]')){e.target.checked?selectedQueue.add(e.target.dataset.queueSelect):selectedQueue.delete(e.target.dataset.queueSelect);}});
document.addEventListener('input',e=>{if(e.target.matches('[data-pair-filter]'))for(const label of document.querySelectorAll('.pair-options label'))label.hidden=!label.textContent.toLocaleLowerCase().includes(e.target.value.toLocaleLowerCase());});

document.addEventListener('input',e=>{if(e.target.matches('[data-short-filter]'))for(const option of document.querySelectorAll('[name=pairSongId] option'))option.hidden=!!option.value&&!option.textContent.toLocaleLowerCase().includes(e.target.value.toLocaleLowerCase());});

document.addEventListener('input',e=>{if(e.target.matches('[data-room-filter]'))for(const button of document.querySelectorAll('.room-options button'))button.hidden=!button.textContent.toLocaleLowerCase().includes(e.target.value.toLocaleLowerCase());});


async function loadEvents(){const holder=$('#event-list');if(!holder)return;try{if(demo||draft){holder.innerHTML=blank('永久操作歷史於正式同步時由伺服器記錄。');return;}const r=await api({op:'events',page:eventPage});if(holder!==$('#event-list'))return;const labels={players:'玩家',songs:'歌曲',ledger:'存歌',queue:'點歌',crowns:'冠歌',cards:'卡片',wishes:'許願',settings:'設定',meta:'主播設定'};holder.innerHTML=r.rows.map(x=>'<details class="notice"><summary>'+h(time(x.created_at))+' · '+h(labels[x.entity_kind]||x.entity_kind)+' · '+h(x.action)+'</summary><p>操作者：'+h(x.actor_player_id?playerName(x.actor_player_id):'管理端')+'<br>實際時間：'+h(time(x.effective_at))+'</p><pre class="event-detail">'+h(JSON.stringify({修改前:x.before_data,修改後:x.after_data},null,2))+'</pre></details>').join('')||blank('尚無新操作紀錄');holder.innerHTML+='<div class="actions">'+button('上一頁','eventPage','-1','tiny',eventPage?'':'disabled')+'<small>第 '+(eventPage+1)+' 頁</small>'+button('下一頁','eventPage','1','tiny',r.hasMore?'':'disabled')+'</div>';}catch(e){holder.textContent=e.message;}}
function recordTime(table,id){const row=state[table].find(x=>x.id===id),labels={at:'提出／存歌時間',acceptedAt:'收到禮物／確認時間',completedAt:'完成演唱時間',cancelledAt:'取消時間',storedAt:'轉存時間',activatedAt:'生效時間',expiresAt:'到期時間',startsAt:'開始時間'},keys=({queue:['at','acceptedAt','completedAt','cancelledAt','storedAt'],ledger:['at'],crowns:['activatedAt','expiresAt'],cards:['startsAt','expiresAt'],wishes:['at']})[table].filter(k=>row[k]||k==='at');modal('調整實際時間','<p>登記時間：'+h(time(row.created_at||row.createdAt))+'（保留不變）</p>'+keys.map(k=>field(k,labels[k],dateInput(row[k]),'datetime-local','required')).join('')+area('note','備註',row.note||''),async f=>dispatch('recordTime',{table,id,times:Object.fromEntries(keys.map(k=>[k,isoInput(f.get(k))])),note:f.get('note')}));}
function allocateDialog(id){const old=state.ledger.find(l=>l.id===id);modal('收到歌單：分配現點／存歌',select('playerId','玩家',playerOptions(),old?.playerId||'')+field('total','收到總首數',old?.amount||3,'number','min="0.5" step="0.5" required '+(old?'readonly':''))+field('stored','保留存歌首數',old?.amount||2,'number','min="0" step="0.5" required')+field('effective_at','實際收到時間',dateInput(old?.at||clock()),'datetime-local','required')+area('note','備註',old?.note||'')+check('openingBalance','歷史／初始存歌（不計當日收到）',old?.openingBalance||old?.note==='初始存歌')+'<p class="muted">存歌首數＋下方現點用額必須等於總首數。已收到禮物的現點直接排入待唱；選擇已唱則補登完成。</p><div id="allocation-rows"></div>'+button('＋加入現點歌曲','allocationRow'),async(f,form)=>{const items=[...form.querySelectorAll('.allocation-row')].map(row=>({songId:row.querySelector('[name=songId]').value,pairSongId:row.querySelector('[name=pairSongId]')?.value||'',completed:row.querySelector('[name=completed]').checked}));await dispatch('allocate',{...formData(f),ledgerId:old?.id,items,effective_at:isoInput(f.get('effective_at')),openingBalance:f.has('openingBalance')});});}
function addAllocationRow(){const div=document.createElement('div');div.className='allocation-row notice';div.innerHTML=select('songId','現點歌曲',state.songs.map(s=>[s.songId,s.title+'－'+s.artist]),'')+'<div class="allocation-cost"></div>'+check('completed','此首已完成演唱')+button('移除此列','removeAllocationRow');$('#allocation-rows').append(div);let previous='';div.addEventListener('click',()=>setTimeout(()=>{const id=div.querySelector('[name=songId]').value;if(id===previous)return;previous=id;const s=song(id);div.querySelector('.allocation-cost').innerHTML=s?shortSongOptions(s)+'<p>使用 '+(Number(s.creditCost)===0.5?1:s.creditCost||1)+' 首額度</p>':'';},0));}

notifications.refresh().catch(()=>{});

async function streamerAccounts(){if(!isSuperAdmin())return;const r=demo?{accounts:[]} :await api({op:'streamerAccounts'});modal('主播帳號與密碼','<p>玩家帳號全站共用；主播登入只管理自己的資料。設定或停用後，該主播現有管理登入會失效。</p>'+state.streamers.map(room=>{const a=r.accounts.find(a=>a.streamer_id===room.id);return '<div class="notice"><b>'+h(room.display_name)+'</b> · '+(a?.enabled?'已啟用':'尚未啟用')+' '+button('設定密碼／啟用','streamerCredentials',room.id)+'</div>';}).join(''));}
async function streamerCredentials(id){if(!isSuperAdmin())return;const room=state.streamers.find(r=>r.id===id);if(!room)return;modal(room.display_name+' · 主播登入',field('password','新密碼（已設定者留空可保留）','','password','minlength="4" maxlength="72" autocomplete="new-password"')+check('enabled','啟用主播登入',true),async f=>{if(demo)throw Error('請在正式總管理設定');await api({op:'setStreamerAccount',streamer:room.slug,password:f.get('password'),enabled:f.has('enabled')});toast('主播登入設定已儲存');});}
