export const TABLES=['players','songs','ledger','queue','crowns','cards','wishes'];
export const TIERS=[{name:'金卡',fee:55599,price:4200,months:1},{name:'鉑金卡',fee:125000,price:9999,months:1},{name:'鑽石卡',fee:375000,price:18188,months:1},{name:'黑卡',fee:500000,price:27999,months:3},{name:'至尊卡',fee:925000,price:55599,months:0}];
export const DEFAULTS={status:'空閒中',hourlyLimit:2,opening:'19:00～01:00（可能加班）',audition:387,livePrice:2990,liveDouble:500,crownDouble:18188,tiers:TIERS,plans:[{name:'一般 2 首',amount:2,fee:5555,double:990},{name:'一般 3 首',amount:3,fee:7299,double:1399},{name:'一般 6 首',amount:6,fee:13999,double:2799},{name:'🏅 金牌歌單',amount:10,fee:22887,double:4200}],tags:['嗨歌','傷感','甜歌','怪歌','慢歌'],manual:'1. 先登入玩家，再挑首喜歡的歌 ♡\n2. 提歌扣存歌，每小時有上限。\n3. 現點送出後，等怕怕確認禮物。\n4. 冠歌主人照一般規則；其他玩家依卡別現點。'};
export const uid=()=>crypto.randomUUID();
export const list=x=>[...new Set((Array.isArray(x)?x:String(x||'').split(/[,，、；;]/)).map(x=>String(x).trim()).filter(Boolean))];
export const norm=x=>String(x??'').trim().toLocaleLowerCase();
export function empty(){return {schemaVersion:2,revision:0,settings:structuredClone(DEFAULTS),...Object.fromEntries(TABLES.map(k=>[k,[]]))};}
export function stamp(t=Date.now()){return new Date(t).toISOString();}
export function timeValue(x){if(typeof x==='number')return x;if(!x)return NaN; if(/^\d{4}[-/]\d{1,2}[-/]\d{1,2}[ T]\d/.test(x)&&!/(Z|[+-]\d\d:\d\d)$/.test(x)){const m=x.match(/(\d{4})[-/](\d{1,2})[-/](\d{1,2})[ T](\d{1,2}):(\d{2})(?::(\d{2}))?/);return Date.UTC(+m[1],+m[2]-1,+m[3],+m[4]-8,+m[5],+(m[6]||0));}return Date.parse(x);}
export const hourKey=t=>Math.floor(timeValue(t)/3600000);
export const liveDay=t=>new Date(timeValue(t)+8*3600000-19*3600000).toISOString().slice(0,10);
export function addMonths(t,n){const d=new Date(timeValue(t)+8*3600000),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);const end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,end));return stamp(d.getTime()-8*3600000);}
export const balance=(s,id)=>s.ledger.filter(x=>x.playerId===id).reduce((n,x)=>n+Number(x.amount),0);
export const playerSearch=(s,q)=>s.players.filter(p=>[p.name,p.playerId,...p.ids,...p.names].some(v=>norm(v).includes(norm(q))));
export const isActive=(c,t)=>!!c.activatedAt&&timeValue(c.activatedAt)<=timeValue(t)&&(!c.expiresAt||timeValue(c.expiresAt)>timeValue(t));
export const crownFor=(s,id,t)=>s.crowns.find(c=>c.songId===id&&isActive(c,t));
const oldUsedHour=(s,t)=>s.queue.filter(q=>q.kind==='saved'&&!q.test&&q.acceptedAt&&hourKey(q.acceptedAt)===hourKey(t)).length;
export const songPlays=(s,id)=>s.queue.filter(q=>q.status==='completed'&&!q.test&&!q.selfProvided).reduce((n,q)=>n+(q.items?q.items.filter(i=>i.songId===id).reduce((v,i)=>v+i.performances,0):q.songId===id?1:0),0)+(s.songs.find(x=>x.songId===id)?.playAdjustment||0);
export function stats(s,t){const day=liveDay(t),same=x=>x&&Number.isFinite(timeValue(x))&&liveDay(x)===day;const incoming=s.ledger.filter(x=>!x.test&&!x.excludeStats&&!x.openingBalance&&x.note!=='初始存歌'&&!x.conversion&&x.amount>0&&same(x.at)).reduce((n,x)=>n+x.amount,0),live=s.queue.filter(q=>!q.test&&q.kind==='live'&&!q.openingBalance&&same(q.acceptedAt));const received=incoming+live.reduce((n,q)=>n+(q.creditCost||1),0),done=s.queue.filter(q=>!q.test&&q.status==='completed'&&same(q.completedAt)),spent=done.reduce((n,q)=>n+(q.creditCost||1),0);return {received,sung:done.reduce((n,q)=>n+(q.items?.reduce((v,i)=>v+i.performances,0)||1),0),saved:Math.max(0,received-spent)};}
export function achievements(s,id,t){const p=s.players.find(p=>p.playerId===id),qs=s.queue.filter(q=>q.playerId===id&&q.acceptedAt&&!q.test&&!q.selfProvided),done=qs.filter(q=>q.status==='completed'),tags=done.flatMap(q=>s.songs.find(x=>x.songId===q.songId)?.tags||[]),counts=done.reduce((a,q)=>(a[q.songId]=(a[q.songId]||0)+1,a),{}),artists=done.map(q=>s.songs.find(x=>x.songId===q.songId)?.artist),first=s.queue.filter(q=>q.acceptedAt&&!q.test&&!q.selfProvided&&liveDay(q.acceptedAt)===liveDay(t)).sort((a,b)=>timeValue(a.acceptedAt)-timeValue(b.acceptedAt))[0];return [qs.length&&'🌱 初來乍到',first?.playerId===id&&'🥇 今日第一麥',qs.some(q=>new Date(timeValue(q.at)+8*3600000).getUTCHours()<6)&&'🌙 夜貓點唱機',tags.filter(x=>x==='嗨歌').length>=3&&'🔥 嗨歌製造機',tags.filter(x=>x==='傷感').length>=3&&'💔 失戀專業戶',tags.filter(x=>x==='甜歌').length>=3&&'🍬 甜歌供應商',Object.values(counts).some(n=>n>=3)&&'🔁 這首是真愛',artists.length>=5&&new Set(artists).size===1&&'❤️ 專情派',s.crowns.some(c=>c.playerId===id&&isActive(c,t))&&'👑 冠歌守護者',balance(s,id)>=10&&'💾 存歌大戶'].filter(Boolean);}
function requireThat(ok,message){if(!ok)throw new Error(message);}
function integer(v,label,min=-1000000){const n=Number(v);requireThat(Number.isSafeInteger(n)&&n>=min&&n<=1000000000,`${label}請填有效整數`);return n;}
function requirePlayer(s,id){const p=s.players.find(p=>p.playerId===id);requireThat(p,'找不到玩家');return p;}
function log(s,p,amount,note,t,extra={}){s.ledger.push({id:uid(),playerId:p,amount,note,at:t,...extra});}
function mutateRoom(source,action,actor,t=stamp()){
 const s=structuredClone(source),a=action,payload=a.data||{};const admin=actor?.role==='admin';
 if(!['request','wish','self','cancelOwn'].includes(a.type))requireThat(admin,'請先登入管理');
 if(['request','wish','self','cancelOwn'].includes(a.type))requirePlayer(s,actor?.playerId);
 switch(a.type){
 case 'cancelOwn':{const q=s.queue.find(x=>x.id===payload.id);requireThat(q&&q.playerId===actor.playerId,'只能取消自己的點歌');requireThat(['pending','waiting'].includes(q.status),'這筆已結束');q.status='cancelled';q.cancelledAt=t;q.cancelled_by=actor.playerId;break;}
 case 'onBehalf':{const proxy={role:'admin',playerId:payload.playerId,loginId:''};const at=validTime(payload.effective_at||payload.at||t,t);let next=mutateRoom(s,{type:'request',data:payload},proxy,at);const q=next.queue.at(-1);q.recordedAt=payload.at?at:null;q.createdAt=t;q.created_at=t;q.effective_at=at;q.note=String(payload.note||'').trim().slice(0,1000);if(payload.completed){if(q.kind==='live')next=mutateRoom(next,{type:'queue',data:{id:q.id,operation:'approve'}},actor,at);next=mutateRoom(next,{type:'queue',data:{id:q.id,operation:'complete'}},actor,at);}return next;}
 case 'request':{const p=requirePlayer(s,actor.playerId),song=s.songs.find(x=>x.songId===payload.songId);requireThat(song,'找不到歌曲');requireThat(admin||s.settings.status!=='暫停點歌','怕怕休息一下，等等再來 ♡');requireThat(['saved','live'].includes(payload.kind),'請選提歌或現點');const c=crownFor(s,song.songId,t),other=c&&c.playerId!==p.playerId;requireThat(!other||payload.kind==='live','這首是冠歌，請依卡別現點 👑');const quote=quoteSong(s,song.songId,payload,p.playerId,t);if(payload.kind==='saved'){requireThat(admin||usedHour(s,t)+reservedHour(s,t)<s.settings.hourlyLimit,'先住手，本小時真的滿了啦～');requireThat(balance(s,p.playerId)-reservedCredits(s,p.playerId)>=quote.creditCost,'存歌袋空空，風吹進去都有回音。');}else requireThat(payload.giftConfirmed===true,'請先確認現點禮物價格');const q={...quote,id:uid(),songId:song.songId,playerId:p.playerId,loginId:actor.loginId||'',title:song.title,artist:song.artist,kind:payload.kind,selfProvided:!!payload.selfProvided,status:payload.kind==='saved'?'waiting':'pending',at:t,acceptedAt:payload.kind==='saved'?t:null,stage:'⏳ 等待中',test:!!p.test,price:other?c.price:s.settings.livePrice,double:other?0:s.settings.liveDouble,crownId:other?c.id:null};s.queue.push(q);break;}
 case 'queue':{const q=s.queue.find(q=>q.id===payload.id);requireThat(q,'找不到紀錄');const pending=q.status==='pending',waiting=q.status==='waiting';switch(payload.operation){case 'approve':requireThat(pending,'這筆已確認或已結束');q.status='waiting';q.acceptedAt=validTime(payload.effective_at||t,t);break;case 'complete':{const completed=validTime(payload.effective_at||q.recordedAt||t,t);requireThat(waiting,'先確認禮物，再完成演唱');if(q.kind==='saved'){requireThat(balance(s,q.playerId)>=(q.creditCost||1),'存歌不足，請先核對玩家餘額');log(s,q.playerId,-(q.creditCost||1),'完成演唱：'+q.title,completed,{queueId:q.id,test:q.test});}q.status='completed';q.completedAt=completed;q.completion_created_at=t;q.effective_at=completed;break;}case 'cancel':requireThat(pending||waiting,'這筆已結束');q.status='cancelled';q.cancelledAt=validTime(payload.effective_at||t,t);break;case 'store':requireThat(waiting&&q.kind==='live','僅已確認、未演唱現點可轉存');q.status='stored';q.storedAt=validTime(payload.effective_at||t,t);log(s,q.playerId,q.creditCost||1,'現點未唱轉存歌：'+q.title,q.storedAt,{queueId:q.id,test:q.test,conversion:true});break;case 'delete':s.queue=s.queue.filter(x=>x.id!==q.id);s.ledger=s.ledger.filter(x=>x.queueId!==q.id);break;case 'stage':requireThat(waiting,'這筆不在待播');requireThat(['⏳ 等待中','🎤 暖嗓中','🎹 找 Key 中','✨ 準備上台'].includes(payload.stage),'舞台狀態不正確');q.stage=payload.stage;if(payload.preparationMinutes!==undefined){const minutes=integer(payload.preparationMinutes,'準備分鐘',0);requireThat(minutes<=120,'準備時間最多 120 分鐘');q.preparationMinutes=minutes;}break;case 'move':{const indexes=s.queue.map((q,i)=>q.status==='waiting'?i:-1).filter(i=>i>=0),i=indexes.indexOf(s.queue.indexOf(q)),j=indexes[i+(payload.direction<0?-1:1)];if(i>=0&&j!==undefined)[s.queue[indexes[i]],s.queue[j]]=[s.queue[j],s.queue[indexes[i]]];break;}default:throw new Error('未知操作');}break;}
 case 'queueBulkDelete':{const ids=list(payload.ids);requireThat(ids.length&&ids.every(id=>s.queue.some(q=>q.id===id)),'所選紀錄已異動');s.queue=s.queue.filter(q=>!ids.includes(q.id));s.ledger=s.ledger.filter(l=>!ids.includes(l.queueId));break;}
 case 'player':{const old=s.players.find(x=>x.playerId===payload.playerId),ids=list(payload.ids).filter(x=>x!=='未知');requireThat(String(payload.name||'').trim(),'請填玩家名稱');requireThat(!s.players.some(p=>p!==old&&p.ids.some(id=>ids.includes(id))),'這個平台 ID 已綁定其他玩家');const p={...old,playerId:old?.playerId||uid(),name:String(payload.name).trim(),ids,names:list([...(old?.names||[]),old?.name,...list(payload.names),payload.name].filter(Boolean)),note:String(payload.note||''),password:String(payload.password??old?.password??''),certification:String(payload.certification||''),test:!!payload.test};if(old)Object.assign(old,p);else{s.players.push(p);const amount=creditNumber(payload.balance||0,true);if(amount)log(s,p.playerId,amount,'初始存歌',t,{test:p.test,openingBalance:true});}break;}
 case 'self':{const p=requirePlayer(s,actor.playerId);if(payload.name?.trim()){p.names=list([...p.names,p.name,payload.name.trim()]);p.name=payload.name.trim();}if(payload.password!==undefined){requireThat(!p.password||payload.currentPassword===p.password,'目前密碼不正確');requireThat(!payload.password||payload.password.length>=4,'密碼至少 4 個字');p.password=payload.password;}break;}
 case 'ledger':{requirePlayer(s,payload.playerId);const old=s.ledger.find(x=>x.id===payload.id);if(old){requireThat(old.playerId===payload.playerId,'玩家不符');if(payload.remove)s.ledger=s.ledger.filter(x=>x!==old);else{if(old.queueId){const q=s.queue.find(q=>q.id===old.queueId);requireThat(!q||q.status!=='completed'||Number(payload.amount)===old.amount,'已完成扣歌首數請保留原值');if(q?.status==='completed'){q.completedAt=validTime(payload.at,t);q.effective_at=q.completedAt;}}old.amount=creditNumber(payload.amount,true,true);old.note=String(payload.note||'');if(payload.openingBalance!==undefined)old.openingBalance=!!payload.openingBalance;requireThat(Number.isFinite(timeValue(payload.at)),'時間不正確');old.at=validTime(payload.at,t);}}else{requireThat(!payload.remove,'紀錄已刪除');log(s,payload.playerId,creditNumber(payload.amount,true,true),String(payload.note||'手動存歌'),payload.at?validTime(payload.at,t):t,{test:!!requirePlayer(s,payload.playerId).test,openingBalance:!!payload.openingBalance});}break;}
 case 'song':{const old=s.songs.find(x=>x.songId===payload.songId);if(payload.remove){requireThat(old,'歌曲不存在');requireThat(!s.crowns.some(c=>c.songId===old.songId&&isActive(c,t)),'請先處理這首的有效冠歌');s.songs=s.songs.filter(x=>x!==old);break;}requireThat(payload.title?.trim(),'請填歌名');const title=payload.title.trim(),artist=String(payload.artist||'未分類').trim();requireThat(!s.songs.some(x=>x!==old&&norm(x.title)===norm(title)&&norm(x.artist)===norm(artist)),'同名同歌手已在曲庫');const song={...old,songId:old?.songId||uid(),title,artist,cat:payload.cat||'華語',artistType:payload.artistType||'其他',tags:list(payload.tags),new:!!payload.new,murmur:String(payload.murmur||'').slice(0,40),lyrics:String(payload.lyrics??old?.lyrics??''),playAdjustment:old?.playAdjustment||0,creditCost:creditNumber(payload.creditCost??old?.creditCost??1),shortMode:payload.shortMode??old?.shortMode??'repeat',pairSongIds:list(payload.pairSongIds??old?.pairSongIds??[])};requireThat(['repeat','pair','both'].includes(song.shortMode),'半首方式不正確');requireThat(song.pairSongIds.every(id=>id!==song.songId&&s.songs.some(x=>x.songId===id&&Number(x.creditCost)===0.5)),'搭配歌曲必須是本主播的其他半首歌');if(payload.plays!==undefined)song.playAdjustment=integer(payload.plays,'次數',0)-(songPlays(s,song.songId)-(old?.playAdjustment||0));if(old)Object.assign(old,song);else s.songs.push(song);s.settings.tags=list([...s.settings.tags,...song.tags]);break;}
 case 'songsBulk':{
  const ids=[...new Set(payload.songIds||[])],rows=ids.map(id=>s.songs.find(x=>x.songId===id)),mode=payload.tagMode||'keep',tags=list(payload.tags||[]);
  requireThat(ids.length&&rows.every(Boolean),'所選歌曲有異動，請重新選取');
  requireThat(['keep','add','remove','replace','clear'].includes(mode),'標籤處理方式不正確');
  requireThat(!['add','remove','replace'].includes(mode)||tags.length,'請勾選或填寫標籤；要全部移除請選清空');
  requireThat(payload.cat===undefined||['華語','韓語','台語','其他'].includes(payload.cat),'語言不正確');
  requireThat(payload.artistType===undefined||['女歌手','男歌手','團體','合唱','其他'].includes(payload.artistType),'歌手分類不正確');
  requireThat(payload.new===undefined||typeof payload.new==='boolean','新練設定不正確');
  requireThat(payload.murmur===undefined||typeof payload.murmur==='string'&&payload.murmur.length<=40,'碎碎念最多 40 字');
  requireThat(mode!=='keep'||['cat','artistType','new','murmur','creditCost'].some(k=>payload[k]!==undefined),'請先指定要修改的欄位');
  if(payload.creditCost!==undefined)payload.creditCost=creditNumber(payload.creditCost);for(const row of rows){if(mode==='add')row.tags=list([...(row.tags||[]),...tags]);if(mode==='remove')row.tags=(row.tags||[]).filter(t=>!tags.includes(t));if(mode==='replace')row.tags=tags.slice();if(mode==='clear')row.tags=[];for(const k of ['cat','artistType','new','murmur','creditCost'])if(payload[k]!==undefined)row[k]=payload[k];}
  s.settings.tags=list([...s.settings.tags,...rows.flatMap(r=>r.tags||[])]);break;
 }
 case 'restoreSongEdits':{
  const before=payload.before,after=payload.after,keys=['cat','artistType','tags','new','murmur','creditCost'];
  requireThat(Array.isArray(before)&&before.length&&Array.isArray(after)&&before.length===after.length,'找不到可復原的修改');
  requireThat(new Set(before.map(x=>x.songId)).size===before.length,'復原歌曲重複');
  const value=(row,key)=>JSON.stringify(row[key]??(key==='tags'?[]:key==='new'?false:''));
  for(const previous of before){const current=s.songs.find(x=>x.songId===previous.songId),expected=after.find(x=>x.songId===previous.songId);requireThat(current&&expected&&keys.every(k=>value(current,k)===value(expected,k)),'歌曲已有其他修改，無法覆蓋復原');}
  for(const previous of before){const current=s.songs.find(x=>x.songId===previous.songId);for(const k of keys)current[k]=structuredClone(previous[k]);}
  s.settings.tags=list([...s.settings.tags,...before.flatMap(r=>r.tags||[])]);break;
 }
 case 'tag':{const tag=String(payload.tag).trim();if(payload.remove){s.settings.tags=s.settings.tags.filter(x=>x!==tag);s.songs.forEach(x=>x.tags=x.tags.filter(y=>y!==tag));}else if(tag)s.settings.tags=list([...s.settings.tags,tag]);break;}
 case 'crown':{const old=s.crowns.find(x=>x.id===payload.id);if(payload.remove){s.crowns=s.crowns.filter(x=>x.id!==payload.id);break;}requirePlayer(s,payload.playerId);requireThat(s.songs.some(x=>x.songId===payload.songId),'請選歌曲');const tier=s.settings.tiers.find(x=>x.name===payload.tier);requireThat(tier,'請選卡別');const c={...old,id:old?.id||uid(),playerId:payload.playerId,songId:payload.songId,tier:tier.name,fee:integer(payload.fee??tier.fee,'辦卡費',0),price:integer(payload.price??tier.price,'現點價',0),double:integer(payload.double??s.settings.crownDouble,'雙費',0),months:integer(payload.months??tier.months,'月數',0),note:String(payload.note||'')};if(payload.activate){requireThat(payload.singerPaid&&payload.bandPaid&&payload.hostPaid,'辦卡費與雙費都確認後才生效');requireThat(!old?.activatedAt,'已生效冠歌不能重新開始計時');c.activatedAt=t;c.expiresAt=c.months?addMonths(t,c.months):null;}if(c.activatedAt)requireThat(!s.crowns.some(x=>x.id!==c.id&&x.songId===c.songId&&isActive(x,t)),'這首已有有效冠歌');if(old)Object.assign(old,c);else s.crowns.push(c);break;}
 case 'card':{const old=s.cards.find(x=>x.id===payload.id);if(payload.remove){s.cards=s.cards.filter(x=>x.id!==payload.id);break;}if(payload.playerId)requirePlayer(s,payload.playerId);requireThat(/^https:\/\//.test(payload.url||''),'請先上傳圖片');requireThat(Number.isFinite(timeValue(payload.startsAt)),'請填開始時間');requireThat(!payload.expiresAt||timeValue(payload.expiresAt)>timeValue(payload.startsAt),'到期時間要晚於開始');const c={id:old?.id||uid(),url:payload.url,thumbnail:payload.thumbnail||payload.url,playerId:payload.playerId||null,description:String(payload.description||''),startsAt:stamp(timeValue(payload.startsAt)),expiresAt:payload.expiresAt?stamp(timeValue(payload.expiresAt)):null};if(old)Object.assign(old,c);else s.cards.push(c);break;}
 case 'wish':requireThat(payload.title?.trim()&&payload.artist?.trim(),'請填歌名與歌手');requireThat(!payload.url||/^https?:\/\//.test(payload.url),'歌曲連結請用 http 或 https');s.wishes.push({id:uid(),playerId:actor.playerId,title:payload.title.trim(),artist:payload.artist.trim(),note:String(payload.note||''),url:payload.url||'',at:t,status:'收到'});break;
 case 'wishAdmin':{const w=s.wishes.find(x=>x.id===payload.id);requireThat(w,'找不到許願');if(payload.remove){s.wishes=s.wishes.filter(x=>x!==w);break;}requireThat(['收到','考慮中','學習中','已學會','暫不學'].includes(payload.status),'許願狀態不正確');w.status=payload.status;if(payload.addSong){requireThat(w.status==='已學會','學會後再加入曲庫');let song=s.songs.find(x=>norm(x.title)===norm(w.title)&&norm(x.artist)===norm(w.artist));if(!song){song={songId:uid(),title:w.title,artist:w.artist,cat:'華語',artistType:'其他',tags:[],new:true,murmur:'',playAdjustment:0};s.songs.push(song);}w.songId=song.songId;}break;}
 case 'settings':{const next={...s.settings,...payload};next.hourlyLimit=integer(next.hourlyLimit,'每小時上限',0);for(const k of ['livePrice','liveDouble','audition','crownDouble'])next[k]=integer(next[k],k,0);requireThat(['空閒中','忙碌中','準備中','暫停點歌'].includes(next.status),'狀態不正確');requireThat(Array.isArray(next.tiers)&&next.tiers.length===5,'需要五種冠歌卡別');for(const x of next.tiers)for(const k of ['fee','price','months'])x[k]=integer(x[k],k,0);for(const x of next.plans)for(const k of ['amount','fee','double'])x[k]=integer(x[k],k,k==='amount'?1:0);s.settings=next;break;}
 case 'cleanup':throw new Error('全域資料清除已停用，請在各項紀錄內編輯');
 default:throw new Error('未知操作');
 }
 s.revision=(source.revision||0)+1;return s;
}

// Legacy balances are preserved by an explicit reconciliation entry, never silently recalculated.
export function migrateLegacy(old,catalog=[]){if(old?.schemaVersion>=2)return structuredClone(old);const s=empty(),issues=[];const raw=old||{};s.settings={...s.settings,status:raw.status?.status||'空閒中',hourlyLimit:raw.status?.hourlyLimit??2,tags:list(raw.settings?.songTags??s.settings.tags)};
 s.songs=(raw.songs||catalog).map(x=>({...x,songId:'S'+x.id,artist:x.artist||list(x.artists).join('／'),tags:list(x.tags),murmur:x.murmur||'',playAdjustment:0}));
 const assigned=new Set();for(const u of raw.users||[]){const playerId='P'+u.id,ids=list(u.ids).filter(x=>x!=='未知');for(const id of ids){if(assigned.has(id))issues.push(`重複平台 ID：${id}，請核對玩家`);assigned.add(id);}const p={playerId,name:u.name,ids,names:list([u.name,...list(u.names)]),note:u.note||'',password:u.playerPassword||'',certification:u.certification||'',test:!!u.testAccount};s.players.push(p);for(const [i,l] of (u.logs||[]).entries()){const at=timeValue(l.time);s.ledger.push({id:playerId+'-L'+i,playerId,amount:Number(l.amount)||0,note:l.note||l.type||'',at:Number.isFinite(at)?stamp(at):null,legacyTime:l.time,test:p.test,excludeStats:!Number.isFinite(at)});}const difference=(Number(u.credits)||0)-balance(s,playerId);if(difference){s.ledger.push({id:playerId+'-opening',playerId,amount:difference,note:'V1 餘額核對差額（保留原餘額，請管理員核對）',at:null,excludeStats:true,test:p.test});issues.push(`${p.name}：原餘額與歷史差 ${difference} 首，已保留並列核對紀錄`);}}
 const resolve=(id,name)=>{const exact=s.players.filter(p=>p.ids.includes(String(id)));if(exact.length===1)return exact[0].playerId;const matches=s.players.filter(p=>p.name===name||p.names.includes(name));if(matches.length===1)return matches[0].playerId;return null;};
 s.queue=(raw.queue||[]).map(q=>{const at=timeValue(q.time),playerId=resolve(q.userId,q.name);if(!playerId)issues.push(`待播 ${q.id} 無法唯一對應玩家`);const status=({'完成':'completed','取消':'cancelled','已轉存歌':'stored','待主播確認':'pending'})[q.status]||'waiting',kind=q.saved?'saved':'live';return {id:'Q'+q.id,playerId,songId:q.songId?'S'+q.songId:null,title:q.crownTitle||s.songs.find(x=>x.songId==='S'+q.songId)?.title||'舊歌曲',artist:'',kind,status,at:Number.isFinite(at)?stamp(at):null,acceptedAt:null,completedAt:null,legacyTime:q.time,stage:'⏳ 等待中',selfProvided:!!(q.selfProvided||q.selfProvidedAccount),test:!!(q.test||q.testAccount)||!!s.players.find(p=>p.playerId===playerId)?.test};});
 // Old timestamps do not identify gift confirmation/completion time; do not fabricate per-show stats.
 for(const song of s.songs){const completed=s.queue.filter(q=>q.songId===song.songId&&q.status==='completed'&&!q.test&&!q.selfProvided).length;song.playAdjustment=0;if(song.plays&&song.plays!==completed)issues.push(`${song.title}：舊點歌數 ${song.plays} 與完成 ${completed} 不同，新熱門按完成計算`);}
 s.crowns=(raw.crowns||[]).map(c=>{const song=s.songs.find(x=>x.songId==='S'+c.songId)||s.songs.find(x=>x.title===c.title&&x.artist===c.artist),playerId=resolve(c.crownedBy,c.crownedBy),tier=TIERS.find(x=>String(c.type).includes(x.name.replace('卡','')))||TIERS[4];issues.push(`冠歌 ${c.title}：需核對主人、款項與生效時間`);return {id:'C'+c.id,songId:song?.songId||null,playerId,title:c.title||song?.title||'',artist:c.artist||song?.artist||'',ownerName:c.crownedBy||'',legacyDisplay:true,tier:tier.name,fee:tier.fee,price:Number(c.price)||tier.price,double:18188,months:tier.months,activatedAt:null,expiresAt:null,note:'V1 待核對：'+[c.crownedBy,c.crownedAt,c.expires].join(' / ')};});
 s.migrationIssues=issues;return s;
}

export function previewImport(s,kind,text){const rows=text.trim().split(/\r?\n/).filter(Boolean).map(line=>line.split(/[｜|\t]/).map(x=>x.trim()));if(['主要名稱','歌名','歌曲'].includes(rows[0]?.[0]))rows.shift();return rows.map((cells,index)=>{let data={},matches=[],error='';if(kind==='players'){const [name,id,other,names,amount,password,note,certification]=cells;data={name,ids:list([id,...list(other)].filter(Boolean)),names:list(names),balance:amount||0,password,note,certification};matches=s.players.filter(p=>p.ids.some(x=>data.ids.includes(x))||norm(p.name)===norm(name));if(!name)error='缺玩家名稱';}else if(kind==='songs'){const [title,artist,cat,artistType,tags,isNew,murmur]=cells;data={title,artist,cat,artistType,tags:list(tags),new:['是','1','true','新練'].includes(isNew),murmur};matches=s.songs.filter(x=>norm(x.title)===norm(title)&&norm(x.artist)===norm(artist));if(!title||!artist)error='缺歌名或歌手';}else{const [title,artist,owner,tier,activation,note]=cells,ps=s.players.filter(p=>[p.name,p.playerId,...p.ids,...p.names].includes(owner)),songs=s.songs.filter(x=>norm(x.title)===norm(title)&&norm(x.artist)===norm(artist));data={songId:songs[0]?.songId,playerId:ps[0]?.playerId,tier:s.settings.tiers.find(t=>t.name===tier||t.name.replace('卡','')===tier)?.name,note:[note,activation&&'匯入指定時間（待核對）：'+activation].filter(Boolean).join(' / ')};matches=s.crowns.filter(x=>x.songId===data.songId);if(ps.length!==1||songs.length!==1||!data.tier)error='請先唯一對應玩家、歌曲與卡別';}if(matches.length>1)error='多筆疑似重複，請先手動核對';return {line:index+1,data,match:matches[0],error};});}
export function applyImport(s,kind,rows,choices,actor,t=stamp(),streamer='papa'){let next=structuredClone(s);for(const [i,r] of rows.entries()){if(choices[i]==='skip')continue;requireThat(!r.error,`第 ${r.line} 行：${r.error}`);const scoped=scopeState(next,streamer),refreshed=kind==='players'?scoped.players.filter(p=>p.ids.some(id=>r.data.ids.includes(id))||norm(p.name)===norm(r.data.name)):kind==='songs'?scoped.songs.filter(x=>norm(x.title)===norm(r.data.title)&&norm(x.artist)===norm(r.data.artist)):scoped.crowns.filter(x=>x.songId===r.data.songId);requireThat(refreshed.length<=1,'匯入資料有多筆衝突');const match=refreshed[0];requireThat(!match||choices[i]==='update',`第 ${r.line} 行重複，請選更新或跳過`);next=mutate(next,{streamer,type:({players:'player',songs:'song',crowns:'crown'})[kind],data:{...match,...r.data,...(match?kind==='players'?{playerId:match.playerId}:kind==='songs'?{songId:match.songId}:{id:match.id}:{})}},actor,t);}return next;}

function publicViewRoom(s,actor,t=stamp()){if(actor?.role==='admin')return structuredClone(s);const id=actor?.playerId;const view={schemaVersion:2,revision:s.revision,settings:s.settings,songs:s.songs.map(x=>({...x,plays:songPlays(s,x.songId)})),crowns:s.crowns.filter(c=>c.activatedAt||c.legacyDisplay).map(c=>({...c,ownerName:s.players.find(p=>p.playerId===c.playerId)?.name||c.ownerName||'玩家'})),cards:s.cards.map(c=>({...c,playerName:s.players.find(p=>p.playerId===c.playerId)?.name||''})),players:[],ledger:[],queue:[],wishes:[],nowPlaying:(()=>{const q=s.queue.find(q=>q.status==='waiting');return q?{title:s.songs.find(song=>song.songId===q.songId)?.title||q.title||'歌曲',stage:q.stage,preparationMinutes:q.preparationMinutes??5}:null;})(),summary:stats(s,t),hourlyUsed:usedHour(s,t),hourBucket:hourKey(t),rank:s.players.filter(p=>!p.test).map(p=>({id:p.playerId,amount:balance(s,p.playerId)})).sort((a,b)=>b.amount-a.amount).map((p,i)=>({rank:i+1,amount:p.amount,mine:p.id===id})).filter((p,i)=>i<5||p.mine)};if(id){const p=s.players.find(p=>p.playerId===id);if(p)view.players=[{playerId:p.playerId,name:p.name,ids:p.ids,names:p.names,certification:p.certification,test:p.test,hasPassword:!!p.password}];view.ledger=s.ledger.filter(x=>x.playerId===id);view.queue=s.queue.filter(x=>x.playerId===id);view.wishes=s.wishes.filter(x=>x.playerId===id);view.badges=achievements(s,id,t);view.crowns=s.crowns.filter(c=>c.playerId===id||c.activatedAt||c.legacyDisplay).map(c=>({...c,ownerName:s.players.find(p=>p.playerId===c.playerId)?.name||c.ownerName||'玩家'}));}return view;}

export function matchesSong(song,query='',tags=[]){const words=norm(query).split(/\s+/).filter(Boolean),text=norm([song.title,song.artist,song.cat,song.artistType,song.lyrics,song.murmur,...(song.tags||[])].join(' '));return words.every(w=>text.includes(w))&&(!tags.length||tags.some(t=>(song.tags||[]).includes(t)));}

export function creditNumber(value,zero=false,negative=false){const n=Number(value);requireThat(Number.isFinite(n)&&Number.isSafeInteger(n*2)&&n<1000000&&(negative||n>=(zero?0:0.5)),'首數請用 0.5 的倍數');return n;}
export const usedHour=(s,t)=>s.queue.filter(q=>q.kind==='saved'&&q.status==='completed'&&q.completedAt&&hourKey(q.completedAt)===hourKey(t)).length;
export const reservedHour=(s,t)=>s.queue.filter(q=>q.kind==='saved'&&['pending','waiting'].includes(q.status)&&hourKey(q.at)===hourKey(t)).length;
export const reservedCredits=(s,id)=>s.queue.filter(q=>q.playerId===id&&q.kind==='saved'&&['pending','waiting'].includes(q.status)).reduce((n,q)=>n+(q.creditCost||1),0);
export function quoteSong(s,id,payload={},playerId,t=stamp()){
 const song=s.songs.find(x=>x.songId===id);requireThat(song,'找不到歌曲');const cost=creditNumber(song.creditCost??1),item=x=>({songId:x.songId,title:x.title,artist:x.artist,creditCost:Number(x.creditCost??1),performances:1});
 if(cost!==0.5)return {creditCost:cost,items:[item(song)]};
 const mode=song.shortMode||'repeat';if(payload.pairSongId){requireThat(mode==='pair'||mode==='both','這首半首歌設定為唱兩次');const pair=s.songs.find(x=>x.songId===payload.pairSongId);requireThat(pair&&pair.songId!==id&&Number(pair.creditCost)===0.5&&(song.pairSongIds||[]).includes(pair.songId),'請選擇管理員指定的搭配半首歌曲');const crown=crownFor(s,pair.songId,t);requireThat(!crown||crown.playerId===playerId,'搭配歌曲有其他玩家的有效冠歌，請另選');return {creditCost:1,items:[item(song),item(pair)]};}
 requireThat(mode!=='pair','請選擇另一首半首歌搭配');return {creditCost:1,items:[{...item(song),performances:2}]};
}
const ROOM_TABLES=TABLES.filter(k=>k!=='players');
export function upgradePlatform(source){const s=structuredClone(source||empty());if(s.schemaVersion>=3)return s;
 s.streamers=[{id:'papa',slug:'papa',display_name:'怕怕',home_title:'怕怕 PARTY',active:true,created_at:stamp(),updated_at:stamp()}];s.streamerSettings={papa:structuredClone(s.settings)};
 for(const k of ROOM_TABLES)for(const row of s[k])row.streamer_id=row.streamer_id||'papa';
 // Convert existing V2 prepaid waiting requests into reservations, retaining an audit trail.
 for(const q of s.queue.filter(q=>q.kind==='saved'&&['pending','waiting'].includes(q.status))){const paid=-s.ledger.filter(l=>l.queueId===q.id&&l.amount<0).reduce((n,l)=>n+l.amount,0);if(paid)s.ledger.push({id:'completion-migration-'+q.id,streamer_id:q.streamer_id,playerId:q.playerId,amount:paid,note:'改為完成演唱才扣：歸還原預扣額',at:stamp(),excludeStats:true,test:q.test,queueId:q.id});q.creditCost=q.creditCost||paid||1;}
 if(s.streamerSettings.papa.manual===DEFAULTS.manual)s.streamerSettings.papa.manual=s.streamerSettings.papa.manual.replace('提歌扣存歌','完成演唱才扣存歌');s.schemaVersion=3;return s;
}
export function scopeState(source,streamer='papa'){const s=upgradePlatform(source),room=s.streamers.find(x=>x.id===streamer||x.slug===streamer);requireThat(room,'找不到主播');return {...s,currentStreamer:room,settings:structuredClone(s.streamerSettings[room.id]||DEFAULTS),...Object.fromEntries(ROOM_TABLES.map(k=>[k,s[k].filter(x=>x.streamer_id===room.id)]))};}
function mutateBase(source,action,actor,t=stamp()){
 const full=upgradePlatform(source),room=scopeState(full,action.streamer||source.currentStreamer?.id||'papa');
 if(action.type==='streamer'){requireThat(actor?.role==='admin','請先登入管理');const p=action.data||{},old=full.streamers.find(x=>x.id===p.id),slug=String(p.slug||old?.slug||'').trim();requireThat(/^[a-z0-9][a-z0-9-]{0,39}$/.test(slug),'網址名稱請使用小寫英文、數字或減號');requireThat(!full.streamers.some(x=>x!==old&&x.slug===slug),'主播網址已使用');requireThat(p.display_name?.trim(),'請填主播名稱');const r={...old,id:old?.id||uid(),slug,display_name:p.display_name.trim(),home_title:String(p.home_title||p.display_name),subtitle:String(p.subtitle||''),description:String(p.description||''),avatar_url:String(p.avatar_url||''),banner_url:String(p.banner_url||''),active:p.active!==false,created_at:old?.created_at||t,updated_at:t};if(old)Object.assign(old,r);else{full.streamers.push(r);full.streamerSettings[r.id]={...structuredClone(DEFAULTS),tags:[]};}full.revision++;return full;}
 // Reject cross-room identifiers instead of accidentally creating replacement rows.
 const target={song:['songs','songId'],ledger:['ledger','id'],crown:['crowns','id'],card:['cards','id']}[action.type];if(target&&action.data?.[target[1]])requireThat(room[target[0]].some(x=>x[target[1]]===action.data[target[1]]),'紀錄不屬於目前主播或已刪除');
 requireThat(room.currentStreamer.active||actor?.role==='admin','主播頁暫未開放');const next=mutateRoom(room,action,actor,t);full.players=next.players;for(const k of ROOM_TABLES)full[k]=[...full[k].filter(x=>x.streamer_id!==room.currentStreamer.id),...next[k].map(x=>({...x,streamer_id:room.currentStreamer.id}))];full.streamerSettings[room.currentStreamer.id]=next.settings;full.settings=full.streamerSettings.papa;full.revision=next.revision;return full;
}
export function publicView(source,actor,t=stamp(),streamer='papa'){const room=scopeState(source,streamer),view=publicViewRoom(room,actor,t);requireThat(room.currentStreamer.active||actor?.role==='admin','主播頁暫未開放');if(actor?.role==='admin'){delete view.streamerSettings;}return {...view,currentStreamer:room.currentStreamer,streamers:room.streamers.filter(x=>actor?.role==='admin'||x.active),schemaVersion:3,hourlyUsed:usedHour(room,t),hourlyReserved:reservedHour(room,t),hourBucket:hourKey(t)};}
export function searchAcrossStreamers(source,query){const s=upgradePlatform(source);return s.songs.filter(song=>matchesSong(song,query)).flatMap(song=>{const r=s.streamers.find(r=>r.id===song.streamer_id&&r.active);return r?[{songId:song.songId,title:song.title,artist:song.artist,streamer:r.display_name,slug:r.slug}]:[];});}

// Release A: business time is editable; registration time is immutable.
function validTime(value,now){const n=timeValue(value);requireThat(Number.isFinite(n)&&n<=timeValue(now)+60000,'實際時間請選當下或過去');return stamp(n);}
function recordId(k,r){return k==='players'?r.playerId:k==='songs'?r.songId:r.id;}
export function mutate(source,action,actor,t=stamp()){
 const before=upgradePlatform(source),room=scopeState(before,action.streamer||source.currentStreamer?.id||'papa'),p=action.data||{};
 let next;
 if(['recordTime','allocate'].includes(action.type)){
  requireThat(actor?.role==='admin','請先登入管理');
  if(action.type==='allocate'){
   const total=creditNumber(p.total),stored=creditNumber(p.stored||0,true),rows=Array.isArray(p.items)?p.items:[];
   requireThat(rows.length<=50,'一次最多分配 50 首');requirePlayer(room,p.playerId);
   const at=validTime(p.effective_at||t,t),original=p.ledgerId?room.ledger.find(l=>l.id===p.ledgerId):null; if(p.ledgerId){requireThat(original&&original.playerId===p.playerId&&original.amount===total&&!original.queueId&&!original.conversion,'請選此玩家可分配的存歌紀錄');requireThat(balance(room,p.playerId)-reservedCredits(room,p.playerId)>=total-stored,'存歌已有使用或保留，無法重新分配');}const quotes=rows.map(x=>quoteSong(room,x.songId,x,p.playerId,at));
   requireThat(stored+quotes.reduce((n,q)=>n+q.creditCost,0)===total,'現點首數加存歌首數必須等於收到總首數');
   next=before;const group=uid();
   if(stored||original)next=mutateBase(next,{streamer:room.currentStreamer.id,type:'ledger',data:{id:original?.id,playerId:p.playerId,amount:stored,at,note:p.note||'收到歌單分配存歌',openingBalance:!!p.openingBalance}},actor,t);
   for(const x of rows){next=mutateBase(next,{streamer:room.currentStreamer.id,type:'onBehalf',data:{...x,playerId:p.playerId,kind:'live',giftConfirmed:true,at,note:p.note||'',completed:!!x.completed}},actor,t);const q=next.queue.at(-1);if(q.status==='pending'){q.status='waiting';q.acceptedAt=at;}q.allocation_id=group;q.openingBalance=!!p.openingBalance;}
   for(const l of next.ledger)if(!before.ledger.some(o=>o.id===l.id))l.allocation_id=group;
  }else{
   requireThat(['queue','ledger','crowns','cards','wishes'].includes(p.table),'不支援此紀錄');
   const current=room[p.table].find(x=>x.id===p.id);requireThat(current,'紀錄不屬於目前主播或已刪除');
   next=structuredClone(before);const row=next[p.table].find(x=>x.id===p.id&&x.streamer_id===room.currentStreamer.id);
   const fields={queue:['at','acceptedAt','completedAt','cancelledAt','storedAt'],ledger:['at'],crowns:['activatedAt','expiresAt'],cards:['startsAt','expiresAt'],wishes:['at']}[p.table];
   requireThat(p.times&&Object.keys(p.times).length,'請填實際時間');
   for(const [key,value] of Object.entries(p.times)){requireThat(fields.includes(key),'不能修改登記時間');requireThat(row[key]||key==='at'||key==='startsAt','請先完成對應操作');requireThat(value,'實際時間不可留空');row[key]=['expiresAt','startsAt'].includes(key)?stamp(timeValue(value)):validTime(value,t);}
   if(p.note!==undefined)row.note=String(p.note).slice(0,1000);
   if(p.table==='queue'){
    row.recordedAt=row.status==='completed'?row.completedAt:row.at;
    for(const l of next.ledger.filter(l=>l.queueId===row.id&&l.streamer_id===row.streamer_id)){if(l.amount<0&&row.completedAt)l.at=row.completedAt;else if(l.conversion&&row.storedAt)l.at=row.storedAt;}
   }
   next.revision=before.revision+1;
  }
 }else next=mutateBase(before,action,actor,t);
 for(const k of TABLES){const old=new Map(before[k].map(r=>[recordId(k,r),r]));for(const r of next[k]){const o=old.get(recordId(k,r));if(o&&JSON.stringify(o)===JSON.stringify(r))continue;r.created_at=o?(o.created_at||o.createdAt||null):t;r.updated_at=t;r.effective_at=(k==='queue'?(r.status==='completed'?r.completedAt:r.at):k==='crowns'?r.activatedAt:k==='cards'?r.startsAt:r.at)||o?.effective_at||null;}}
 return next;
}
