import {HOME_MODULES,HERO_FIELDS,normalizeHome,validateHome} from './home-settings.js?v=9.24-H';
export function openHomeEditor({home,room,modal,dispatch,upload,demo,toast}){
 const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const initial=normalizeHome(home),field=(name,label,value,type='text',limit=160)=>`<label>${h(label)}<input name="${name}" type="${type}" value="${h(value)}" maxlength="${limit}"></label>`;
 const rows=(kind,labels,order,visible)=>`<ol class="home-order" data-home-list="${kind}">${order.map(id=>`<li draggable="true" data-home-id="${id}"><span class="drag-handle" aria-hidden="true">⠿</span><label><input type="checkbox" name="${kind}.${id}" ${visible[id]?'checked':''}>${h(labels[id])}</label><button type="button" data-home-move="-1" aria-label="${h(labels[id])}上移">↑</button><button type="button" data-home-move="1" aria-label="${h(labels[id])}下移">↓</button></li>`).join('')}</ol>`;
 modal('🎨 '+room.display_name+'的首頁設定',`<p>只調整本主播的首頁。隱藏卡片不會刪除資料或關閉功能。拖曳排序，也可以用 ↑ ↓。</p><div class="form-grid">${field('color','主題顏色',initial.color,'color')}${field('title','首頁標題（留空使用原標題）',initial.title,'text',80)}${field('subtitle','副標題（留空使用原副標題）',initial.subtitle)}${field('statusText','狀態文字（留空跟隨直播狀態）',initial.statusText,'text',80)}${field('message','自訂一句話（留空使用狀態提示）',initial.message,'text',240)}<label>主圖顯示方式<select name="imageMode"><option value="default" ${initial.imageMode==='default'?'selected':''}>使用原主圖</option><option value="custom" ${initial.imageMode==='custom'?'selected':''}>使用自訂主圖</option><option value="none" ${initial.imageMode==='none'?'selected':''}>不顯示主圖</option></select></label>${field('imageUrl','自訂主圖 HTTPS 網址',initial.imageUrl,'url',2048)}<label>上傳主圖<input name="homeImage" type="file" accept="image/*"></label></div><p class="subtle">選圖後會自動壓縮；儲存才上傳。選「使用原主圖」可恢復。</p><div class="home-editor-preview"><strong>首頁內容預覽</strong><div data-home-preview></div></div><details open><summary>首頁卡片顯示與排序</summary>${rows('modules',HOME_MODULES,initial.order,initial.visible)}</details><details><summary>本日狀態欄位顯示與排序</summary>${rows('fields',HERO_FIELDS,initial.fieldOrder,initial.fields)}</details><button type="button" data-home-reset>恢復預設排列與外觀</button><p class="subtle">恢復預設後仍需按儲存才會生效。</p>`,async(f,form)=>{
  let value=read(form);const file=f.get('homeImage');
  if(file?.size){if(demo)throw Error('預覽模式不會上傳，請在正式主播後台上傳主圖');value.imageUrl=await upload(file);value.imageMode='custom';}
  value=validateHome(value);await dispatch('settings',{home:value});toast('本主播的首頁設定已儲存');
 });
 const form=document.querySelector('#modal-form');
 function read(form){const f=new FormData(form),order=kind=>[...form.querySelectorAll(`[data-home-list="${kind}"] [data-home-id]`)].map(row=>row.dataset.homeId);return {...Object.fromEntries(['color','title','subtitle','statusText','message','imageMode','imageUrl'].map(k=>[k,f.get(k)])),order:order('modules'),fieldOrder:order('fields'),visible:Object.fromEntries(Object.keys(HOME_MODULES).map(k=>[k,f.has('modules.'+k)])),fields:Object.fromEntries(Object.keys(HERO_FIELDS).map(k=>[k,f.has('fields.'+k)]))};}
 function preview(){const v=normalizeHome(read(form)),target=form.querySelector('[data-home-preview]');target.style.borderColor=v.color;target.innerHTML=`<h3>${h(v.title||room.home_title||room.display_name)}</h3><p>${h(v.statusText||'目前直播狀態')} · ${h(v.message||'狀態提示')}</p><small>${v.order.filter(id=>v.visible[id]).map(id=>h(HOME_MODULES[id])).join(' → ')||'首頁卡片已全部隱藏'}</small>`;}
 form.addEventListener('input',preview);form.addEventListener('change',preview);
 form.addEventListener('click',e=>{const move=e.target.closest('[data-home-move]');if(move){const row=move.closest('li'),other=Number(move.dataset.homeMove)<0?row.previousElementSibling:row.nextElementSibling;if(other)Number(move.dataset.homeMove)<0?other.before(row):other.after(row);preview();}if(e.target.closest('[data-home-reset]')){const v=normalizeHome();for(const k of ['color','title','subtitle','statusText','message','imageMode','imageUrl'])form.elements.namedItem(k).value=v[k];form.elements.namedItem('homeImage').value='';for(const [kind,keys,on] of [['modules',v.order,v.visible],['fields',v.fieldOrder,v.fields]]){const list=form.querySelector(`[data-home-list="${kind}"]`);for(const id of keys){const row=list.querySelector(`[data-home-id="${id}"]`);list.append(row);row.querySelector('input').checked=on[id];}}preview();}});
 let dragged;
 form.addEventListener('dragstart',e=>{dragged=e.target.closest('[data-home-id]');if(dragged){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragged.dataset.homeId);}});
 form.addEventListener('dragover',e=>{const row=e.target.closest('[data-home-id]');if(row&&dragged&&row.parentElement===dragged.parentElement)e.preventDefault();});
 form.addEventListener('drop',e=>{const row=e.target.closest('[data-home-id]');if(row&&dragged&&row!==dragged&&row.parentElement===dragged.parentElement){e.preventDefault();const below=e.clientY>row.getBoundingClientRect().top+row.getBoundingClientRect().height/2;below?row.after(dragged):row.before(dragged);preview();}dragged=null;});
 form.addEventListener('dragend',()=>{dragged=null;});preview();
}
