import {NOTICE_TYPES,cleanNoticePrefs,noticeChannels,deriveNotices} from './notification-rules.js';
export function createNotifications({api,context,toast,onUpdate,apiUrl,apiKey}){
 const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let key='',rows=[],prefs=cleanNoticePrefs(),counts={},page=0,more=false,topic='',socket,heartbeat,reconnect,loading=false,view='',generation=0,seen=new Set(),primed=false,mutedAudio;
 const dialog=document.createElement('dialog');dialog.id='notification-dialog';dialog.className='notice-dialog';document.body.append(dialog);
 const sound=new Audio(new URL('../assets/notification.m4a',import.meta.url));sound.preload='none';let unlocked=false;
 const storageKey=k=>'pa-notice-'+key+'-'+k;
 const read=(k,fallback)=>{try{return JSON.parse(localStorage.getItem(storageKey(k)))??fallback;}catch{return fallback;}};
 const write=(k,v)=>{try{localStorage.setItem(storageKey(k),JSON.stringify(v));}catch{throw Error('裝置儲存空間不足，請使用較小音效');}};
 function stop(){clearInterval(heartbeat);clearTimeout(reconnect);if(socket){socket.onclose=null;socket.close();socket=null;}topic='';}
 function identity(){const c=context(),next=c.recipient?`${c.demo?'demo:':''}${c.streamer}:${c.recipient}`:'';if(key===next)return c;key=next;generation++;stop();rows=[];counts={};page=0;seen=new Set();primed=false;view='';dialog.close();prefs=cleanNoticePrefs();sound.pause();unlocked=false;if(key)sound.src=read('sound',null)||new URL('../assets/notification.m4a',import.meta.url).href;return c;}
 function button(){identity();const total=Object.entries(counts).reduce((n,[t,c])=>n+(noticeChannels(prefs,t).badge?c:0),0);return key?`<button type="button" data-notice="open">🔔 訊息${total?` <span class="notice-count">${total>99?'99+':total}</span>`:''}</button>`:'';}
 function updateButton(){for(const el of document.querySelectorAll('header [data-notice="open"]')){const wrapper=document.createElement('div');wrapper.innerHTML=button();el.replaceWith(...wrapper.childNodes);}}
 function connect(ch){if(ch===topic&&socket)return;stop();topic=ch;const myGeneration=generation;const start=()=>{if(myGeneration!==generation)return;socket=new WebSocket(apiUrl.replace(/^https:/,'wss:').replace(/\/functions\/v1\/.*$/,'/realtime/v1/websocket')+'?apikey='+encodeURIComponent(apiKey)+'&vsn=1.0.0');let ref=1;const send=(event,payload,channel='realtime:papa-notice:'+ch)=>socket?.readyState===1&&socket.send(JSON.stringify({topic:channel,event,payload,ref:String(ref++),join_ref:'1'}));socket.onopen=()=>{send('phx_join',{config:{broadcast:{ack:false,self:false},presence:{enabled:false},private:false}});heartbeat=setInterval(()=>send('heartbeat',{},'phoenix'),25000);refresh();};socket.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.event==='broadcast')refresh();}catch{}};socket.onclose=()=>{clearInterval(heartbeat);reconnect=setTimeout(start,10000);};};start();}
 async function play(){if(!unlocked)return false;try{sound.currentTime=0;await sound.play();return true;}catch{return false;}}
 async function unlock(){try{sound.muted=true;await sound.play();sound.pause();sound.currentTime=0;sound.muted=false;unlocked=true;}catch{sound.muted=false;}}
 document.addEventListener('pointerdown',()=>{if(!unlocked&&key)unlock();},{passive:true});
 async function refresh(){const c=identity();if(!key||loading)return;const g=generation;loading=true;try{const data=c.demo?read('data',{rows:[],preferences:{},unread:{}}):await api({op:'notifications',page});if(g!==generation)return;const latestPage=page>0&&!c.demo?await api({op:'notifications',page:0}):data;if(g!==generation)return;const previous=primed;const latest=c.demo?(data.rows||[]).slice(page*50,page*50+51):(data.rows||[]);prefs=cleanNoticePrefs(latestPage.preferences);counts=latestPage.unread||{};more=latest.length>50;rows=latest.slice(0,50);{const fresh=(latestPage.rows||[]).slice(0,50).filter(n=>!seen.has(n.id)&&!n.read_at);for(const n of (latestPage.rows||[]).slice(0,50))seen.add(n.id);if(previous){const active=fresh.filter(n=>Date.now()-Date.parse(n.created_at)<120000);const pop=active.find(n=>noticeChannels(prefs,n.type).popup);if(pop&&!document.hidden)toast(pop.body);const audible=active.find(n=>noticeChannels(prefs,n.type).sound);if(audible&&!document.hidden){const ring=async()=>{if(read('lastSound',null)===audible.id)return;if(await play())write('lastSound',audible.id);};if(navigator.locks)await navigator.locks.request(storageKey('audio-lock'),ring);else await ring();}}primed=true;}if(!c.demo&&data.topic)connect(data.topic);updateButton();if(view==='inbox')showInbox(false);if(previous&&rows.some(n=>!n.read_at)&&!dialog.open)onUpdate?.();}finally{loading=false;}}
 function shell(title,html){dialog.innerHTML=`<div class="dialog-head"><h2>${escape(title)}</h2><button type="button" data-notice="close" aria-label="關閉通知">✕</button></div>${html}<p class="error" id="notice-error" role="status"></p>`;if(!dialog.open)dialog.showModal();}
 function showInbox(open=true){view='inbox';const visible=rows.filter(n=>noticeChannels(prefs,n.type).center);shell('🔔 系統通知',`<div class="actions"><button data-notice="settings">⚙️ 通知設定</button><button data-notice="mute">${prefs.muteAll?'🔔 恢復通知':'🔕 暫停通知'}</button><button data-notice="readPage">本頁全部已讀</button></div><p class="subtle">${escape(context().streamerName||'目前主播')} · 最新在上${prefs.muteAll?' · 已靜音，紀錄仍保留':''}</p>${visible.map(n=>`<article class="notice-item ${n.read_at?'':'unread'}"><small>${n.level===2?'🔴 即時重要':'🟠 一般異動'} · ${escape(n.streamer_name)} · ${escape(new Date(n.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'}))}</small><p>${escape(n.body)}</p>${n.read_at?'<small>已讀</small>':`<button data-notice="read" data-notice-id="${escape(n.id)}">標為已讀</button>`}</article>`).join('')||'<div class="empty">目前沒有通知 ♡</div>'}<div class="pagination"><button data-notice="prev" ${page?'':'disabled'}>上一頁</button><span>第 ${page+1} 頁</span><button data-notice="next" ${more?'':'disabled'}>下一頁</button></div>`);}
 function showSettings(){view='settings';const checkbox=(name,on,label)=>`<label class="check-row"><input type="checkbox" name="${name}" ${on?'checked':''}>${label}</label>`;shell('⚙️ 通知設定',`<form id="notice-settings"><p>設定只套用在你於此主播的通知。關閉提醒仍保留事件紀錄。</p>${checkbox('muteAll',prefs.muteAll,'🔕 暫停所有畫面、音效與推播提醒')}${checkbox('muteSound',prefs.muteSound,'關閉所有音效')}${checkbox('pushEnabled',prefs.pushEnabled,'允許系統推播（另需啟用這台裝置）')}<div class="actions"><button type="button" data-notice="enablePush">啟用這台裝置推播</button><button type="button" data-notice="disablePush">停用這台裝置推播</button><button type="button" data-notice="sound">試聽音效</button><button type="button" data-notice="testPush">發送測試通知</button></div><label>替換本裝置音效（最多 256 KB）<input type="file" id="notice-sound-file" accept="audio/*"></label><button type="button" data-notice="resetSound">恢復預設音效</button><p class="subtle">自訂音效在網頁開啟時播放。背景／鎖屏聲音由裝置控制。iPhone 若無法啟用，請先將網站加入主畫面並從主畫面開啟。</p><div class="notice-settings-grid">${Object.entries(NOTICE_TYPES).map(([type,[name]])=>`<fieldset><legend>${name}</legend>${[['center','訊息中心'],['popup','畫面提醒'],['sound','音效'],['push','Push'],['badge','紅點']].map(([k,label])=>checkbox(type+'.'+k,prefs.types[type][k],label)).join('')}</fieldset>`).join('')}</div><p class="subtle">私訊、留言、公告與勳章的事件會在對應批次開放。</p><div class="actions"><button type="button" data-notice="open">返回通知</button><button class="primary" type="submit">儲存設定</button></div></form>`);}
 async function save(p){if(context().demo){const d=read('data',{rows:[],unread:{}});d.preferences=cleanNoticePrefs(p);write('data',d);}else await api({op:'noticePreferences',preferences:p});prefs=cleanNoticePrefs(p);await refresh();}
 async function mark(ids){if(context().demo){const d=read('data',{rows:[],preferences:{}});for(const n of d.rows)if(ids.includes(n.id))n.read_at=new Date().toISOString();d.unread=countUnread(d.rows);write('data',d);}else await api({op:'noticeRead',ids});await refresh();}
 const countUnread=items=>items.filter(n=>!n.read_at).reduce((a,n)=>(a[n.type]=(a[n.type]||0)+1,a),{});
 async function registration(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw Error('此瀏覽器尚不支援推播，通知中心仍可使用');return navigator.serviceWorker.register(new URL('../sw.js',import.meta.url));}
 async function pushOn(){if(context().demo)throw Error('預覽模式不訂閱正式推播');if(!('serviceWorker'in navigator)||!('PushManager'in window))throw Error('此瀏覽器尚不支援推播，通知中心仍可使用');const permissionRequest=Notification.requestPermission();toast('請在瀏覽器的通知權限提示中選擇允許');const permission=await permissionRequest;if(permission!=='granted')throw Error('通知未獲允許，請在瀏覽器設定開啟');await registration();const reg=await navigator.serviceWorker.ready;const {publicKey}=await api({op:'pushKey'});const decoded=atob(publicKey.replace(/-/g,'+').replace(/_/g,'/'));const sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(decoded,c=>c.charCodeAt(0))});await api({op:'pushSubscribe',subscription:sub.toJSON()});await save({...prefs,pushEnabled:true});showSettings();toast('此裝置已啟用推播');}
 async function pushOff(){if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.getRegistration(new URL('../',import.meta.url));const sub=await reg?.pushManager.getSubscription();if(sub)await api({op:'pushUnsubscribe',endpoint:sub.endpoint});toast('已停用此主播在本裝置的推播');}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-notice]');if(!b)return;e.preventDefault();try{identity();switch(b.dataset.notice){case'open':page=0;await refresh();showInbox();break;case'close':view='';dialog.close();break;case'settings':showSettings();break;case'mute':await save({...prefs,muteAll:!prefs.muteAll});break;case'read':await mark([b.dataset.noticeId]);break;case'readPage':await mark(rows.map(n=>n.id));break;case'prev':page=Math.max(0,page-1);await refresh();break;case'next':page++;await refresh();break;case'enablePush':if(!('Notification'in window))throw Error('此瀏覽器不支援推播');await pushOn();break;case'disablePush':await pushOff();break;case'testPush':if(context().demo)throw Error('請在正式登入後測試推播');await api({op:'noticeTest'});await refresh();toast('測試通知已送出');break;case'sound':unlocked=true;if(!await play())throw Error('音效無法播放，請再按一次試聽');break;case'resetSound':write('sound',null);sound.src=new URL('../assets/notification.m4a',import.meta.url).href;toast('已恢復你提供的預設音效');break;}}catch(err){const target=dialog.querySelector('#notice-error');if(target)target.textContent=err.message;else toast(err.message);}});
 dialog.addEventListener('close',()=>{view='';});
 dialog.addEventListener('submit',async e=>{if(e.target.id!=='notice-settings')return;e.preventDefault();const f=new FormData(e.target),p=cleanNoticePrefs();for(const k of ['muteAll','muteSound','pushEnabled'])p[k]=f.has(k);for(const type of Object.keys(NOTICE_TYPES))for(const k of Object.keys(p.types[type]))p.types[type][k]=f.has(type+'.'+k);try{await save(p);toast('通知設定已儲存');showInbox();}catch(err){dialog.querySelector('#notice-error').textContent=err.message;}});
 dialog.addEventListener('change',async e=>{if(e.target.id!=='notice-sound-file')return;const file=e.target.files[0];if(!file)return;try{if(!file.type.startsWith('audio/')||file.size>262144)throw Error('請選擇 256 KB 以下的音效檔');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const probe=new Audio(data);await new Promise((resolve,reject)=>{probe.onloadedmetadata=resolve;probe.onerror=()=>reject(Error('此瀏覽器無法播放這個音效格式'));});write('sound',data);sound.src=data;toast('本裝置音效已替換');}catch(err){dialog.querySelector('#notice-error').textContent=err.message;}});
 setInterval(()=>{if(!document.hidden)refresh().catch(()=>{});},30000);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh().catch(()=>{});});
 window.addEventListener('hashchange',()=>{identity();refresh().catch(()=>{});});
 return {button,refresh,localChange(before,after,action,actor){identity();const c=context();const all=deriveNotices(before,after,{streamer_id:after.streamers.find(x=>x.slug===c.streamer)?.id||c.streamer,role:actor?.role},new Date().toISOString());for(const recipient of new Set(all.map(n=>n.recipient))){const k=`pa-notice-demo:${c.streamer}:${recipient}-data`;let d;try{d=JSON.parse(localStorage.getItem(k));}catch{}d||={rows:[],preferences:{}};d.rows.unshift(...all.filter(n=>n.recipient===recipient));d.unread=countUnread(d.rows);localStorage.setItem(k,JSON.stringify(d));}refresh().catch(()=>{});}};
}

